from wordfreq import zipf_frequency
import json

# Curated SAT vocabulary with definitions and POS
# Only words NOT in the existing words.js
WORDS = [
# A
("abandon","v.","to give up completely; to desert"),
("aberrant","adj.","departing from the accepted standard"),
("abeyance","n.","a state of temporary inactivity"),
("ablution","n.","the act of washing or cleansing"),
("abnegate","v.","to renounce or give up a right or belief"),
("abominable","adj.","extremely hateful or detestable"),
("aboriginal","adj.","being the first or earliest known; indigenous"),
("abortive","adj.","failing to achieve the intended result"),
("abrasive","adj.","harsh or rough in manner; causing irritation"),
("abreast","adv.","alongside; up to date with"),
("abscission","n.","the natural separation of a part from a whole"),
("absolve","v.","to declare free from guilt or blame"),
("abstain","v.","to restrain oneself from indulging"),
("abundance","n.","a very large quantity; plentifulness"),
("abut","v.","to border on or be next to"),
("abysmal","adj.","extremely bad; measurelessly deep"),
("acclimate","v.","to become accustomed to a new environment"),
("acclivity","n.","an upward slope or incline"),
("accomplice","n.","a partner in crime"),
("accost","v.","to approach and address aggressively"),
("accrete","v.","to grow or accumulate gradually"),
("accrue","v.","to accumulate or increase over time"),
("acerbity","n.","sharpness or harshness of tone or manner"),
("acidulous","adj.","slightly sour or sharp in taste or manner"),
("acoustics","n.","the qualities of a room that affect how sound is heard"),
("acquisitive","adj.","eager to acquire and possess things"),
("acquittal","n.","a judgment of not guilty"),
("acrimonious","adj.","angry and bitter in tone or manner"),
("actuarial","adj.","relating to insurance risk calculation"),
("actuary","n.","a person who calculates insurance risks"),
("addendum","n.","an additional item appended to a document"),
("adherent","n.","a supporter or follower of a cause"),
("adjunct","n.","something added but not essential"),
("admonition","n.","a firm warning or gentle reproof"),
("adventitious","adj.","occurring by chance rather than design"),
("aegis","n.","protection or sponsorship of a powerful authority"),
("affluence","n.","the state of having great wealth"),
("aggrandize","v.","to increase the power or reputation of"),
("ailment","n.","a minor illness or physical complaint"),
("albeit","conj.","although; even though"),
("alcove","n.","a small recessed area in a room or garden"),
("alias","n.","an assumed or false name"),
("allege","v.","to claim without proof"),
("allude","v.","to make an indirect reference to"),
("amass","v.","to gather together a large quantity"),
("ambient","adj.","relating to the surrounding environment"),
("amenable","adj.","willing to accept or be influenced"),
("amiable","adj.","friendly and pleasant in manner"),
("amnesty","n.","an official pardon for political offenses"),
("amoral","adj.","lacking a moral sense; unconcerned with morality"),
("ample","adj.","more than enough; plentiful"),
("anachronism","n.","something out of its proper time period"),
("analogous","adj.","comparable in certain respects"),
("anarchist","n.","a person who advocates abolition of government"),
("anarchy","n.","absence of government; political disorder"),
("ancillary","adj.","providing support to a primary activity"),
("annex","v.","to add territory to one's own domain"),
("annihilate","v.","to destroy completely"),
("annotate","v.","to add explanatory notes to a text"),
("annuity","n.","a fixed sum paid to someone each year"),
("anoint","v.","to ceremonially apply oil; to designate as chosen"),
("anthem","n.","a rousing or uplifting song associated with a group"),
("antidote","n.","a remedy that counteracts a poison or disease"),
("antipathy","n.","a deep feeling of dislike or aversion"),
("antiquity","n.","the ancient past; great age"),
("apex","n.","the highest point or peak"),
("aplomb","n.","self-confidence and composure"),
("apocryphal","adj.","of doubtful authenticity; fictitious"),
("apparition","n.","a ghostly figure; a sudden appearance"),
("appellation","n.","a name or title"),
("apposite","adj.","very appropriate to the situation"),
("appraise","v.","to assess the value or quality of"),
("appreciable","adj.","large enough to be noticed or measured"),
("apprehensive","adj.","anxious or fearful about the future"),
("apropos","adj.","very appropriate to a particular situation"),
("aptitude","n.","a natural ability or talent"),
("arable","adj.","suitable for growing crops"),
("arbitrate","v.","to settle a dispute as a neutral party"),
("ardent","adj.","passionate; enthusiastic"),
("aria","n.","a long accompanied song for a solo voice in opera"),
("aristocracy","n.","the highest social class; government by the elite"),
("armistice","n.","an agreement to stop fighting temporarily"),
("arraign","v.","to call before a court to answer charges"),
("artifice","n.","clever trickery or deception"),
("ascendancy","n.","dominance or controlling influence"),
("assail","v.","to attack violently or criticize strongly"),
("assent","v.","to agree or express approval"),
("assert","v.","to state confidently and forcefully"),
("assuage","v.","to make less intense; to relieve or soothe"),
("astringent","adj.","sharp or severe in manner; causing contraction"),
("atone","v.","to make amends for a wrongdoing"),
("atrophy","n.","gradual decline in strength or effectiveness"),
("autocrat","n.","a ruler with absolute power"),
("avarice","n.","excessive greed for wealth"),
("avid","adj.","having a keen interest or enthusiasm"),
("avow","v.","to declare openly and without shame"),
("axiom","n.","a statement accepted as true without proof"),
# B
("baffle","v.","to bewilder or confuse completely"),
("balk","v.","to hesitate or refuse to proceed"),
("banality","n.","the quality of being unoriginal or dull"),
("bane","n.","a cause of great distress or annoyance"),
("barrage","n.","an overwhelming number of things arriving at once"),
("barren","adj.","too poor to produce vegetation; unproductive"),
("bastion","n.","a stronghold or fortified position"),
("befuddle","v.","to confuse or perplex"),
("begrudge","v.","to envy someone's possession or enjoyment"),
("beguile","v.","to charm or enchant, often deceptively"),
("behemoth","n.","something enormous in size or power"),
("beleaguer","v.","to cause persistent difficulty or harassment"),
("bellicose","adj.","demonstrating aggression and willingness to fight"),
("bemoan","v.","to express sorrow or discontent about"),
("benefactor","n.","a person who gives financial or other aid"),
("benign","adj.","gentle and kind; not harmful"),
("berate","v.","to scold harshly and at length"),
("bereft","adj.","deprived of or lacking something"),
("bestow","v.","to confer or present as a gift"),
("betoken","v.","to be a sign or indication of"),
("bigot","n.","a person intolerant of differing opinions"),
("blatant","adj.","completely obvious and without subtlety"),
("blight","n.","a thing that spoils or damages"),
("bliss","n.","perfect happiness; great joy"),
("blithe","adj.","showing casual and cheerful indifference"),
("bombastic","adj.","using high-sounding but meaningless language"),
("bourgeois","adj.","relating to the middle class; conventional"),
("brandish","v.","to wave something as a threat or display"),
("brazen","adj.","bold and shameless"),
("brevity","n.","concise and exact use of words; shortness of time"),
("broach","v.","to raise a subject for discussion"),
("bucolic","adj.","relating to the pleasant aspects of rural life"),
("bulwark","n.","a defensive wall or strong support"),
("bungle","v.","to carry out clumsily or incompetently"),
("buoyant","adj.","cheerful and optimistic; able to float"),
("bureaucracy","n.","a system of government with many complex rules"),
("burnish","v.","to polish something by rubbing"),
# C
("cabal","n.","a secret political group plotting against authority"),
("cajole","v.","to persuade through flattery or coaxing"),
("calamity","n.","a disastrous event causing great damage"),
("calibrate","v.","to adjust precisely for a particular purpose"),
("callous","adj.","showing cruel disregard for others"),
("candid","adj.","truthful and straightforward; frank"),
("cantankerous","adj.","bad-tempered and uncooperative"),
("capacious","adj.","having a lot of space inside; roomy"),
("capitulate","v.","to surrender or give in to demands"),
("capricious","adj.","given to sudden changes of mood or behavior"),
("cardinal","adj.","of the greatest importance; fundamental"),
("carnage","n.","the killing of a large number of people"),
("carouse","v.","to drink and enjoy oneself with others"),
("carp","v.","to complain or find fault continually"),
("cascade","n.","a waterfall; a succession of things"),
("castigate","v.","to reprimand or punish severely"),
("catharsis","n.","the release of strong emotions; purification"),
("caustic","adj.","sarcastic in a scathing way; chemically corrosive"),
("cavalier","adj.","showing a lack of proper concern; offhand"),
("cede","v.","to yield or formally surrender"),
("celerity","n.","swiftness of movement; speed"),
("cerebral","adj.","relating to the intellect rather than emotions"),
("chaff","n.","worthless matter; trivial banter"),
("chagrin","n.","distress caused by humiliation or failure"),
("charisma","n.","compelling attractiveness that inspires devotion"),
("charlatan","n.","a person falsely claiming special knowledge"),
("chasm","n.","a deep gap or opening; a profound difference"),
("chastise","v.","to rebuke or punish severely"),
("chicanery","n.","the use of trickery to achieve a goal"),
("chronic","adj.","persisting for a long time; habitual"),
("circuitous","adj.","longer than the most direct route; roundabout"),
("circumscribe","v.","to restrict or limit; to draw a line around"),
("circumvent","v.","to find a way around an obstacle or rule"),
("clandestine","adj.","kept secret or done in a hidden way"),
("clemency","n.","mercy or leniency shown to an offender"),
("cliché","n.","an overused phrase or idea"),
("coalesce","v.","to come together to form one mass or whole"),
("codify","v.","to arrange into a systematic code"),
("coerce","v.","to persuade using force or threats"),
("cognizant","adj.","having knowledge or awareness"),
("colloquial","adj.","used in ordinary or familiar conversation"),
("collusion","n.","secret cooperation for a dishonest purpose"),
("commemorate","v.","to recall and honor the memory of"),
("commend","v.","to praise formally or officially"),
("commodity","n.","a raw material or product that can be traded"),
("communal","adj.","shared by all members of a community"),
("compelling","adj.","evoking strong interest or attention"),
("compensate","v.","to give something in return for loss or suffering"),
("compile","v.","to gather and assemble information systematically"),
("complacent","adj.","smugly self-satisfied and uncritical"),
("comply","v.","to act in accordance with a wish or command"),
("comprise","v.","to consist of; to be made up of"),
("concede","v.","to admit that something is true after resistance"),
("concerted","adj.","jointly arranged or carried out"),
("conciliatory","adj.","intended to make peace or goodwill"),
("concurrent","adj.","existing or happening at the same time"),
("condone","v.","to accept behavior considered wrong"),
("confiscate","v.","to seize property by authority"),
("confound","v.","to surprise and confuse greatly"),
("congenial","adj.","pleasant because suited to one's character"),
("connoisseur","n.","an expert judge in matters of fine taste"),
("conscientious","adj.","thorough and careful in one's work or duty"),
("consecrate","v.","to make or declare sacred"),
("consensus","n.","general agreement among a group"),
("console","v.","to comfort someone in grief or disappointment"),
("consolidate","v.","to strengthen or combine into a single whole"),
("conspicuous","adj.","standing out so as to be clearly visible"),
("construe","v.","to interpret or understand in a particular way"),
("consummate","adj.","supremely skilled; complete in every detail"),
("contentious","adj.","causing or likely to cause disagreement"),
("contrite","adj.","feeling deep regret and guilt for a wrong"),
("contrived","adj.","deliberately created rather than natural"),
("convene","v.","to come together for a meeting or activity"),
("conversant","adj.","familiar with or knowledgeable about"),
("convivial","adj.","friendly, lively, and enjoyable"),
("copious","adj.","abundant in supply or quantity"),
("cordial","adj.","warm and friendly"),
("corroborate","v.","to confirm or give support to a statement"),
("cosmopolitan","adj.","having worldwide scope; worldly and sophisticated"),
("countenance","n.","a person's face or facial expression"),
("covert","adj.","not openly acknowledged or displayed; secret"),
("crass","adj.","showing no sensitivity; stupid and crude"),
("credence","n.","belief in something as true"),
("criterion","n.","a standard by which something is judged"),
("cull","v.","to select from a large quantity; to reduce by removal"),
("culminate","v.","to reach the highest point or final stage"),
("culpable","adj.","deserving blame or censure"),
("cumulative","adj.","increasing by successive additions"),
("cursory","adj.","hasty and therefore not thorough"),
("curtail","v.","to reduce in extent or quantity"),
("cynical","adj.","distrustful of human sincerity or integrity"),
# D
("dearth","n.","a scarcity or lack of something"),
("debacle","n.","a sudden disastrous collapse or failure"),
("debunk","v.","to expose the falseness of an idea or belief"),
("decadence","n.","moral or cultural decline; excessive indulgence"),
("decimate","v.","to destroy a large proportion of"),
("decree","n.","an official order issued by a legal authority"),
("decry","v.","to publicly denounce or criticize"),
("deem","v.","to consider or regard in a specified way"),
("default","n.","failure to fulfill an obligation"),
("deference","n.","respectful submission to another's judgment"),
("deft","adj.","demonstrating skill and cleverness"),
("delineate","v.","to describe or indicate precisely"),
("deluge","n.","a great flood; an overwhelming amount"),
("demeanor","n.","outward behavior or bearing"),
("demise","n.","a person's death; the end of something"),
("demolish","v.","to destroy completely; to refute decisively"),
("denote","v.","to be a sign of; to indicate"),
("denounce","v.","to publicly declare to be wrong or evil"),
("depict","v.","to represent in a drawing or painting; to describe"),
("deplete","v.","to use up the supply or resources of"),
("deplore","v.","to feel or express strong disapproval of"),
("depose","v.","to remove from office suddenly and forcefully"),
("deprecate","v.","to express disapproval of; to belittle"),
("derelict","adj.","in a very poor condition; neglectful of duty"),
("derivative","adj.","imitative of another's work; not original"),
("descry","v.","to catch sight of something difficult to see"),
("desecrate","v.","to treat a sacred place with violent disrespect"),
("despot","n.","a ruler who holds absolute power, typically cruelly"),
("destitute","adj.","without basic necessities; extremely poor"),
("detached","adj.","separate or disconnected; emotionally uninvolved"),
("detract","v.","to diminish the worth or value of"),
("deviate","v.","to depart from an established course"),
("devious","adj.","using dishonest or indirect methods"),
("devoid","adj.","entirely lacking or free from"),
("devout","adj.","deeply religious; totally committed"),
("dexterous","adj.","showing skill with the hands; clever"),
("dialectical","adj.","relating to logical discussion of ideas"),
("didactic","adj.","intended to teach or instruct"),
("diffident","adj.","modest or shy because of a lack of confidence"),
("diffuse","v.","to spread over a wide area; adj. not concentrated"),
("digress","v.","to stray from the main subject"),
("dilapidated","adj.","in a state of disrepair from age or neglect"),
("dilate","v.","to become wider or larger; to speak at length"),
("diligent","adj.","having careful and persistent effort"),
("diminish","v.","to make or become less"),
("dirge","n.","a slow mournful piece of music for a funeral"),
("disaffected","adj.","dissatisfied and no longer loyal"),
("discern","v.","to perceive or recognize clearly"),
("disclose","v.","to make known or reveal"),
("discordant","adj.","disagreeing or incongruous"),
("discourse","n.","written or spoken communication on a subject"),
("discreet","adj.","careful and prudent; unobtrusive"),
("discrepancy","n.","a difference between things expected to be the same"),
("discretion","n.","the quality of behaving prudently; freedom of choice"),
("disdain","n.","the feeling that someone is unworthy of consideration"),
("disenfranchise","v.","to deprive of the right to vote"),
("disinterested","adj.","not influenced by personal involvement; impartial"),
("dismantle","v.","to take apart piece by piece"),
("disparage","v.","to regard or represent as being of little worth"),
("disparate","adj.","essentially different in kind"),
("dispassionate","adj.","not influenced by strong emotion; rational"),
("dispatch","v.","to send off quickly to a destination"),
("dispel","v.","to make a feeling or belief disappear"),
("disposition","n.","a person's inherent qualities of character"),
("disproportion","n.","a lack of balance or equality"),
("disseminate","v.","to spread information widely"),
("dissent","n.","disagreement with a prevailing opinion"),
("dissonance","n.","lack of harmony; a tension between conflicting ideas"),
("dissuade","v.","to persuade someone not to do something"),
("distill","v.","to extract the essential meaning or element"),
("diverse","adj.","showing a great deal of variety"),
("divest","v.","to deprive or rid of something"),
("docile","adj.","ready to accept instruction; submissive"),
("dogma","n.","a set of principles laid down by an authority"),
("domestic","adj.","relating to the home; of one's own country"),
("dormant","adj.","temporarily inactive; in a state of rest"),
("dubious","adj.","hesitating or doubting; of questionable value"),
("duplicity","n.","deceitfulness; double-dealing"),
# E
("eclectic","adj.","deriving ideas from a broad range of sources"),
("edify","v.","to instruct or improve morally or intellectually"),
("efface","v.","to erase or make oneself inconspicuous"),
("efficacious","adj.","successful in producing a desired result"),
("egalitarian","adj.","believing in equal rights for all people"),
("egregious","adj.","outstandingly bad; shocking"),
("elaborate","adj.","detailed and complicated; v. to explain in detail"),
("elated","adj.","ecstatically happy"),
("elegy","n.","a poem of serious reflection on death or loss"),
("elicit","v.","to draw out a response or reaction"),
("elite","n.","a group of people considered superior"),
("eloquent","adj.","fluent or persuasive in speaking or writing"),
("elucidate","v.","to make something clear; to explain"),
("elude","v.","to evade or escape skillfully"),
("emaciate","v.","to make abnormally thin or weak"),
("emanate","v.","to issue or spread out from a source"),
("embargo","n.","a government order restricting trade"),
("embellish","v.","to make more attractive by adding details"),
("embody","v.","to give a body to; to represent in visible form"),
("eminent","adj.","famous and respected in a particular field"),
("empirical","adj.","based on observation or experience, not theory"),
("emulate","v.","to match or surpass by imitation"),
("enact","v.","to make into law; to act out"),
("encompass","v.","to surround or include comprehensively"),
("encroach","v.","to intrude on someone's territory or rights"),
("endemic","adj.","native to and widespread in a particular area"),
("endow","v.","to provide with a quality or ability"),
("enervate","v.","to drain of energy or vitality"),
("engender","v.","to cause or give rise to"),
("enhance","v.","to increase the quality, value, or extent of"),
("enigmatic","adj.","mysterious and difficult to understand"),
("enmity","n.","a state of deep-seated hostility"),
("ennui","n.","a feeling of boredom and dissatisfaction"),
("entail","v.","to involve as a necessary consequence"),
("enthrall","v.","to capture the attention of; to fascinate"),
("entreat","v.","to ask someone earnestly or anxiously"),
("ephemeral","adj.","lasting for a very short time"),
("epitome","n.","a perfect example of a quality or type"),
("equanimity","n.","mental calmness and composure"),
("equitable","adj.","fair and impartial"),
("equivocal","adj.","open to more than one interpretation; ambiguous"),
("erode","v.","to gradually destroy or diminish"),
("erudite","adj.","having or showing great knowledge"),
("espouse","v.","to adopt or support a cause or belief"),
("estrange","v.","to cause someone to become unfriendly or distant"),
("ethereal","adj.","extremely delicate and light; heavenly"),
("euphemism","n.","a mild expression substituted for a harsh one"),
("evanescent","adj.","quickly fading from sight or memory"),
("exacerbate","v.","to make a problem or situation worse"),
("exacting","adj.","making great demands; requiring precision"),
("exalt","v.","to praise highly or hold in high regard"),
("excerpt","n.","a short extract from a text or performance"),
("exemplify","v.","to serve as a typical example of"),
("exempt","adj.","free from an obligation imposed on others"),
("exhort","v.","to strongly encourage or urge"),
("exodus","n.","a mass departure of people"),
("exonerate","v.","to absolve from blame or fault"),
("expedient","adj.","convenient and practical, though possibly improper"),
("expedite","v.","to make an action happen sooner or faster"),
("explicit","adj.","stated clearly and in detail"),
("exploit","v.","to use selfishly for one's own ends"),
("exposition","n.","a comprehensive description or explanation"),
("expunge","v.","to erase or remove completely"),
("extant","adj.","still in existence; surviving"),
("extol","v.","to praise enthusiastically"),
("extraneous","adj.","irrelevant or unrelated to the subject"),
("extricate","v.","to free from a constraint or difficulty"),
("exuberant","adj.","filled with lively energy and excitement"),
# F
("fabricate","v.","to invent or make up; to construct"),
("facet","n.","one side of something many-sided; an aspect"),
("facetious","adj.","treating serious issues with inappropriate humor"),
("fallacious","adj.","based on a mistaken belief"),
("fallacy","n.","a mistaken belief based on unsound reasoning"),
("fallow","adj.","left unplanted; inactive"),
("fanatical","adj.","filled with excessive zeal"),
("fastidious","adj.","very attentive to detail; hard to please"),
("fatuous","adj.","silly and pointless"),
("fawn","v.","to give a servile display of affection"),
("feasible","adj.","possible and practical to do"),
("feckless","adj.","lacking initiative or strength of character"),
("feign","v.","to pretend to be affected by something"),
("felicitous","adj.","well chosen or suited to the circumstances"),
("fervent","adj.","having or displaying passionate intensity"),
("fester","v.","to become worse or more intense over time"),
("fiscal","adj.","relating to government revenue and finances"),
("flagrant","adj.","conspicuously or obviously offensive"),
("flaunt","v.","to display ostentatiously"),
("flippant","adj.","not showing proper respect or seriousness"),
("fluctuate","v.","to rise and fall irregularly"),
("foment","v.","to instigate or stir up trouble"),
("forbearance","n.","patient self-control; restraint"),
("forestall","v.","to prevent by taking action in advance"),
("formidable","adj.","inspiring fear or respect through power"),
("forthright","adj.","direct and outspoken; straightforward"),
("fortuitous","adj.","happening by chance; fortunate"),
("foster","v.","to encourage or promote the development of"),
("founder","v.","to fail or come to nothing; to sink"),
("frail","adj.","weak and delicate"),
("frivolous","adj.","not having any serious purpose or value"),
("frugal","adj.","sparing or economical with money or resources"),
("futile","adj.","incapable of producing any useful result"),
# G
("gainsay","v.","to deny or contradict"),
("garner","v.","to gather or collect"),
("garrulous","adj.","excessively talkative"),
("gauge","v.","to estimate or determine the amount or level of"),
("genesis","n.","the origin or mode of formation of something"),
("genial","adj.","friendly and cheerful"),
("germane","adj.","relevant to the matter at hand"),
("gesticulate","v.","to use gestures to express meaning"),
("glean","v.","to obtain information from various sources"),
("glib","adj.","fluent but insincere and shallow"),
("goad","v.","to provoke or annoy to stimulate action"),
("grandeur","n.","splendor and impressiveness of appearance"),
("grandiose","adj.","impressive or magnificent; pretentiously grand"),
("gratuitous","adj.","uncalled for; lacking good reason"),
("gregarious","adj.","fond of company; sociable"),
("grievous","adj.","very severe or serious"),
("guile","n.","sly or cunning intelligence; craftiness"),
("gullible","adj.","easily persuaded to believe something"),
# H
("hackneyed","adj.","unoriginal and trite from overuse"),
("hamper","v.","to hinder or impede the progress of"),
("haphazard","adj.","lacking any obvious order or planning"),
("hapless","adj.","unfortunate; having bad luck"),
("harangue","n.","a lengthy and aggressive speech"),
("hardy","adj.","robust; capable of enduring difficult conditions"),
("havoc","n.","widespread destruction or disorder"),
("hedonist","n.","a person devoted to the pursuit of pleasure"),
("heed","v.","to pay attention to; to take notice of"),
("heinous","adj.","utterly wicked and shocking"),
("heresy","n.","belief or opinion contrary to accepted doctrine"),
("hermetic","adj.","completely sealed; relating to alchemy"),
("hierarchy","n.","a system of ranking according to authority"),
("hinder","v.","to create difficulties that delay or prevent"),
("hoary","adj.","old and trite; gray-haired with age"),
("hubris","n.","excessive pride or self-confidence"),
("humility","n.","a modest view of one's own importance"),
# I
("iconoclast","n.","a person who attacks cherished beliefs"),
("idiosyncrasy","n.","a distinctive personal peculiarity"),
("idyllic","adj.","extremely happy, peaceful, and picturesque"),
("ignominious","adj.","deserving or causing public disgrace"),
("illicit","adj.","forbidden by law, rules, or custom"),
("illustrious","adj.","well known and admired for achievements"),
("imbue","v.","to inspire or permeate with a feeling or quality"),
("imminent","adj.","about to happen"),
("immutable","adj.","unchanging over time; permanent"),
("impair","v.","to weaken or damage"),
("impartial","adj.","treating all rivals or disputants equally; fair"),
("impasse","n.","a situation in which no progress is possible"),
("impeach","v.","to charge a public official with misconduct"),
("impeccable","adj.","without any faults or errors"),
("impede","v.","to delay or prevent by obstructing"),
("imperative","adj.","of vital importance; crucial"),
("imperceptible","adj.","so slight as to be almost impossible to detect"),
("imperious","adj.","assuming power without justification; domineering"),
("impervious","adj.","unable to be affected or penetrated"),
("impetuous","adj.","acting quickly without thought or care"),
("implicit","adj.","implied though not directly expressed"),
("implore","v.","to beg someone earnestly or desperately"),
("imply","v.","to suggest without being explicitly stated"),
("improvident","adj.","not having foresight; wasteful"),
("impudent","adj.","showing a lack of respect; impertinent"),
("impugn","v.","to dispute the truth or honesty of"),
("impunity","n.","exemption from punishment or consequences"),
("inadvertent","adj.","unintentional; not deliberately planned"),
("incandescent","adj.","emitting light as a result of being heated; brilliant"),
("incensed","adj.","very angry; enraged"),
("inception","n.","the establishment or starting point"),
("incessant","adj.","continuing without pause or interruption"),
("incipient","adj.","beginning to develop or appear"),
("incisive","adj.","intelligently analytical and clear-thinking"),
("incite","v.","to encourage or stir up violent or unlawful behavior"),
("inclusive","adj.","including all; not excluding any"),
("inconclusive","adj.","not leading to a firm conclusion"),
("increment","n.","a regular increase in amount"),
("incriminate","v.","to make someone appear guilty of wrongdoing"),
("incumbent","adj.","necessary for someone as a duty; n. current holder"),
("indigent","adj.","poor; needy"),
("indignant","adj.","feeling anger at perceived unfair treatment"),
("indiscriminate","adj.","done at random without careful judgment"),
("indolent","adj.","wanting to avoid activity or exertion; lazy"),
("indomitable","adj.","impossible to subdue or defeat"),
("induce","v.","to succeed in persuading; to bring about"),
("ineffable","adj.","too great or extreme to be expressed in words"),
("inept","adj.","having or showing no skill; clumsy"),
("inert","adj.","lacking the ability or strength to move"),
("infallible","adj.","incapable of making mistakes"),
("infamous","adj.","well known for some bad quality or deed"),
("infer","v.","to deduce from evidence or reasoning"),
("inflammable","adj.","easily set on fire; easily angered"),
("influx","n.","an arrival of large numbers of people or things"),
("infringe","v.","to actively break the terms of a law or agreement"),
("ingenious","adj.","clever, original, and inventive"),
("ingenuous","adj.","innocent and unsuspecting"),
("inhibit","v.","to hinder or restrain an action or process"),
("innate","adj.","inborn; natural"),
("innocuous","adj.","not harmful or offensive"),
("innovative","adj.","featuring new methods; advanced and original"),
("innuendo","n.","an indirect or subtle reference, usually negative"),
("insatiable","adj.","impossible to satisfy"),
("inscrutable","adj.","impossible to understand or interpret"),
("insidious","adj.","proceeding in a harmful way that is not apparent"),
("insinuate","v.","to suggest in an indirect and unpleasant way"),
("insipid","adj.","lacking flavor; dull and uninteresting"),
("insolent","adj.","showing a rude lack of respect"),
("instigate","v.","to bring about or initiate"),
("insurgent","n.","a rebel or revolutionary"),
("integral","adj.","necessary to make a whole complete; essential"),
("intermittent","adj.","occurring at irregular intervals"),
("intransigent","adj.","unwilling to change one's views; stubborn"),
("intrinsic","adj.","belonging naturally; essential"),
("inundate","v.","to overwhelm with things to be dealt with"),
("invalidate","v.","to make an argument or claim unsound"),
("invective","n.","insulting or abusive language"),
("invoke","v.","to call on for assistance; to cite as authority"),
("irate","adj.","feeling or showing extreme anger"),
("ironic","adj.","happening in the opposite way to what is expected"),
("irrefutable","adj.","impossible to deny or disprove"),
("irreverent","adj.","showing a lack of respect for serious matters"),
("itinerant","adj.","traveling from place to place"),
# J-K
("jeopardize","v.","to put at risk of being lost or harmed"),
("judicious","adj.","having or showing good judgment"),
("kindle","v.","to light a fire; to arouse an emotion"),
# L
("lackluster","adj.","lacking in vitality, force, or conviction"),
("laconic","adj.","using very few words"),
("lament","v.","to express passionate grief about"),
("lampoon","v.","to publicly criticize using ridicule"),
("languid","adj.","displaying a disinclination for physical exertion"),
("lapse","n.","a temporary failure; a passage of time"),
("latent","adj.","existing but not yet developed or manifest"),
("laudable","adj.","deserving praise and commendation"),
("legacy","n.","something left by a predecessor; an inheritance"),
("lethargy","n.","a lack of energy and enthusiasm"),
("levity","n.","humor or lack of seriousness in serious matters"),
("liaison","n.","communication or cooperation between groups"),
("listless","adj.","lacking energy or enthusiasm"),
("litigious","adj.","tending to engage in lawsuits"),
("lofty","adj.","of imposing height; noble in character"),
("lucid","adj.","expressed clearly; easy to understand"),
("ludicrous","adj.","so foolish or unreasonable as to be amusing"),
("luminous","adj.","full of or shedding light; brilliant"),
("lure","v.","to tempt with a promise of reward"),
# M
("magnanimous","adj.","very generous or forgiving"),
("maladroit","adj.","ineffective or bungling; clumsy"),
("malaise","n.","a general feeling of discomfort or unease"),
("malfeasance","n.","wrongdoing by a public official"),
("malign","v.","to speak about in a spitefully critical manner"),
("malleable","adj.","easily influenced or shaped"),
("mandate","n.","an official order or commission to do something"),
("manifest","adj.","clear or obvious; v. to display or show"),
("maverick","n.","an independent-minded person"),
("meager","adj.","lacking in quantity or quality; inadequate"),
("mediate","v.","to intervene in a dispute to bring agreement"),
("menial","adj.","not requiring much skill; servile"),
("mercenary","adj.","primarily concerned with making money"),
("mercurial","adj.","subject to sudden changes of mood"),
("meticulous","adj.","showing great attention to detail"),
("mitigate","v.","to make less severe or serious"),
("modicum","n.","a small quantity of something"),
("mollify","v.","to calm or soothe someone's anger"),
("momentous","adj.","of great importance or significance"),
("monotonous","adj.","dull and tedious due to lack of variety"),
("moratorium","n.","a temporary prohibition of an activity"),
("morose","adj.","sullen and ill-tempered"),
("mundane","adj.","lacking interest or excitement; dull"),
("munificent","adj.","very generous; lavish"),
("myriad","n.","a countless or extremely great number"),
# N
("naive","adj.","showing lack of experience or wisdom"),
("nascent","adj.","just beginning to develop"),
("nebulous","adj.","vague or ill-defined"),
("nefarious","adj.","wicked or criminal"),
("negligible","adj.","so small or unimportant as to be not worth considering"),
("nettle","v.","to irritate or annoy"),
("nimble","adj.","quick and light in movement; agile"),
("nocturnal","adj.","done or active during the night"),
("nominal","adj.","existing in name only; very small"),
("nonchalant","adj.","feeling calm and relaxed; casually unconcerned"),
("nostalgia","n.","a sentimental longing for the past"),
("notorious","adj.","famous for something bad"),
("novelty","n.","the quality of being new or unusual"),
("nuance","n.","a subtle difference in meaning or expression"),
("nullify","v.","to make legally void; to cancel out"),
# O
("obdurate","adj.","stubbornly refusing to change"),
("objective","adj.","not influenced by personal feelings; impartial"),
("obligatory","adj.","required by law, rule, or custom"),
("oblique","adj.","not direct; slanting"),
("obscure","adj.","not discovered or known about; unclear"),
("obsolete","adj.","no longer produced or used; outdated"),
("obstinate","adj.","stubbornly refusing to change opinion"),
("obtuse","adj.","annoyingly slow to understand"),
("ominous","adj.","giving the impression that something bad will happen"),
("omnipotent","adj.","having unlimited power"),
("onerous","adj.","involving a great deal of effort or difficulty"),
("opaque","adj.","not able to be seen through; hard to understand"),
("opportunist","n.","one who exploits circumstances for personal gain"),
("optimal","adj.","best or most favorable"),
("opulent","adj.","ostentatiously rich and luxurious"),
("orchestrate","v.","to arrange or direct elements for a desired effect"),
("orthodox","adj.","conforming to traditional beliefs or practices"),
("oscillate","v.","to move back and forth at a regular speed"),
("ostensible","adj.","stated or appearing to be true, but not necessarily"),
("ostentatious","adj.","designed to impress; showy"),
("oust","v.","to drive out or expel from a position"),
("overt","adj.","done openly; not secret"),
# P
("pact","n.","a formal agreement between individuals or parties"),
("palatable","adj.","pleasant to taste; acceptable"),
("palliate","v.","to make less severe without removing the cause"),
("palpable","adj.","able to be touched or felt; obvious"),
("panacea","n.","a solution for all problems or diseases"),
("paradigm","n.","a typical example or model"),
("paradox","n.","a seemingly contradictory statement that may be true"),
("paramount","adj.","more important than anything else; supreme"),
("pariah","n.","an outcast; a person despised by others"),
("parody","n.","an imitation for comic effect"),
("parsimonious","adj.","excessively unwilling to spend money"),
("partisan","adj.","prejudiced in favor of a particular cause"),
("pathology","n.","the study of the causes and effects of diseases"),
("patronize","v.","to treat condescendingly; to be a customer of"),
("paucity","n.","the presence of something in very small quantities"),
("pedantic","adj.","excessively concerned with minor details or rules"),
("penchant","n.","a strong habitual liking for something"),
("penitent","adj.","feeling or showing sorrow for wrongdoing"),
("perennial","adj.","lasting for an indefinitely long time"),
("perfunctory","adj.","carried out with minimum effort"),
("perilous","adj.","full of danger or risk"),
("permeate","v.","to spread throughout"),
("pernicious","adj.","having a harmful effect in a gradual way"),
("perpetuate","v.","to make something continue indefinitely"),
("perplexing","adj.","completely baffling or puzzling"),
("persevere","v.","to continue despite difficulty or discouragement"),
("pertinent","adj.","relevant or applicable to the matter at hand"),
("pervasive","adj.","spreading widely throughout an area"),
("petition","n.","a formal written request signed by many people"),
("petulant","adj.","childishly sulky or bad-tempered"),
("philanthropist","n.","a person who seeks to promote the welfare of others"),
("pious","adj.","devoutly religious"),
("pivotal","adj.","of crucial importance"),
("placate","v.","to make less angry or hostile; to appease"),
("placid","adj.","not easily upset or excited; calm"),
("plaintiff","n.","a person who brings a case against another in court"),
("platitude","n.","a remark used too often to be meaningful"),
("plausible","adj.","seeming reasonable or probable"),
("plethora","n.","an excess of something"),
("plight","n.","a dangerous or difficult situation"),
("poignant","adj.","evoking a keen sense of sadness or regret"),
("polarize","v.","to divide into sharply opposing groups"),
("ponderous","adj.","slow and clumsy; dull"),
("portend","v.","to be a sign or warning of something future"),
("postulate","v.","to assume as a basis for reasoning"),
("potent","adj.","having great power, influence, or effect"),
("pragmatic","adj.","dealing with things practically rather than ideally"),
("precept","n.","a general rule intended to guide behavior"),
("precipitate","v.","to cause something to happen suddenly"),
("preclude","v.","to prevent from happening; to make impossible"),
("precocious","adj.","having developed abilities at an unusually early age"),
("predecessor","n.","a person who held a position before the current holder"),
("predilection","n.","a preference or special liking"),
("predominant","adj.","present as the strongest element"),
("preeminent","adj.","surpassing all others; outstanding"),
("premise","n.","a statement assumed to be true for reasoning"),
("premonition","n.","a strong feeling that something will happen"),
("prerogative","n.","an exclusive right or privilege"),
("prevalent","adj.","widespread in a particular area or time"),
("pristine","adj.","in its original condition; unspoiled"),
("probity","n.","the quality of having strong moral principles"),
("proclivity","n.","a tendency to choose a particular thing"),
("procure","v.","to obtain something with care or effort"),
("prodigal","adj.","spending money freely and recklessly"),
("prodigious","adj.","remarkably great in extent or degree"),
("profane","adj.","relating to the ordinary; showing disrespect for religion"),
("proficient","adj.","competent or skilled at doing something"),
("profuse","adj.","abundant; excessively plentiful"),
("prohibitive","adj.","excessively high so as to prevent purchase"),
("prominence","n.","the state of being important or well-known"),
("promulgate","v.","to make widely known; to put into effect"),
("propagate","v.","to spread and promote widely"),
("propensity","n.","an inclination or natural tendency"),
("prophetic","adj.","accurately predicting the future"),
("proponent","n.","a person who advocates for something"),
("propriety","n.","conformity to accepted standards of behavior"),
("prosaic","adj.","lacking imagination; dull and ordinary"),
("proscribe","v.","to forbid or condemn"),
("prospective","adj.","expected or expecting to be something in the future"),
("protagonist","n.","the leading character in a story or cause"),
("protracted","adj.","lasting for a long time; prolonged"),
("provident","adj.","making provision for future needs; prudent"),
("provincial","adj.","relating to a province; unsophisticated"),
("proviso","n.","a condition attached to an agreement"),
("prowess","n.","great skill or bravery"),
("prudent","adj.","acting with care and thought for the future"),
("pugnacious","adj.","eager or quick to argue or fight"),
("punctilious","adj.","showing great attention to detail or correct behavior"),
("punitive","adj.","inflicting or intended as punishment"),
("purport","v.","to appear or claim to be"),
# Q-R
("qualm","n.","an uneasy feeling of doubt or worry"),
("quandary","n.","a state of perplexity or uncertainty"),
("quarantine","n.","a period of isolation to prevent disease spread"),
("querulous","adj.","complaining in a whiny manner"),
("quorum","n.","the minimum number of members needed for proceedings"),
("ramification","n.","a consequence of an action, especially unwelcome"),
("rampant","adj.","flourishing in an uncontrolled way"),
("rancor","n.","bitterness or resentfulness"),
("ratify","v.","to sign or give formal consent to"),
("raucous","adj.","making a loud and harsh noise"),
("rebuff","v.","to reject or refuse in an abrupt manner"),
("rebuke","v.","to express sharp disapproval or criticism"),
("recalcitrant","adj.","having an obstinate unwillingness to obey"),
("recant","v.","to withdraw a former opinion publicly"),
("reciprocal","adj.","given, felt, or done in return"),
("recluse","n.","a person who lives a solitary life"),
("reconcile","v.","to restore friendly relations; to make compatible"),
("rectify","v.","to put right; to correct"),
("redress","n.","remedy or compensation for a wrong"),
("redundant","adj.","not needed; unnecessarily repetitive"),
("refute","v.","to prove a statement or theory to be wrong"),
("regal","adj.","resembling or fit for a monarch; impressive"),
("reimburse","v.","to repay money spent"),
("relegate","v.","to assign to a lower position or place"),
("relinquish","v.","to voluntarily give up a right or possession"),
("remedial","adj.","intended as a cure or correction"),
("remorse","n.","deep regret or guilt for a wrongdoing"),
("render","v.","to cause to be or become; to provide"),
("renounce","v.","to formally declare one's abandonment of"),
("repeal","v.","to revoke or annul a law or act"),
("repercussion","n.","an unintended consequence of an action"),
("replenish","v.","to fill or build up again"),
("reprehensible","adj.","deserving of condemnation"),
("repress","v.","to subdue or restrain by force"),
("reprimand","n.","a formal expression of disapproval"),
("reproach","v.","to express disapproval or disappointment"),
("repudiate","v.","to refuse to accept or be associated with"),
("reputable","adj.","having a good reputation"),
("requisite","adj.","made necessary by particular circumstances"),
("rescind","v.","to revoke or cancel a law or agreement"),
("resilient","adj.","able to recover quickly from difficulties"),
("resolute","adj.","admirably purposeful and determined"),
("resonate","v.","to evoke feelings or associations"),
("restitution","n.","the restoration of something to its rightful owner"),
("retract","v.","to withdraw a statement or accusation"),
("reverberate","v.","to be repeated as an echo; to have continuing effects"),
("revere","v.","to feel deep respect or admiration for"),
("rhetoric","n.","the art of persuasive speaking or writing"),
("rigorous","adj.","extremely thorough and careful"),
("robust","adj.","strong and healthy; vigorous"),
("rudimentary","adj.","involving or limited to basic principles"),
("rustic","adj.","relating to the countryside; simple and charming"),
# S
("sacrosanct","adj.","regarded as too important to be interfered with"),
("salient","adj.","most noticeable or important"),
("sanction","n.","a penalty for disobeying; official permission"),
("sardonic","adj.","grimly mocking or cynical"),
("satiate","v.","to satisfy fully"),
("scant","adj.","barely sufficient or adequate"),
("scathing","adj.","witheringly critical; harshly severe"),
("schism","n.","a split or division between groups"),
("scrutiny","n.","critical observation or examination"),
("secular","adj.","not connected with religious matters"),
("sentiment","n.","a view or attitude held toward something"),
("sequester","v.","to isolate or hide away"),
("serendipity","n.","the occurrence of fortunate events by chance"),
("servile","adj.","having an excessive willingness to serve or please"),
("shrewd","adj.","having sharp powers of judgment; astute"),
("skeptical","adj.","not easily convinced; having doubts"),
("slander","n.","false spoken statements damaging reputation"),
("solemn","adj.","formal and dignified; deeply sincere"),
("solicit","v.","to ask for or try to obtain"),
("solitary","adj.","done or existing alone"),
("somber","adj.","dark or dull; oppressively serious"),
("sordid","adj.","involving ignoble actions; morally degrading"),
("sovereign","adj.","possessing supreme authority"),
("speculate","v.","to form a theory without firm evidence"),
("sporadic","adj.","occurring at irregular intervals"),
("spurious","adj.","not genuine; false or fake"),
("squander","v.","to waste recklessly"),
("stagnant","adj.","showing no activity or development"),
("staunch","adj.","very loyal and committed"),
("steadfast","adj.","resolutely firm and unwavering"),
("stigma","n.","a mark of disgrace associated with something"),
("stipulate","v.","to demand or specify as part of an agreement"),
("stoic","adj.","enduring pain without showing feelings"),
("stringent","adj.","strict, precise, and exacting"),
("subordinate","adj.","lower in rank or position"),
("subservient","adj.","prepared to obey others unquestioningly"),
("substantive","adj.","having a firm basis in reality; important"),
("subvert","v.","to undermine the power of an established system"),
("succinct","adj.","briefly and clearly expressed"),
("suffice","v.","to be enough or adequate"),
("superficial","adj.","existing or occurring at the surface; shallow"),
("superfluous","adj.","unnecessary; more than enough"),
("supplant","v.","to take the place of"),
("supposition","n.","an uncertain belief; an assumption"),
("surfeit","n.","an excessive amount of something"),
("surmise","v.","to suppose without sufficient evidence"),
("surpass","v.","to exceed or be greater than"),
("surreptitious","adj.","kept secret because disapproval is expected"),
("susceptible","adj.","likely to be influenced or harmed"),
("sustenance","n.","food and drink regarded as nourishment"),
("sycophant","n.","a person who flatters someone important for gain"),
# T
("tacit","adj.","understood without being stated"),
("tangential","adj.","only slightly relevant; diverging from a subject"),
("tangible","adj.","clear and definite; able to be touched"),
("tantamount","adj.","equivalent in seriousness or effect"),
("tedious","adj.","too long, slow, or dull"),
("temerity","n.","excessive confidence or boldness; audacity"),
("temperate","adj.","showing moderation or self-restraint"),
("temporal","adj.","relating to worldly affairs; relating to time"),
("tenable","adj.","able to be maintained or defended"),
("tenuous","adj.","very weak or slight"),
("terminate","v.","to bring to an end"),
("thesis","n.","a statement to be proved; an academic paper"),
("thwart","v.","to prevent from accomplishing a purpose"),
("tirade","n.","a long, angry speech of criticism"),
("torpid","adj.","mentally or physically inactive; sluggish"),
("tout","v.","to promote or publicize enthusiastically"),
("tractable","adj.","easy to control or influence"),
("transcend","v.","to surpass or go beyond the limits of"),
("transient","adj.","lasting only for a short time"),
("trepidation","n.","a feeling of fear about something that may happen"),
("trite","adj.","lacking originality from overuse"),
("trivial","adj.","of very little importance or value"),
("truncate","v.","to shorten by cutting off the top or end"),
("tumultuous","adj.","making a loud, confused noise; disorderly"),
("turbulent","adj.","characterized by conflict or disorder"),
("turmoil","n.","a state of great disturbance or confusion"),
("tycoon","n.","a wealthy and influential business person"),
("tyranny","n.","cruel and oppressive rule or government"),
# U
("ubiquitous","adj.","present everywhere at the same time"),
("ulterior","adj.","existing beyond what is obvious; hidden"),
("ultimatum","n.","a final demand with a threat of consequences"),
("umbrage","n.","offense or annoyance"),
("unassuming","adj.","not pretentious or arrogant; modest"),
("undercut","v.","to offer goods at a lower price; to weaken"),
("underscore","v.","to emphasize or call special attention to"),
("unequivocal","adj.","leaving no doubt; unambiguous"),
("unilateral","adj.","performed by or affecting only one side"),
("unkempt","adj.","having an untidy or disheveled appearance"),
("unorthodox","adj.","contrary to what is usual or traditional"),
("unpalatable","adj.","not pleasant to taste; difficult to accept"),
("unprecedented","adj.","never done or known before"),
("unscrupulous","adj.","having no moral principles; dishonest"),
("untenable","adj.","not able to be maintained or defended"),
("unwieldy","adj.","difficult to handle because of size or complexity"),
("upbraid","v.","to find fault with someone severely"),
("usurp","v.","to seize power or position illegally"),
("utilitarian","adj.","designed to be useful rather than attractive"),
# V
("vacillate","v.","to waver between different opinions or actions"),
("validate","v.","to check or prove the accuracy of"),
("valor","n.","great courage in the face of danger"),
("vanquish","v.","to defeat thoroughly"),
("vehement","adj.","showing strong feeling; passionate"),
("venerate","v.","to regard with great respect"),
("veracious","adj.","speaking or representing the truth"),
("verbose","adj.","using more words than needed"),
("verdict","n.","a decision or judgment made after deliberation"),
("versatile","adj.","able to adapt to many different functions"),
("vex","v.","to make someone feel annoyed or frustrated"),
("viable","adj.","capable of working successfully; feasible"),
("vigilant","adj.","keeping careful watch for danger"),
("vindicate","v.","to clear of blame or suspicion"),
("vindictive","adj.","having a strong desire for revenge"),
("virtuoso","n.","a person highly skilled in music or another art"),
("visceral","adj.","relating to deep inward feelings rather than intellect"),
("vitriolic","adj.","filled with bitter criticism or malice"),
("vivacious","adj.","attractively lively and animated"),
("vocation","n.","a strong feeling of suitability for a career"),
("vociferous","adj.","vehement or clamorous in expressing views"),
("volition","n.","the faculty of using one's will"),
("voracious","adj.","wanting or devouring great quantities"),
("vulnerable","adj.","susceptible to physical or emotional harm"),
# W-Z
("wane","v.","to decrease gradually in strength or importance"),
("warrant","v.","to justify or make necessary"),
("whimsical","adj.","playfully quaint or fanciful"),
("wistful","adj.","having a feeling of vague or regretful longing"),
("wrath","n.","extreme anger"),
("xenophobia","n.","dislike or prejudice against foreign peoples"),
("yeoman","n.","a person who does loyal, diligent work"),
("zealot","n.","a person who is fanatically committed to a cause"),
]

# Read existing words
with open('words.js') as f:
    content = f.read()
import re
existing = set(re.findall(r'w:"([^"]*)"', content))
print(f"Existing words: {len(existing)}")

# Filter out duplicates
new_words = [(w,p,d) for w,p,d in WORDS if w not in existing]
print(f"New unique words to add: {len(new_words)}")

# Assign difficulty using wordfreq
results = []
for w, pos, defn in new_words:
    z = zipf_frequency(w, 'en')
    if z >= 4.0:
        diff = 'easy'
    elif z >= 3.0:
        diff = 'medium'
    else:
        diff = 'hard'
    results.append((w, pos, defn, diff, z))

# Stats
easy = sum(1 for _,_,_,d,_ in results if d=='easy')
med = sum(1 for _,_,_,d,_ in results if d=='medium')
hard = sum(1 for _,_,_,d,_ in results if d=='hard')
print(f"Difficulty distribution: easy={easy}, medium={med}, hard={hard}")

# Generate words.js entries
entries = []
for w, pos, defn, diff, z in results:
    entries.append('{w:"'+w+'",p:"'+pos+'",d:"'+defn+'",diff:"'+diff+'"}')

# Append to words.js
# Find the closing ];
close_idx = content.rstrip().rfind('];')
new_content = content[:close_idx] + ',\n' + ',\n'.join(entries) + '\n];\n'

with open('words.js', 'w') as f:
    f.write(new_content)

print(f"\nSuccessfully added {len(results)} new words to words.js")
print(f"Total words now: {len(existing) + len(results)}")
