const W=[
{w:"abase",p:"v.",d:"to humiliate, degrade"},
{w:"abate",p:"v.",d:"to reduce, lessen"},
{w:"abdicate",p:"v.",d:"to give up a position, usually leadership"},
{w:"abduct",p:"v.",d:"to kidnap, take by force"},
{w:"aberration",p:"n.",d:"something that differs from the norm"},
{w:"abet",p:"v.",d:"to aid, help, encourage"},
{w:"abhor",p:"v.",d:"to hate, detest"},
{w:"abide",p:"v.",d:"to put up with; to remain"},
{w:"abject",p:"adj.",d:"wretched, pitiful"},
{w:"abjure",p:"v.",d:"to reject, renounce"},
{w:"abnegation",p:"n.",d:"denial of comfort to oneself"},
{w:"abort",p:"v.",d:"to give up on a half-finished project"},
{w:"abridge",p:"v.",d:"to cut down, shorten"},
{w:"abrogate",p:"v.",d:"to abolish, usually by authority"},
{w:"abscond",p:"v.",d:"to sneak away and hide"},
{w:"absolution",p:"n.",d:"freedom from blame, guilt, or sin"},
{w:"abstain",p:"v.",d:"to freely choose not to commit an action"},
{w:"abstruse",p:"adj.",d:"hard to comprehend"},
{w:"accede",p:"v.",d:"to agree"},
{w:"accentuate",p:"v.",d:"to stress, highlight"},
{w:"accessible",p:"adj.",d:"obtainable, reachable"},
{w:"acclaim",p:"n.",d:"high praise"},
{w:"accolade",p:"n.",d:"high praise, special distinction"},
{w:"accommodating",p:"adj.",d:"helpful, obliging, polite"},
{w:"accord",p:"n.",d:"an agreement"},
{w:"accost",p:"v.",d:"to confront verbally"},
{w:"accretion",p:"n.",d:"slow growth in size or amount"},
{w:"acerbic",p:"adj.",d:"biting, bitter in tone or taste"},
{w:"acquiesce",p:"v.",d:"to agree without protesting"},
{w:"acrimony",p:"n.",d:"bitterness, discord"},
{w:"acumen",p:"n.",d:"keen insight"},
{w:"acute",p:"adj.",d:"sharp or severe; having keen insight"},
{w:"adamant",p:"adj.",d:"impervious, unyielding"},
{w:"adept",p:"adj.",d:"extremely skilled"},
{w:"adhere",p:"v.",d:"to stick to; to follow devoutly"},
{w:"admonish",p:"v.",d:"to caution, criticize, reprove"},
{w:"adorn",p:"v.",d:"to decorate"},
{w:"adroit",p:"adj.",d:"skillful, dexterous"},
{w:"adulation",p:"n.",d:"extreme praise"},
{w:"adumbrate",p:"v.",d:"to sketch out vaguely"},
{w:"adverse",p:"adj.",d:"antagonistic, unfavorable, dangerous"},
{w:"advocate",p:"v.",d:"to argue for; a person who argues for"},
{w:"aerial",p:"adj.",d:"related to the air"},
{w:"aesthetic",p:"adj.",d:"artistic, related to beauty"},
{w:"affable",p:"adj.",d:"friendly, amiable"},
{w:"affinity",p:"n.",d:"a spontaneous feeling of closeness"},
{w:"affluent",p:"adj.",d:"rich, wealthy"},
{w:"affront",p:"n.",d:"an insult"},
{w:"aggrandize",p:"v.",d:"to increase or make greater"},
{w:"aggregate",p:"n.",d:"a whole or total; to gather into a mass"},
{w:"aggrieved",p:"adj.",d:"distressed, wronged"},
{w:"agile",p:"adj.",d:"quick, nimble"},
{w:"agnostic",p:"adj.",d:"believing God's existence cannot be proven"},
{w:"agriculture",p:"n.",d:"farming"},
{w:"aisle",p:"n.",d:"a passageway between rows"},
{w:"alacrity",p:"n.",d:"eagerness, speed"},
{w:"alias",p:"n.",d:"a false name or identity"},
{w:"allay",p:"v.",d:"to soothe, ease"},
{w:"allege",p:"v.",d:"to assert, usually without proof"},
{w:"alleviate",p:"v.",d:"to relieve, make bearable"},
{w:"allocate",p:"v.",d:"to distribute, set aside"},
{w:"aloof",p:"adj.",d:"reserved, distant"},
{w:"altercation",p:"n.",d:"a dispute, fight"},
{w:"altruistic",p:"adj.",d:"showing selfless concern for others"},
{w:"amalgamate",p:"v.",d:"to bring together, unite"},
{w:"ambiguous",p:"adj.",d:"uncertain, variably interpretable"},
{w:"ambivalent",p:"adj.",d:"having opposing feelings"},
{w:"ameliorate",p:"v.",d:"to improve"},
{w:"amenable",p:"adj.",d:"willing, compliant"},
{w:"amenity",p:"n.",d:"an item that increases comfort"},
{w:"amiable",p:"adj.",d:"friendly"},
{w:"amicable",p:"adj.",d:"friendly, often regarding agreements"},
{w:"amorous",p:"adj.",d:"showing love"},
{w:"amorphous",p:"adj.",d:"without definite shape or type"},
{w:"anachronistic",p:"adj.",d:"out of correct chronological order"},
{w:"analgesic",p:"n.",d:"something that reduces pain"},
{w:"analogous",p:"adj.",d:"similar to"},
{w:"anarchist",p:"n.",d:"one who wants to eliminate all government"},
{w:"anathema",p:"n.",d:"a cursed, detested person"},
{w:"anecdote",p:"n.",d:"a short, humorous account"},
{w:"anesthesia",p:"n.",d:"loss of sensation"},
{w:"anguish",p:"n.",d:"extreme sadness, torment"},
{w:"animated",p:"adj.",d:"lively"},
{w:"annex",p:"v.",d:"to incorporate territory"},
{w:"annul",p:"v.",d:"to make void or invalid"},
{w:"anomaly",p:"n.",d:"something that doesn't fit the normal order"},
{w:"anonymous",p:"adj.",d:"unknown, unrecognized"},
{w:"antagonism",p:"n.",d:"hostility"},
{w:"antecedent",p:"n.",d:"something that came before"},
{w:"antediluvian",p:"adj.",d:"ancient"},
{w:"anthology",p:"n.",d:"a selected collection of writings"},
{w:"antipathy",p:"n.",d:"a strong dislike, repugnance"},
{w:"antiquated",p:"adj.",d:"old, out of date"},
{w:"antiseptic",p:"adj.",d:"clean, sterile"},
{w:"antithesis",p:"n.",d:"the absolute opposite"},
{w:"anxiety",p:"n.",d:"intense uneasiness"},
{w:"apathetic",p:"adj.",d:"lacking concern or emotion"},
{w:"apocryphal",p:"adj.",d:"fictitious, false"},
{w:"appalling",p:"adj.",d:"inspiring shock, horror, or disgust"},
{w:"appease",p:"v.",d:"to calm, satisfy"},
{w:"appraise",p:"v.",d:"to assess worth or value"},
{w:"apprehend",p:"v.",d:"to seize or arrest; to perceive or understand"},
{w:"approbation",p:"n.",d:"praise"},
{w:"appropriate",p:"v.",d:"to take, make use of"},
{w:"aquatic",p:"adj.",d:"relating to water"},
{w:"arable",p:"adj.",d:"suitable for growing crops"},
{w:"arbiter",p:"n.",d:"one who resolves a dispute"},
{w:"arbitrary",p:"adj.",d:"based on random factors"},
{w:"arbitration",p:"n.",d:"process of resolving a dispute"},
{w:"arboreal",p:"adj.",d:"relating to trees"},
{w:"arcane",p:"adj.",d:"obscure, secret, known by few"},
{w:"archaic",p:"adj.",d:"outdated, from an earlier period"},
{w:"archetypal",p:"adj.",d:"the most representative example"},
{w:"ardor",p:"n.",d:"extreme vigor or enthusiasm"},
{w:"arid",p:"adj.",d:"excessively dry"},
{w:"arrogate",p:"v.",d:"to take without justification"},
{w:"artifact",p:"n.",d:"a remaining piece from an extinct culture"},
{w:"artisan",p:"n.",d:"a craftsman"},
{w:"ascertain",p:"v.",d:"to perceive, learn"},
{w:"ascetic",p:"adj.",d:"practicing restraint or self-discipline"},
{w:"ascribe",p:"v.",d:"to assign, credit, attribute"},
{w:"aspersion",p:"n.",d:"a curse, expression of ill-will"},
{w:"aspire",p:"v.",d:"to long for, aim toward"},
{w:"assail",p:"v.",d:"to attack"},
{w:"assess",p:"v.",d:"to evaluate"},
{w:"assiduous",p:"adj.",d:"hard-working, diligent"},
{w:"assuage",p:"v.",d:"to ease, pacify"},
{w:"astute",p:"adj.",d:"very clever, crafty"},
{w:"asylum",p:"n.",d:"a place of refuge"},
{w:"atone",p:"v.",d:"to repent, make amends"},
{w:"atrophy",p:"v.",d:"to wither away, decay"},
{w:"attain",p:"v.",d:"to achieve, arrive at"},
{w:"attribute",p:"v.",d:"to credit or assign; a facet or trait"},
{w:"atypical",p:"adj.",d:"not typical, unusual"},
{w:"audacious",p:"adj.",d:"excessively bold"},
{w:"audible",p:"adj.",d:"able to be heard"},
{w:"augment",p:"v.",d:"to add to, expand"},
{w:"auspicious",p:"adj.",d:"favorable, indicative of good things"},
{w:"austere",p:"adj.",d:"very bare, bleak"},
{w:"avarice",p:"n.",d:"excessive greed"},
{w:"avenge",p:"v.",d:"to seek revenge"},
{w:"aversion",p:"n.",d:"a particular dislike"},
{w:"balk",p:"v.",d:"to stop, block abruptly"},
{w:"ballad",p:"n.",d:"a love song"},
{w:"banal",p:"adj.",d:"dull, commonplace"},
{w:"bane",p:"n.",d:"a burden"},
{w:"bard",p:"n.",d:"a poet or singer"},
{w:"bashful",p:"adj.",d:"shy, excessively timid"},
{w:"battery",p:"n.",d:"a power device; assault or beating"},
{w:"beguile",p:"v.",d:"to trick, deceive"},
{w:"behemoth",p:"n.",d:"something of tremendous power or size"},
{w:"benevolent",p:"adj.",d:"marked by goodness"},
{w:"benign",p:"adj.",d:"favorable, not threatening, mild"},
{w:"bequeath",p:"v.",d:"to pass on, give"},
{w:"berate",p:"v.",d:"to scold vehemently"},
{w:"bereft",p:"adj.",d:"devoid of, without"},
{w:"beseech",p:"v.",d:"to beg, plead"},
{w:"bias",p:"n.",d:"a tendency, prejudice"},
{w:"bilk",p:"v.",d:"to cheat, defraud"},
{w:"blandish",p:"v.",d:"to coax using flattery"},
{w:"blemish",p:"n.",d:"an imperfection, flaw"},
{w:"blight",p:"n.",d:"a plague or disease; something destroying hope"},
{w:"boisterous",p:"adj.",d:"loud, full of energy"},
{w:"bombastic",p:"adj.",d:"excessively confident, pompous"},
{w:"boon",p:"n.",d:"a gift or blessing"},
{w:"bourgeois",p:"n.",d:"a middle-class person or capitalist"},
{w:"brazen",p:"adj.",d:"excessively bold, brash"},
{w:"brusque",p:"adj.",d:"short, abrupt, dismissive"},
{w:"buffet",p:"v.",d:"to strike with force"},
{w:"burnish",p:"v.",d:"to polish, shine"},
{w:"buttress",p:"v.",d:"to support; something offering support"},
{w:"cacophonous",p:"adj.",d:"having a harsh, discordant mixture of sounds"},
{w:"cacophony",p:"n.",d:"tremendous noise, disharmonious sound"},
{w:"cadence",p:"n.",d:"a rhythm, progression of sound"},
{w:"cajole",p:"v.",d:"to urge, coax"},
{w:"calamity",p:"n.",d:"an event with disastrous consequences"},
{w:"calibrate",p:"v.",d:"to set, standardize"},
{w:"callous",p:"adj.",d:"harsh, cold, unfeeling"},
{w:"calumny",p:"n.",d:"spreading lies to spoil reputation"},
{w:"camaraderie",p:"n.",d:"brotherhood, jovial unity"},
{w:"candor",p:"n.",d:"honesty, frankness"},
{w:"canny",p:"adj.",d:"shrewd, careful"},
{w:"canvas",p:"n.",d:"cloth for painting; to cover or inspect"},
{w:"capacious",p:"adj.",d:"very spacious"},
{w:"capitulate",p:"v.",d:"to surrender"},
{w:"capricious",p:"adj.",d:"subject to whim, fickle"},
{w:"captivate",p:"v.",d:"to hold attention"},
{w:"carouse",p:"v.",d:"to party, celebrate"},
{w:"carp",p:"v.",d:"to annoy, pester"},
{w:"catalog",p:"v.",d:"to list; a list or collection"},
{w:"catalyze",p:"v.",d:"to charge, inspire"},
{w:"caucus",p:"n.",d:"a meeting for a common goal"},
{w:"caustic",p:"adj.",d:"bitter, biting, acidic"},
{w:"cavort",p:"v.",d:"to leap about, behave boisterously"},
{w:"censure",p:"n.",d:"harsh criticism; to rebuke formally"},
{w:"cerebral",p:"adj.",d:"related to the intellect"},
{w:"chaos",p:"n.",d:"absolute disorder"},
{w:"chastise",p:"v.",d:"to criticize severely"},
{w:"cherish",p:"v.",d:"to feel or show affection"},
{w:"chide",p:"v.",d:"to voice disapproval"},
{w:"choreography",p:"n.",d:"arrangement of dances"},
{w:"chronicle",p:"n.",d:"a written history; to write history"},
{w:"chronological",p:"adj.",d:"arranged in time order"},
{w:"circuitous",p:"adj.",d:"roundabout"},
{w:"circumlocution",p:"n.",d:"indirect, wordy language"},
{w:"circumscribed",p:"adj.",d:"marked off, bounded"},
{w:"circumspect",p:"adj.",d:"cautious"},
{w:"circumvent",p:"v.",d:"to get around"},
{w:"clairvoyant",p:"adj.",d:"able to perceive things others cannot"},
{w:"clamor",p:"n.",d:"loud noise; to loudly insist"},
{w:"clandestine",p:"adj.",d:"secret"},
{w:"cleave",p:"v.",d:"to divide; to stick together firmly"},
{w:"clemency",p:"n.",d:"mercy"},
{w:"clergy",p:"n.",d:"members of holy orders"},
{w:"cloying",p:"adj.",d:"sickeningly sweet"},
{w:"coagulate",p:"v.",d:"to thicken, clot"},
{w:"coalesce",p:"v.",d:"to fuse into a whole"},
{w:"cobbler",p:"n.",d:"a shoe repairer"},
{w:"coerce",p:"v.",d:"to force by threat"},
{w:"cogent",p:"adj.",d:"intellectually convincing"},
{w:"cognizant",p:"adj.",d:"aware, mindful"},
{w:"coherent",p:"adj.",d:"logically consistent"},
{w:"collateral",p:"adj.",d:"secondary; security for a debt"},
{w:"colloquial",p:"adj.",d:"characteristic of informal conversation"},
{w:"collusion",p:"n.",d:"secret agreement, conspiracy"},
{w:"colossus",p:"n.",d:"a gigantic statue or thing"},
{w:"combustion",p:"n.",d:"the act of burning"},
{w:"commendation",p:"n.",d:"notice of approval"},
{w:"commensurate",p:"adj.",d:"corresponding in size or amount"},
{w:"commodious",p:"adj.",d:"roomy"},
{w:"compelling",p:"adj.",d:"forceful, demanding attention"},
{w:"compensate",p:"v.",d:"to make appropriate payment"},
{w:"complacency",p:"n.",d:"self-satisfied ignorance of danger"},
{w:"complement",p:"v.",d:"to complete, make perfect"},
{w:"compliant",p:"adj.",d:"ready to adapt to wishes"},
{w:"complicit",p:"adj.",d:"being an accomplice"},
{w:"compliment",p:"n.",d:"expression of esteem"},
{w:"compound",p:"v.",d:"to combine; a combination"},
{w:"comprehensive",p:"adj.",d:"including everything"},
{w:"compress",p:"v.",d:"to apply pressure, squeeze"},
{w:"compunction",p:"n.",d:"distress from guilt"},
{w:"concede",p:"v.",d:"to accept as valid"},
{w:"conciliatory",p:"adj.",d:"friendly, agreeable"},
{w:"concise",p:"adj.",d:"brief, direct"},
{w:"concoct",p:"v.",d:"to fabricate, make up"},
{w:"concomitant",p:"adj.",d:"accompanying in a subordinate fashion"},
{w:"concord",p:"n.",d:"harmonious agreement"},
{w:"condolence",p:"n.",d:"expression of sympathy"},
{w:"condone",p:"v.",d:"to pardon, overlook"},
{w:"conduit",p:"n.",d:"a pipe or channel"},
{w:"confection",p:"n.",d:"a sweet, fancy food"},
{w:"confidant",p:"n.",d:"a person entrusted with secrets"},
{w:"conflagration",p:"n.",d:"great fire"},
{w:"confluence",p:"n.",d:"a gathering together"},
{w:"conformist",p:"n.",d:"one who behaves like others"},
{w:"confound",p:"v.",d:"to frustrate, confuse"},
{w:"congeal",p:"v.",d:"to thicken into a solid"},
{w:"congenial",p:"adj.",d:"pleasantly agreeable"},
{w:"congregation",p:"n.",d:"a gathering, usually religious"},
{w:"congruity",p:"n.",d:"quality of being in agreement"},
{w:"connive",p:"v.",d:"to plot, scheme"},
{w:"consecrate",p:"v.",d:"to dedicate to a holy purpose"},
{w:"consensus",p:"n.",d:"an agreement of opinion"},
{w:"consign",p:"v.",d:"to give over to another's care"},
{w:"consolation",p:"n.",d:"an act of comforting"},
{w:"consonant",p:"adj.",d:"in harmony"},
{w:"constituent",p:"n.",d:"an essential part"},
{w:"constrain",p:"v.",d:"to forcibly restrict"},
{w:"construe",p:"v.",d:"to interpret"},
{w:"consummate",p:"v.",d:"to complete a deal or marriage"},
{w:"consumption",p:"n.",d:"the act of consuming"},
{w:"contemporaneous",p:"adj.",d:"existing during the same time"},
{w:"contentious",p:"adj.",d:"tending to quarrel"},
{w:"contravene",p:"v.",d:"to contradict, violate"},
{w:"contrite",p:"adj.",d:"penitent, eager to be forgiven"},
{w:"contusion",p:"n.",d:"bruise, injury"},
{w:"conundrum",p:"n.",d:"puzzle, problem"},
{w:"convene",p:"v.",d:"to call together"},
{w:"convention",p:"n.",d:"an assembly; a rule or custom"},
{w:"convivial",p:"adj.",d:"characterized by feasting or merriment"},
{w:"convoluted",p:"adj.",d:"intricate, complicated"},
{w:"copious",p:"adj.",d:"profuse, abundant"},
{w:"cordial",p:"adj.",d:"warm, affectionate"},
{w:"coronation",p:"n.",d:"the act of crowning"},
{w:"corpulence",p:"n.",d:"extreme fatness"},
{w:"corroborate",p:"v.",d:"to support with evidence"},
{w:"corrosive",p:"adj.",d:"having tendency to erode"},
{w:"cosmopolitan",p:"adj.",d:"sophisticated, worldly"},
{w:"counteract",p:"v.",d:"to neutralize"},
{w:"coup",p:"n.",d:"a brilliant act; overthrow of government"},
{w:"covert",p:"adj.",d:"secretly engaged in"},
{w:"covet",p:"v.",d:"to desire enviously"},
{w:"credulity",p:"n.",d:"readiness to believe"},
{w:"crescendo",p:"n.",d:"steady increase in intensity"},
{w:"criteria",p:"n.",d:"standards for judgment"},
{w:"culmination",p:"n.",d:"the climax"},
{w:"culpable",p:"adj.",d:"deserving blame"},
{w:"cultivate",p:"v.",d:"to nurture, improve"},
{w:"cumulative",p:"adj.",d:"increasing, building upon itself"},
{w:"cunning",p:"adj.",d:"sly, clever at deceit"},
{w:"cupidity",p:"n.",d:"greed, strong desire"},
{w:"cursory",p:"adj.",d:"brief, superficial"},
{w:"curt",p:"adj.",d:"abruptly or rudely short"},
{w:"curtail",p:"v.",d:"to lessen, reduce"},
{w:"daunting",p:"adj.",d:"intimidating"},
{w:"dearth",p:"n.",d:"a lack, scarcity"},
{w:"debacle",p:"n.",d:"a disastrous failure"},
{w:"debase",p:"v.",d:"to lower quality or esteem"},
{w:"debauch",p:"v.",d:"to corrupt via sensual pleasures"},
{w:"debunk",p:"v.",d:"to expose falseness"},
{w:"decorous",p:"adj.",d:"socially proper"},
{w:"decry",p:"v.",d:"to criticize openly"},
{w:"deface",p:"v.",d:"to ruin appearance"},
{w:"defamatory",p:"adj.",d:"harmful to reputation"},
{w:"defer",p:"v.",d:"to postpone; to yield to wisdom"},
{w:"deferential",p:"adj.",d:"showing respect for authority"},
{w:"defile",p:"v.",d:"to make unclean or impure"},
{w:"deft",p:"adj.",d:"skillful, capable"},
{w:"defunct",p:"adj.",d:"no longer used or existing"},
{w:"delegate",p:"v.",d:"to hand over responsibility"},
{w:"deleterious",p:"adj.",d:"harmful"},
{w:"deliberate",p:"adj.",d:"intentional, careful"},
{w:"delineate",p:"v.",d:"to describe, outline"},
{w:"demagogue",p:"n.",d:"leader appealing to prejudices"},
{w:"demarcation",p:"n.",d:"marking of boundaries"},
{w:"demean",p:"v.",d:"to lower status or stature"},
{w:"demure",p:"adj.",d:"quiet, modest, reserved"},
{w:"denigrate",p:"v.",d:"to belittle"},
{w:"denounce",p:"v.",d:"to criticize publicly"},
{w:"deplore",p:"v.",d:"to feel sorrow or disapproval"},
{w:"depravity",p:"n.",d:"wickedness"},
{w:"deprecate",p:"v.",d:"to belittle, depreciate"},
{w:"derelict",p:"adj.",d:"abandoned, run-down"},
{w:"deride",p:"v.",d:"to laugh at mockingly"},
{w:"derivative",p:"adj.",d:"taken from a source, unoriginal"},
{w:"desecrate",p:"v.",d:"to violate sacredness"},
{w:"desiccated",p:"adj.",d:"dried up, dehydrated"},
{w:"desolate",p:"adj.",d:"deserted, dreary"},
{w:"despondent",p:"adj.",d:"depressed, hopeless"},
{w:"despot",p:"n.",d:"one with total brutal power"},
{w:"destitute",p:"adj.",d:"impoverished"},
{w:"deter",p:"v.",d:"to discourage, prevent"},
{w:"devious",p:"adj.",d:"not straightforward, deceitful"},
{w:"dialect",p:"n.",d:"a variation of a language"},
{w:"diaphanous",p:"adj.",d:"light, airy, transparent"},
{w:"didactic",p:"adj.",d:"intended to instruct; overly moralistic"},
{w:"didacticism",p:"n.",d:"the quality of being overly moralistic or instructional"},
{w:"diffident",p:"adj.",d:"shy, quiet, modest"},
{w:"diffuse",p:"v.",d:"to scatter; not concentrated"},
{w:"dilatory",p:"adj.",d:"tending to delay"},
{w:"diligent",p:"adj.",d:"showing care in work"},
{w:"diminutive",p:"adj.",d:"small, miniature"},
{w:"dirge",p:"n.",d:"a mournful song"},
{w:"disaffected",p:"adj.",d:"rebellious, resentful"},
{w:"disavow",p:"v.",d:"to deny knowledge or responsibility"},
{w:"discern",p:"v.",d:"to perceive, detect"},
{w:"disclose",p:"v.",d:"to reveal"},
{w:"discomfit",p:"v.",d:"to thwart, baffle"},
{w:"discordant",p:"adj.",d:"not in harmony"},
{w:"discrepancy",p:"n.",d:"difference, failure to correspond"},
{w:"discretion",p:"n.",d:"reserve in speech or action; good judgment"},
{w:"discursive",p:"adj.",d:"rambling, lacking order"},
{w:"disdain",p:"v.",d:"to scorn"},
{w:"disgruntled",p:"adj.",d:"upset, not content"},
{w:"disheartened",p:"adj.",d:"loss of spirit or morale"},
{w:"disparage",p:"v.",d:"to criticize or speak ill of"},
{w:"disparate",p:"adj.",d:"sharply differing"},
{w:"dispatch",p:"v.",d:"to send off"},
{w:"dispel",p:"v.",d:"to drive away, scatter"},
{w:"disperse",p:"v.",d:"to scatter"},
{w:"disrepute",p:"n.",d:"state of being held in low regard"},
{w:"dissemble",p:"v.",d:"to conceal, fake"},
{w:"disseminate",p:"v.",d:"to spread widely"},
{w:"dissent",p:"v.",d:"to disagree"},
{w:"dissipate",p:"v.",d:"to disappear; to waste"},
{w:"dissonance",p:"n.",d:"lack of harmony or consistency"},
{w:"dissuade",p:"v.",d:"to persuade someone not to do something"},
{w:"distend",p:"v.",d:"to swell out"},
{w:"dither",p:"v.",d:"to be indecisive"},
{w:"divine",p:"adj.",d:"godly, wonderful"},
{w:"divisive",p:"adj.",d:"causing dissent or discord"},
{w:"divulge",p:"v.",d:"to reveal something secret"},
{w:"docile",p:"adj.",d:"easily taught"},
{w:"dogmatic",p:"adj.",d:"arrogantly certain about unproved principles"},
{w:"dormant",p:"adj.",d:"sleeping, inactive"},
{w:"dour",p:"adj.",d:"stern, joyless"},
{w:"dubious",p:"adj.",d:"doubtful, uncertain quality"},
{w:"duplicity",p:"n.",d:"crafty dishonesty"},
{w:"duress",p:"n.",d:"hardship, threat"},
{w:"dynamic",p:"adj.",d:"actively changing"},
{w:"ebullient",p:"adj.",d:"extremely lively, enthusiastic"},
{w:"eclectic",p:"adj.",d:"diverse variety of elements"},
{w:"ecstatic",p:"adj.",d:"intensely happy"},
{w:"edict",p:"n.",d:"an order, decree"},
{w:"efface",p:"v.",d:"to wipe out, obliterate"},
{w:"effervescent",p:"adj.",d:"bubbly, lively"},
{w:"efficacious",p:"adj.",d:"effective"},
{w:"effrontery",p:"n.",d:"impudence, nerve"},
{w:"effulgent",p:"adj.",d:"radiant, splendorous"},
{w:"egregious",p:"adj.",d:"extremely bad"},
{w:"elaborate",p:"adj.",d:"complex, detailed"},
{w:"elated",p:"adj.",d:"overjoyed, thrilled"},
{w:"elegy",p:"n.",d:"speech honoring the dead"},
{w:"elicit",p:"v.",d:"to bring forth, draw out"},
{w:"eloquent",p:"adj.",d:"expressive, articulate"},
{w:"elucidate",p:"v.",d:"to clarify, explain"},
{w:"elude",p:"v.",d:"to evade, escape"},
{w:"emaciated",p:"adj.",d:"very thin, enfeebled"},
{w:"embellish",p:"v.",d:"to decorate; to add details"},
{w:"embezzle",p:"v.",d:"to steal money by falsifying records"},
{w:"emend",p:"v.",d:"to correct or revise text"},
{w:"eminent",p:"adj.",d:"distinguished, famous; conspicuous"},
{w:"emollient",p:"adj.",d:"soothing"},
{w:"emote",p:"v.",d:"to express emotion"},
{w:"empathy",p:"n.",d:"sensitivity to another's feelings"},
{w:"empirical",p:"adj.",d:"based on observation or experience"},
{w:"emulate",p:"v.",d:"to imitate"},
{w:"enamor",p:"v.",d:"to fill with love or fascinate"},
{w:"encore",p:"n.",d:"demand for repeat performance"},
{w:"encumber",p:"v.",d:"to weigh down, burden"},
{w:"enervate",p:"v.",d:"to weaken, exhaust"},
{w:"enervating",p:"adj.",d:"causing one to feel drained of energy"},
{w:"enfranchise",p:"v.",d:"to grant the vote"},
{w:"engender",p:"v.",d:"to bring about, create"},
{w:"enigmatic",p:"adj.",d:"mystifying, cryptic"},
{w:"enmity",p:"n.",d:"ill will, hatred"},
{w:"ennui",p:"n.",d:"boredom, weariness"},
{w:"entail",p:"v.",d:"to include as a necessary step"},
{w:"enthrall",p:"v.",d:"to charm, hold spellbound"},
{w:"ephemera",p:"n.",d:"items of collectible memorabilia originally expected to have only short-term usefulness"},
{w:"ephemeral",p:"adj.",d:"short-lived, fleeting"},
{w:"epistolary",p:"adj.",d:"relating to letters"},
{w:"epitome",p:"n.",d:"a perfect example"},
{w:"equanimity",p:"n.",d:"composure"},
{w:"equivocal",p:"adj.",d:"ambiguous, uncertain"},
{w:"erudite",p:"adj.",d:"learned"},
{w:"eschew",p:"v.",d:"to shun, avoid"},
{w:"esoteric",p:"adj.",d:"understood by only a select few"},
{w:"espouse",p:"v.",d:"to take up as a cause, support"},
{w:"ethereal",p:"adj.",d:"heavenly, delicate"},
{w:"etymology",p:"n.",d:"history or origin of words"},
{w:"euphoric",p:"adj.",d:"elated, uplifted"},
{w:"evanescent",p:"adj.",d:"fleeting, momentary"},
{w:"evince",p:"v.",d:"to show, reveal"},
{w:"exacerbate",p:"v.",d:"to make more violent or intense"},
{w:"exalt",p:"v.",d:"to glorify, praise"},
{w:"exasperate",p:"v.",d:"to irritate, irk"},
{w:"excavate",p:"v.",d:"to dig out or remove"},
{w:"exculpate",p:"v.",d:"to free from guilt or blame"},
{w:"excursion",p:"n.",d:"a trip or outing"},
{w:"execrable",p:"adj.",d:"loathsome, detestable"},
{w:"exhort",p:"v.",d:"to urge, prod"},
{w:"exigent",p:"adj.",d:"urgent, critical"},
{w:"exonerate",p:"v.",d:"to free from guilt or blame"},
{w:"exorbitant",p:"adj.",d:"excessive"},
{w:"expedient",p:"adj.",d:"advisable, serving self-interest"},
{w:"expiate",p:"v.",d:"to make amends, atone"},
{w:"expunge",p:"v.",d:"to obliterate, eradicate"},
{w:"expurgate",p:"v.",d:"to remove offensive parts"},
{w:"extant",p:"adj.",d:"existing, not lost"},
{w:"extol",p:"v.",d:"to praise, revere"},
{w:"extraneous",p:"adj.",d:"irrelevant, extra"},
{w:"extricate",p:"v.",d:"to disentangle"},
{w:"exult",p:"v.",d:"to rejoice"},
{w:"fabricate",p:"v.",d:"to make up, invent"},
{w:"facade",p:"n.",d:"wall of a building; deceptive appearance"},
{w:"facile",p:"adj.",d:"easy; superficial or insincere"},
{w:"fallacious",p:"adj.",d:"incorrect, misleading"},
{w:"fastidious",p:"adj.",d:"meticulous, demanding high standards"},
{w:"fathom",p:"v.",d:"to understand, comprehend"},
{w:"fatuous",p:"adj.",d:"silly, foolish"},
{w:"fecund",p:"adj.",d:"fruitful, fertile"},
{w:"felicitous",p:"adj.",d:"well suited or apt; delightful"},
{w:"feral",p:"adj.",d:"wild, savage"},
{w:"fervent",p:"adj.",d:"ardent, passionate"},
{w:"fetid",p:"adj.",d:"having a foul odor"},
{w:"fetter",p:"v.",d:"to chain, restrain"},
{w:"fickle",p:"adj.",d:"shifting, inconstant"},
{w:"fidelity",p:"n.",d:"loyalty, devotion"},
{w:"figurative",p:"adj.",d:"symbolic"},
{w:"flabbergasted",p:"adj.",d:"astounded"},
{w:"flaccid",p:"adj.",d:"limp, not firm"},
{w:"flagrant",p:"adj.",d:"offensive, egregious"},
{w:"florid",p:"adj.",d:"flowery, ornate"},
{w:"flout",p:"v.",d:"to disregard or disobey openly"},
{w:"foil",p:"v.",d:"to thwart, defeat"},
{w:"forage",p:"v.",d:"to graze, rummage for food"},
{w:"forbearance",p:"n.",d:"patience, restraint"},
{w:"forestall",p:"v.",d:"to prevent, thwart"},
{w:"forlorn",p:"adj.",d:"lonely, abandoned, hopeless"},
{w:"forsake",p:"v.",d:"to give up, renounce"},
{w:"fortitude",p:"n.",d:"strength, guts"},
{w:"fortuitous",p:"adj.",d:"happening by chance, lucky"},
{w:"forum",p:"n.",d:"medium for discussion"},
{w:"foster",p:"v.",d:"to stimulate, promote"},
{w:"fractious",p:"adj.",d:"troublesome, irritable"},
{w:"fraught",p:"adj.",d:"filled or accompanied with"},
{w:"frenetic",p:"adj.",d:"frenzied, hectic"},
{w:"frivolous",p:"adj.",d:"of little importance"},
{w:"frugal",p:"adj.",d:"thrifty, economical"},
{w:"furtive",p:"adj.",d:"secretive, sly"},
{w:"garish",p:"adj.",d:"gaudy, in bad taste"},
{w:"garrulous",p:"adj.",d:"talkative, wordy"},
{w:"genial",p:"adj.",d:"friendly, affable"},
{w:"gluttony",p:"n.",d:"overindulgence in food or drink"},
{w:"goad",p:"v.",d:"to urge, spur"},
{w:"gourmand",p:"n.",d:"someone fond of eating or drinking"},
{w:"grandiloquence",p:"n.",d:"lofty, pompous language"},
{w:"grandiose",p:"adj.",d:"magnificent or exaggerated scale"},
{w:"grandiosity",p:"n.",d:"the quality of being grandiose"},
{w:"gratuitous",p:"adj.",d:"uncalled for, unwarranted"},
{w:"gregarious",p:"adj.",d:"sociable, drawn to company"},
{w:"grievous",p:"adj.",d:"injurious, serious"},
{w:"guile",p:"n.",d:"deceitful, cunning behavior"},
{w:"hackneyed",p:"adj.",d:"unoriginal, trite"},
{w:"hallowed",p:"adj.",d:"revered, consecrated"},
{w:"hapless",p:"adj.",d:"unlucky"},
{w:"harangue",p:"n.",d:"a ranting speech"},
{w:"hardy",p:"adj.",d:"robust, capable of surviving adversity"},
{w:"harrowing",p:"adj.",d:"greatly distressing"},
{w:"haughty",p:"adj.",d:"disdainfully proud"},
{w:"hedonist",p:"n.",d:"one who believes pleasure is primary"},
{w:"hegemony",p:"n.",d:"domination over others"},
{w:"heinous",p:"adj.",d:"shockingly wicked"},
{w:"heterogeneous",p:"adj.",d:"varied, diverse"},
{w:"hiatus",p:"n.",d:"a break or gap"},
{w:"hierarchy",p:"n.",d:"system of ranked groups"},
{w:"hypocrisy",p:"n.",d:"pretending to believe what one does not"},
{w:"hypothetical",p:"adj.",d:"supposed true but unproven"},
{w:"iconoclasm",p:"n.",d:"the action of attacking cherished beliefs"},
{w:"iconoclast",p:"n.",d:"one who attacks common beliefs"},
{w:"idiosyncratic",p:"adj.",d:"peculiar to one person"},
{w:"idolatrous",p:"adj.",d:"excessively worshipping"},
{w:"ignominious",p:"adj.",d:"humiliating, disgracing"},
{w:"illicit",p:"adj.",d:"forbidden, not permitted"},
{w:"immerse",p:"v.",d:"to absorb, deeply involve"},
{w:"immutability",p:"n.",d:"the state of being unchangeable"},
{w:"immutable",p:"adj.",d:"not changeable"},
{w:"impassive",p:"adj.",d:"stoic, not susceptible to suffering"},
{w:"impeccable",p:"adj.",d:"exemplary, flawless"},
{w:"impecunious",p:"adj.",d:"poor"},
{w:"imperative",p:"adj.",d:"necessary or pressing; a command"},
{w:"imperious",p:"adj.",d:"commanding, domineering"},
{w:"impertinent",p:"adj.",d:"rude, insolent"},
{w:"impervious",p:"adj.",d:"impenetrable"},
{w:"impetuous",p:"adj.",d:"rash, hastily done"},
{w:"impinge",p:"v.",d:"to impact or affect; to encroach"},
{w:"implacable",p:"adj.",d:"incapable of being appeased"},
{w:"implement",p:"v.",d:"a tool; to put into effect"},
{w:"implicate",p:"v.",d:"to involve in an incriminating way"},
{w:"implicit",p:"adj.",d:"understood but not obvious"},
{w:"impregnable",p:"adj.",d:"resistant to capture"},
{w:"impudent",p:"adj.",d:"casually rude, insolent"},
{w:"impute",p:"v.",d:"to ascribe, blame"},
{w:"inane",p:"adj.",d:"silly, meaningless"},
{w:"inarticulate",p:"adj.",d:"incapable of expressing clearly"},
{w:"incarnate",p:"adj.",d:"embodied in flesh"},
{w:"incendiary",p:"adj.",d:"inflammatory; an agitator"},
{w:"incessant",p:"adj.",d:"unending"},
{w:"inchoate",p:"adj.",d:"just begun and so not fully formed or developed"},
{w:"incisive",p:"adj.",d:"clear, sharp, direct"},
{w:"inclination",p:"n.",d:"a tendency, propensity"},
{w:"incontrovertible",p:"adj.",d:"indisputable"},
{w:"incorrigible",p:"adj.",d:"incapable of correction"},
{w:"increment",p:"n.",d:"an enlargement or increase"},
{w:"incumbent",p:"n.",d:"office holder; obligatory"},
{w:"indefatigable",p:"adj.",d:"incapable of defeat or failure"},
{w:"indigenous",p:"adj.",d:"originating in a region"},
{w:"indigent",p:"adj.",d:"very poor, impoverished"},
{w:"indignation",p:"n.",d:"anger sparked by injustice"},
{w:"indolent",p:"adj.",d:"lazy"},
{w:"indomitable",p:"adj.",d:"not capable of being conquered"},
{w:"induce",p:"v.",d:"to bring about, stimulate"},
{w:"ineffable",p:"adj.",d:"unspeakable"},
{w:"inept",p:"adj.",d:"not suitable or capable"},
{w:"inexorable",p:"adj.",d:"incapable of being persuaded"},
{w:"inextricable",p:"adj.",d:"hopelessly tangled"},
{w:"infamy",p:"n.",d:"notoriety, extreme ill repute"},
{w:"infusion",p:"n.",d:"injection or permeation of one substance into another"},
{w:"ingenious",p:"adj.",d:"clever, resourceful"},
{w:"ingenuous",p:"adj.",d:"not devious; innocent, candid"},
{w:"inhibit",p:"v.",d:"to prevent, restrain"},
{w:"inimical",p:"adj.",d:"hostile, enemy-like"},
{w:"iniquity",p:"n.",d:"wickedness, sin"},
{w:"injunction",p:"n.",d:"an order of official warning"},
{w:"innate",p:"adj.",d:"inborn, inherent"},
{w:"innocuous",p:"adj.",d:"harmless, inoffensive"},
{w:"innovate",p:"v.",d:"to do something unprecedented"},
{w:"innuendo",p:"n.",d:"an insinuation"},
{w:"inoculate",p:"v.",d:"to vaccinate"},
{w:"inquisitor",p:"n.",d:"one who inquires hostilely"},
{w:"insatiable",p:"adj.",d:"incapable of being satisfied"},
{w:"insidious",p:"adj.",d:"appealing but imperceptibly harmful"},
{w:"insinuate",p:"v.",d:"to suggest indirectly"},
{w:"insipid",p:"adj.",d:"dull, boring"},
{w:"insolent",p:"adj.",d:"rude, arrogant"},
{w:"instigate",p:"v.",d:"to urge, goad"},
{w:"insular",p:"adj.",d:"separated, narrow-minded"},
{w:"insurgent",p:"n.",d:"one who rebels"},
{w:"integral",p:"adj.",d:"necessary for completeness"},
{w:"interject",p:"v.",d:"to insert between things"},
{w:"interlocutor",p:"n.",d:"someone in a dialogue"},
{w:"interminable",p:"adj.",d:"without possibility of end"},
{w:"intimation",p:"n.",d:"an indirect suggestion"},
{w:"intractable",p:"adj.",d:"difficult to manipulate"},
{w:"intransigent",p:"adj.",d:"refusing to compromise"},
{w:"intrepid",p:"adj.",d:"brave in face of danger"},
{w:"inundate",p:"v.",d:"to flood with abundance"},
{w:"inure",p:"v.",d:"to become accustomed to"},
{w:"invective",p:"n.",d:"angry verbal attack"},
{w:"inveterate",p:"adj.",d:"stubbornly established by habit"},
{w:"inviolable",p:"adj.",d:"secure from assault"},
{w:"irascible",p:"adj.",d:"easily angered"},
{w:"iridescent",p:"adj.",d:"showing rainbow colors"},
{w:"irreverence",p:"n.",d:"disrespect"},
{w:"irrevocable",p:"adj.",d:"incapable of being taken back"},
{w:"jubilant",p:"adj.",d:"extremely joyful"},
{w:"judicious",p:"adj.",d:"having sound judgment"},
{w:"juxtaposition",p:"n.",d:"placing two things next to each other"},
{w:"knell",p:"n.",d:"solemn sound of a bell, usually death"},
{w:"kudos",p:"n.",d:"praise for achievement"},
{w:"laceration",p:"n.",d:"a cut, tear"},
{w:"laconic",p:"adj.",d:"terse in speech or writing"},
{w:"languid",p:"adj.",d:"sluggish from fatigue"},
{w:"larceny",p:"n.",d:"theft by trickery"},
{w:"largess",p:"n.",d:"generous giving of lavish gifts"},
{w:"latent",p:"adj.",d:"hidden but capable of exposure"},
{w:"laudatory",p:"adj.",d:"expressing admiration or praise"},
{w:"lavish",p:"adj.",d:"given without limits"},
{w:"legerdemain",p:"n.",d:"deception, sleight-of-hand"},
{w:"lenient",p:"adj.",d:"demonstrating tolerance"},
{w:"lethargic",p:"adj.",d:"sluggish, apathetic"},
{w:"liability",p:"n.",d:"legal responsibility; a handicap or burden"},
{w:"libertarian",p:"adj.",d:"advocating liberty or free will"},
{w:"licentious",p:"adj.",d:"lacking moral or legal restraints"},
{w:"limpid",p:"adj.",d:"clear, transparent"},
{w:"linchpin",p:"n.",d:"something holding parts together"},
{w:"lithe",p:"adj.",d:"graceful, flexible"},
{w:"litigant",p:"n.",d:"someone engaged in a lawsuit"},
{w:"lucid",p:"adj.",d:"clear, understandable"},
{w:"lugubrious",p:"adj.",d:"looking or sounding sad and dismal"},
{w:"luminous",p:"adj.",d:"brightly shining"},
{w:"lurid",p:"adj.",d:"ghastly, sensational"},
{w:"maelstrom",p:"n.",d:"destructive whirlpool"},
{w:"magnanimity",p:"n.",d:"the quality of being magnanimous; generous nobility"},
{w:"magnanimous",p:"adj.",d:"noble, generous"},
{w:"malediction",p:"n.",d:"a curse"},
{w:"malevolent",p:"adj.",d:"wanting harm to befall others"},
{w:"malleable",p:"adj.",d:"capable of being shaped"},
{w:"mandate",p:"n.",d:"authoritative command"},
{w:"manifest",p:"adj.",d:"obvious; to show plainly"},
{w:"manifold",p:"adj.",d:"diverse, varied"},
{w:"maudlin",p:"adj.",d:"weakly sentimental"},
{w:"maverick",p:"n.",d:"independent, nonconformist"},
{w:"mawkish",p:"adj.",d:"sick sentimentality"},
{w:"maxim",p:"n.",d:"common saying expressing a principle"},
{w:"meager",p:"adj.",d:"deficient in size or quality"},
{w:"medley",p:"n.",d:"mixture of differing things"},
{w:"mendacious",p:"adj.",d:"lying, false"},
{w:"mercurial",p:"adj.",d:"rapid change in temperament"},
{w:"meritorious",p:"adj.",d:"worthy of esteem or reward"},
{w:"metamorphosis",p:"n.",d:"change of form or substance"},
{w:"meticulous",p:"adj.",d:"extremely careful with details"},
{w:"mitigate",p:"v.",d:"to make less violent or alleviate"},
{w:"moderate",p:"adj.",d:"not extreme"},
{w:"modicum",p:"n.",d:"a small amount"},
{w:"modulate",p:"v.",d:"to pass from one state to another"},
{w:"mollify",p:"v.",d:"to soften in temper"},
{w:"morass",p:"n.",d:"swamp; something trapping or confusing"},
{w:"mores",p:"n.",d:"moral attitudes or customs of a group"},
{w:"morose",p:"adj.",d:"gloomy, sullen"},
{w:"multifarious",p:"adj.",d:"great diversity or variety"},
{w:"mundane",p:"adj.",d:"commonplace, worldly"},
{w:"munificence",p:"n.",d:"generosity in giving"},
{w:"mutable",p:"adj.",d:"able to change"},
{w:"myriad",p:"adj.",d:"consisting of a very great number"},
{w:"nadir",p:"n.",d:"the lowest point"},
{w:"nascent",p:"adj.",d:"coming into existence"},
{w:"nebulous",p:"adj.",d:"vaguely defined, cloudy"},
{w:"nefarious",p:"adj.",d:"heinously villainous"},
{w:"negligent",p:"adj.",d:"habitually careless"},
{w:"neophyte",p:"n.",d:"young or inexperienced person"},
{w:"nocturnal",p:"adj.",d:"relating to night"},
{w:"noisome",p:"adj.",d:"unpleasant smell"},
{w:"nomadic",p:"adj.",d:"wandering place to place"},
{w:"nominal",p:"adj.",d:"trifling, insignificant"},
{w:"nonchalant",p:"adj.",d:"lacking concern, indifference"},
{w:"nondescript",p:"adj.",d:"lacking distinctive character"},
{w:"notorious",p:"adj.",d:"widely and unfavorably known"},
{w:"novice",p:"n.",d:"beginner"},
{w:"noxious",p:"adj.",d:"harmful, unwholesome"},
{w:"nuance",p:"n.",d:"slight variation in meaning or tone"},
{w:"nurture",p:"v.",d:"to assist development"},
{w:"obdurate",p:"adj.",d:"unyielding to persuasion"},
{w:"obfuscate",p:"v.",d:"to render incomprehensible"},
{w:"obfuscation",p:"n.",d:"the action of making something unclear"},
{w:"oblique",p:"adj.",d:"not straightforward"},
{w:"oblivious",p:"adj.",d:"lacking awareness"},
{w:"obscure",p:"adj.",d:"unclear, partially hidden"},
{w:"obsequious",p:"adj.",d:"excessively compliant or submissive"},
{w:"obsolete",p:"adj.",d:"no longer used, out of date"},
{w:"obstinate",p:"adj.",d:"stubborn"},
{w:"obstreperous",p:"adj.",d:"noisy, unruly"},
{w:"obtuse",p:"adj.",d:"lacking quickness of intellect"},
{w:"odious",p:"adj.",d:"instilling hatred or displeasure"},
{w:"officious",p:"adj.",d:"offering unwanted services"},
{w:"ominous",p:"adj.",d:"foreboding evil"},
{w:"onerous",p:"adj.",d:"burdensome"},
{w:"opulent",p:"adj.",d:"rich abundance, ostentatious"},
{w:"oration",p:"n.",d:"formal speech"},
{w:"ornate",p:"adj.",d:"highly elaborate, decorated"},
{w:"orthodox",p:"adj.",d:"conventional"},
{w:"oscillate",p:"v.",d:"to sway side to side"},
{w:"ostensible",p:"adj.",d:"appearing as such, seemingly"},
{w:"ostentatious",p:"adj.",d:"excessively showy"},
{w:"ostracism",p:"n.",d:"exclusion from a group"},
{w:"pacific",p:"adj.",d:"soothing"},
{w:"palatable",p:"adj.",d:"agreeable to taste"},
{w:"palette",p:"n.",d:"range of colors or qualities"},
{w:"palliate",p:"v.",d:"to reduce severity"},
{w:"pallid",p:"adj.",d:"lacking color"},
{w:"panacea",p:"n.",d:"remedy for all ills"},
{w:"paradigm",p:"n.",d:"perfect pattern or model"},
{w:"paradox",p:"n.",d:"apparently contradictory statement"},
{w:"paragon",p:"n.",d:"model of excellence"},
{w:"paramount",p:"adj.",d:"greatest in importance"},
{w:"pariah",p:"n.",d:"an outcast"},
{w:"parody",p:"n.",d:"satirical imitation"},
{w:"parsimony",p:"n.",d:"frugality, stinginess"},
{w:"partisan",p:"n.",d:"follower, adherent"},
{w:"patent",p:"adj.",d:"readily seen, clear"},
{w:"pathology",p:"n.",d:"deviation from normal"},
{w:"pathos",p:"n.",d:"emotion of sympathy"},
{w:"paucity",p:"n.",d:"small quantity"},
{w:"pejorative",p:"adj.",d:"derogatory"},
{w:"pellucid",p:"adj.",d:"easily intelligible, clear"},
{w:"penchant",p:"n.",d:"tendency, preference"},
{w:"penitent",p:"adj.",d:"remorseful"},
{w:"penultimate",p:"adj.",d:"next to last"},
{w:"penurious",p:"adj.",d:"miserly, stingy"},
{w:"perfidious",p:"adj.",d:"disloyal, unfaithful"},
{w:"perfunctory",p:"adj.",d:"showing little interest"},
{w:"permeate",p:"v.",d:"to spread throughout"},
{w:"pernicious",p:"adj.",d:"extremely destructive or harmful"},
{w:"perniciousness",p:"n.",d:"the quality of having a harmful effect"},
{w:"perplex",p:"v.",d:"to confuse"},
{w:"perspicacity",p:"n.",d:"shrewdness, perceptiveness"},
{w:"pert",p:"adj.",d:"flippant, bold"},
{w:"pertinacious",p:"adj.",d:"stubbornly persistent"},
{w:"perusal",p:"n.",d:"careful examination"},
{w:"pervasive",p:"adj.",d:"tending to spread throughout"},
{w:"petulance",p:"n.",d:"rudeness, irritability"},
{w:"philanthropic",p:"adj.",d:"charitable"},
{w:"phlegmatic",p:"adj.",d:"uninterested, unresponsive"},
{w:"pillage",p:"v.",d:"to seize or plunder"},
{w:"pinnacle",p:"n.",d:"highest point"},
{w:"pithy",p:"adj.",d:"concisely meaningful"},
{w:"pittance",p:"n.",d:"very small amount of money"},
{w:"placate",p:"v.",d:"to ease anger, soothe"},
{w:"placid",p:"adj.",d:"calm, peaceful"},
{w:"platitude",p:"n.",d:"uninspired remark, cliche"},
{w:"plaudits",p:"n.",d:"enthusiastic approval"},
{w:"plausible",p:"adj.",d:"believable, reasonable"},
{w:"plenitude",p:"n.",d:"an abundance"},
{w:"plethora",p:"n.",d:"an abundance, excess"},
{w:"pliable",p:"adj.",d:"flexible"},
{w:"poignant",p:"adj.",d:"deeply affecting, moving"},
{w:"polemic",p:"n.",d:"aggressive argument against an opinion"},
{w:"portent",p:"n.",d:"an omen"},
{w:"potable",p:"adj.",d:"suitable for drinking"},
{w:"potentate",p:"n.",d:"one with great power or ruler"},
{w:"pragmatic",p:"adj.",d:"practical"},
{w:"precipice",p:"n.",d:"face of a cliff"},
{w:"preclude",p:"v.",d:"to prevent"},
{w:"precocious",p:"adj.",d:"advanced, developing early"},
{w:"predilection",p:"n.",d:"preference or inclination"},
{w:"preponderance",p:"n.",d:"superiority in importance or quantity"},
{w:"prepossessing",p:"adj.",d:"occupying the mind exclusively"},
{w:"presage",p:"n.",d:"an omen"},
{w:"prescient",p:"adj.",d:"having foreknowledge"},
{w:"prescribe",p:"v.",d:"to lay down a rule"},
{w:"presumptuous",p:"adj.",d:"disrespectfully bold"},
{w:"pretense",p:"n.",d:"appearance intended to deceive"},
{w:"primeval",p:"adj.",d:"original, ancient"},
{w:"privation",p:"n.",d:"lacking basic necessities"},
{w:"probity",p:"n.",d:"virtue, integrity"},
{w:"proclivity",p:"n.",d:"strong inclination"},
{w:"procure",p:"v.",d:"to obtain, acquire"},
{w:"profane",p:"adj.",d:"lewd, indecent"},
{w:"profligate",p:"adj.",d:"dissolute, extravagant"},
{w:"profuse",p:"adj.",d:"plentiful, abundant"},
{w:"promulgate",p:"v.",d:"to proclaim, make known"},
{w:"propagate",p:"v.",d:"to multiply, spread"},
{w:"propensity",p:"n.",d:"inclination, preference"},
{w:"propitious",p:"adj.",d:"favorable"},
{w:"propriety",p:"n.",d:"quality of being proper or decent"},
{w:"prosaic",p:"adj.",d:"plain, lacking liveliness"},
{w:"proscribe",p:"v.",d:"to condemn, outlaw"},
{w:"protean",p:"adj.",d:"able to change shape, varied"},
{w:"prowess",p:"n.",d:"extraordinary ability"},
{w:"prudence",p:"n.",d:"cautious, circumspect"},
{w:"prurient",p:"adj.",d:"extraordinary interest in sex"},
{w:"puerile",p:"adj.",d:"juvenile, immature"},
{w:"pugnacious",p:"adj.",d:"quarrelsome, combative"},
{w:"pulchritude",p:"n.",d:"physical beauty"},
{w:"punctilious",p:"adj.",d:"eager to follow rules"},
{w:"pungent",p:"adj.",d:"pointed, sharp smell"},
{w:"punitive",p:"adj.",d:"involving punishment"},
{w:"putrid",p:"adj.",d:"rotten, foul"},
{w:"quagmire",p:"n.",d:"a difficult situation"},
{w:"quaint",p:"adj.",d:"charmingly old-fashioned"},
{w:"quandary",p:"n.",d:"perplexed, unresolvable state"},
{w:"quell",p:"v.",d:"to control or diffuse"},
{w:"querulous",p:"adj.",d:"whiny, complaining"},
{w:"quixotic",p:"adj.",d:"idealistic, impractical"},
{w:"quotidian",p:"adj.",d:"daily"},
{w:"rail",p:"v.",d:"to scold, protest"},
{w:"rancid",p:"adj.",d:"terrible taste or smell"},
{w:"rancor",p:"n.",d:"deep, bitter resentment"},
{w:"rapport",p:"n.",d:"mutual understanding or harmony"},
{w:"rash",p:"adj.",d:"hasty, incautious"},
{w:"raucous",p:"adj.",d:"loud, boisterous"},
{w:"raze",p:"v.",d:"to demolish, level"},
{w:"rebuke",p:"v.",d:"to scold, criticize"},
{w:"recalcitrant",p:"adj.",d:"defiant, unapologetic"},
{w:"recapitulate",p:"v.",d:"to sum up, repeat"},
{w:"reciprocate",p:"v.",d:"to give in return"},
{w:"reclusive",p:"adj.",d:"solitary, shunning society"},
{w:"reconcile",p:"v.",d:"to return to harmony; to make consistent"},
{w:"rectitude",p:"n.",d:"uprightness, morality"},
{w:"redoubtable",p:"adj.",d:"formidable; commanding respect"},
{w:"refract",p:"v.",d:"to distort, change"},
{w:"refurbish",p:"v.",d:"to restore, clean up"},
{w:"refute",p:"v.",d:"to prove wrong"},
{w:"regurgitate",p:"v.",d:"to vomit; to throw back exactly"},
{w:"relegate",p:"v.",d:"to assign to proper or inferior place"},
{w:"relish",p:"v.",d:"to enjoy"},
{w:"remedial",p:"adj.",d:"intended to repair gaps"},
{w:"remiss",p:"adj.",d:"negligent"},
{w:"renovate",p:"v.",d:"to restore; enlarge or prettify"},
{w:"renown",p:"n.",d:"honor, acclaim"},
{w:"renunciation",p:"n.",d:"rejection"},
{w:"repentant",p:"adj.",d:"penitent, sorry"},
{w:"replete",p:"adj.",d:"full, abundant"},
{w:"repose",p:"v.",d:"to rest, lie down"},
{w:"reprehensible",p:"adj.",d:"deserving rebuke"},
{w:"reprieve",p:"n.",d:"temporary delay of punishment"},
{w:"reproach",p:"v.",d:"to scold, disapprove"},
{w:"reprobate",p:"adj.",d:"evil, unprincipled"},
{w:"reprove",p:"v.",d:"to scold, rebuke"},
{w:"repudiate",p:"v.",d:"to reject, refuse"},
{w:"repulse",p:"v.",d:"to disgust; to push back"},
{w:"reputable",p:"adj.",d:"of good reputation"},
{w:"requisition",p:"n.",d:"demand for goods"},
{w:"rescind",p:"v.",d:"to take back, repeal"},
{w:"reservoir",p:"n.",d:"reserves; body of water"},
{w:"resilient",p:"adj.",d:"able to recover"},
{w:"resolute",p:"adj.",d:"firm, determined"},
{w:"resolve",p:"v.",d:"to find solution; to firmly decide"},
{w:"respite",p:"n.",d:"a break, rest"},
{w:"resplendent",p:"adj.",d:"shiny, glowing"},
{w:"restitution",p:"n.",d:"restoration to rightful owner"},
{w:"restive",p:"adj.",d:"resistant, stubborn, impatient"},
{w:"retract",p:"v.",d:"to withdraw"},
{w:"revel",p:"v.",d:"to enjoy intensely"},
{w:"revere",p:"v.",d:"to esteem, venerate"},
{w:"revoke",p:"v.",d:"to take back"},
{w:"rhapsodize",p:"v.",d:"to engage in excessive enthusiasm"},
{w:"ribald",p:"adj.",d:"coarsely, crudely humorous"},
{w:"rife",p:"adj.",d:"abundant"},
{w:"ruminate",p:"v.",d:"to contemplate, reflect"},
{w:"ruse",p:"n.",d:"a trick"},
{w:"saccharine",p:"adj.",d:"sickeningly sweet"},
{w:"sacrosanct",p:"adj.",d:"holy, should not be criticized"},
{w:"sagacity",p:"n.",d:"shrewdness, sound perspective"},
{w:"salient",p:"adj.",d:"significant, conspicuous"},
{w:"salutation",p:"n.",d:"a greeting"},
{w:"salve",p:"n.",d:"a soothing balm"},
{w:"sanctimonious",p:"adj.",d:"hypocritical appearance of piety"},
{w:"sanguine",p:"adj.",d:"optimistic, cheery"},
{w:"satiate",p:"v.",d:"to satisfy excessively"},
{w:"scathing",p:"adj.",d:"sharp, critical, hurtful"},
{w:"scintillating",p:"adj.",d:"sparkling"},
{w:"scrupulous",p:"adj.",d:"painstaking, careful"},
{w:"scurrilous",p:"adj.",d:"vulgar, coarse"},
{w:"sedentary",p:"adj.",d:"sitting, settled"},
{w:"semaphore",p:"n.",d:"a visual signal"},
{w:"seminal",p:"adj.",d:"original, important, creating a field"},
{w:"sensual",p:"adj.",d:"sensory gratification, often sexual"},
{w:"sensuous",p:"adj.",d:"sensory gratification"},
{w:"serendipity",p:"n.",d:"luck, finding good things without looking"},
{w:"serene",p:"adj.",d:"calm, untroubled"},
{w:"servile",p:"adj.",d:"subservient"},
{w:"sinuous",p:"adj.",d:"lithe, serpentine"},
{w:"sobriety",p:"n.",d:"sedate, calm"},
{w:"solicitous",p:"adj.",d:"concerned, attentive"},
{w:"solipsistic",p:"adj.",d:"believing only oneself exists"},
{w:"soluble",p:"adj.",d:"able to dissolve"},
{w:"solvent",p:"adj.",d:"substance that dissolves; able to pay debts"},
{w:"somnolent",p:"adj.",d:"sleepy, drowsy"},
{w:"sophomoric",p:"adj.",d:"immature, uninformed"},
{w:"sovereign",p:"adj.",d:"having absolute authority"},
{w:"speculative",p:"adj.",d:"not based in fact"},
{w:"spurious",p:"adj.",d:"false but designed to seem plausible"},
{w:"stagnate",p:"v.",d:"to become inactive"},
{w:"staid",p:"adj.",d:"sedate, serious"},
{w:"stingy",p:"adj.",d:"not generous"},
{w:"stoic",p:"adj.",d:"unaffected by passion or feeling"},
{w:"stolid",p:"adj.",d:"expressing little sensibility"},
{w:"strenuous",p:"adj.",d:"requiring tremendous energy"},
{w:"strident",p:"adj.",d:"harsh, loud"},
{w:"stupefy",p:"v.",d:"to astonish, make insensible"},
{w:"subjugate",p:"v.",d:"to bring under control"},
{w:"sublime",p:"adj.",d:"lofty, grand"},
{w:"submissive",p:"adj.",d:"easily yielding"},
{w:"succinct",p:"adj.",d:"compact precision"},
{w:"superfluous",p:"adj.",d:"exceeding what is necessary"},
{w:"surfeit",p:"n.",d:"overabundant supply"},
{w:"surmise",p:"v.",d:"to infer with little evidence"},
{w:"surreptitious",p:"adj.",d:"stealthy"},
{w:"surrogate",p:"n.",d:"one acting in place of another"},
{w:"swarthy",p:"adj.",d:"dark complexion"},
{w:"sycophancy",p:"n.",d:"obsequious behavior; excessive flattery for self-gain"},
{w:"sycophant",p:"n.",d:"one who flatters for self-gain"},
{w:"tacit",p:"adj.",d:"expressed without words"},
{w:"taciturn",p:"adj.",d:"not inclined to talk"},
{w:"tangential",p:"adj.",d:"incidental, peripheral"},
{w:"tantamount",p:"adj.",d:"equivalent in value or significance"},
{w:"tedious",p:"adj.",d:"dull, boring"},
{w:"temerity",p:"n.",d:"audacity, recklessness"},
{w:"temperance",p:"n.",d:"moderation"},
{w:"tenable",p:"adj.",d:"able to be defended"},
{w:"tenuous",p:"adj.",d:"having little substance or strength"},
{w:"terrestrial",p:"adj.",d:"relating to land"},
{w:"timorous",p:"adj.",d:"timid, fearful"},
{w:"tirade",p:"n.",d:"long speech with harsh language"},
{w:"toady",p:"n.",d:"one who flatters for favors"},
{w:"tome",p:"n.",d:"a large book"},
{w:"torpid",p:"adj.",d:"lethargic, dormant"},
{w:"torrid",p:"adj.",d:"intense heat, passionate"},
{w:"tortuous",p:"adj.",d:"winding"},
{w:"tractable",p:"adj.",d:"easily controlled"},
{w:"tranquil",p:"adj.",d:"calm"},
{w:"transgress",p:"v.",d:"to violate, go over limit"},
{w:"transient",p:"adj.",d:"passing through briefly"},
{w:"transmute",p:"v.",d:"to change or alter form"},
{w:"travesty",p:"n.",d:"grossly inferior imitation"},
{w:"tremulous",p:"adj.",d:"fearful"},
{w:"trenchant",p:"adj.",d:"effective, articulate, clear-cut"},
{w:"trepidation",p:"n.",d:"fear, apprehension"},
{w:"trite",p:"adj.",d:"not original, overused"},
{w:"truculent",p:"adj.",d:"ready to fight, cruel"},
{w:"truncate",p:"v.",d:"to shorten by cutting off"},
{w:"turgid",p:"adj.",d:"swollen, excessively embellished"},
{w:"turpitude",p:"n.",d:"depravity, moral corruption"},
{w:"ubiquitous",p:"adj.",d:"existing everywhere"},
{w:"umbrage",p:"n.",d:"resentment, offense"},
{w:"uncanny",p:"adj.",d:"supernatural character"},
{w:"unctuous",p:"adj.",d:"smooth or greasy in manner"},
{w:"undulate",p:"v.",d:"to move in waves"},
{w:"upbraid",p:"v.",d:"to criticize or scold severely"},
{w:"usurp",p:"v.",d:"to seize by force"},
{w:"utilitarian",p:"adj.",d:"relating to usefulness"},
{w:"utopia",p:"n.",d:"imaginary place of perfection"},
{w:"vacillate",p:"v.",d:"to fluctuate, hesitate"},
{w:"vacuous",p:"adj.",d:"lack of content or ideas, stupid"},
{w:"validate",p:"v.",d:"to confirm, support"},
{w:"vapid",p:"adj.",d:"lacking liveliness, dull"},
{w:"variegated",p:"adj.",d:"diversified, distinctly marked"},
{w:"vehemently",p:"adv.",d:"marked by intense force or emotion"},
{w:"veneer",p:"n.",d:"superficial or deceptive appearance"},
{w:"venerable",p:"adj.",d:"deserving respect due to age or achievement"},
{w:"venerate",p:"v.",d:"to regard with respect"},
{w:"veracity",p:"n.",d:"conformity to facts; accuracy"},
{w:"verbose",p:"adj.",d:"wordy"},
{w:"verdant",p:"adj.",d:"green"},
{w:"vestige",p:"n.",d:"mark or trace of something lost"},
{w:"vex",p:"v.",d:"to confuse or annoy"},
{w:"vicarious",p:"adj.",d:"experiencing through another"},
{w:"vicissitude",p:"n.",d:"event occurring by chance"},
{w:"vigilant",p:"adj.",d:"watchful, alert"},
{w:"vilify",p:"v.",d:"to lower importance, defame"},
{w:"vindicate",p:"v.",d:"to avenge; free from allegation"},
{w:"vindictive",p:"adj.",d:"vengeful"},
{w:"virtuoso",p:"n.",d:"one who excels in an art"},
{w:"viscous",p:"adj.",d:"not free flowing, syrupy"},
{w:"vitriolic",p:"adj.",d:"having caustic quality"},
{w:"vituperate",p:"v.",d:"to berate"},
{w:"vivacious",p:"adj.",d:"lively, sprightly"},
{w:"vocation",p:"n.",d:"profession"},
{w:"vociferous",p:"adj.",d:"loud, boisterous"},
{w:"wallow",p:"v.",d:"to roll indolently; remain helpless"},
{w:"wane",p:"v.",d:"to decrease, dwindle"},
{w:"wanton",p:"adj.",d:"undisciplined, lewd"},
{w:"whimsical",p:"adj.",d:"fanciful, full of whims"},
{w:"wily",p:"adj.",d:"crafty, sly"},
{w:"winsome",p:"adj.",d:"charming, pleasing"},
{w:"wistful",p:"adj.",d:"full of yearning; musingly sad"},
{w:"wizened",p:"adj.",d:"dry, shrunken, wrinkled"},
{w:"wrath",p:"n.",d:"vengeful anger"},
{w:"yoke",p:"v.",d:"to join, link"},
{w:"zealous",p:"adj.",d:"fervent, filled with eagerness"},
{w:"zenith",p:"n.",d:"highest point"},
{w:"zephyr",p:"n.",d:"a gentle breeze"}
];
