const W=[
{w:"abase",p:"v.",d:"to humiliate, degrade",diff:"hard"},
{w:"abate",p:"v.",d:"to reduce, lessen",diff:"medium"},
{w:"abdicate",p:"v.",d:"to give up a position, usually leadership",diff:"medium"},
{w:"abduct",p:"v.",d:"to kidnap, take by force",diff:"medium"},
{w:"aberration",p:"n.",d:"something that differs from the norm",diff:"medium"},
{w:"abet",p:"v.",d:"to aid, help, encourage",diff:"medium"},
{w:"abhor",p:"v.",d:"to hate, detest",diff:"medium"},
{w:"abide",p:"v.",d:"to put up with; to remain",diff:"easy"},
{w:"abject",p:"adj.",d:"wretched, pitiful",diff:"medium"},
{w:"abjure",p:"v.",d:"to reject, renounce",diff:"hard"},
{w:"abnegation",p:"n.",d:"denial of comfort to oneself",diff:"hard"},
{w:"abort",p:"v.",d:"to give up on a half-finished project",diff:"easy"},
{w:"abridge",p:"v.",d:"to cut down, shorten",diff:"hard"},
{w:"abrogate",p:"v.",d:"to abolish, usually by authority",diff:"hard"},
{w:"abscond",p:"v.",d:"to sneak away and hide",diff:"hard"},
{w:"absolution",p:"n.",d:"freedom from blame, guilt, or sin",diff:"medium"},
{w:"abstain",p:"v.",d:"to freely choose not to commit an action",diff:"medium"},
{w:"abstruse",p:"adj.",d:"hard to comprehend",diff:"hard"},
{w:"accede",p:"v.",d:"to agree",diff:"medium"},
{w:"accentuate",p:"v.",d:"to stress, highlight",diff:"medium"},
{w:"accessible",p:"adj.",d:"obtainable, reachable",diff:"easy"},
{w:"acclaim",p:"n.",d:"high praise",diff:"easy"},
{w:"accolade",p:"n.",d:"high praise, special distinction",diff:"medium"},
{w:"accommodating",p:"adj.",d:"helpful, obliging, polite",diff:"easy"},
{w:"accord",p:"n.",d:"an agreement",diff:"easy"},
{w:"accost",p:"v.",d:"to confront verbally",diff:"hard"},
{w:"accretion",p:"n.",d:"slow growth in size or amount",diff:"medium"},
{w:"acerbic",p:"adj.",d:"biting, bitter in tone or taste",diff:"hard"},
{w:"acquiesce",p:"v.",d:"to agree without protesting",diff:"medium"},
{w:"acrimony",p:"n.",d:"bitterness, discord",diff:"hard"},
{w:"acumen",p:"n.",d:"keen insight",diff:"medium"},
{w:"acute",p:"adj.",d:"sharp or severe; having keen insight",diff:"easy"},
{w:"adamant",p:"adj.",d:"impervious, unyielding",diff:"easy"},
{w:"adept",p:"adj.",d:"extremely skilled",diff:"easy"},
{w:"adhere",p:"v.",d:"to stick to; to follow devoutly",diff:"easy"},
{w:"admonish",p:"v.",d:"to caution, criticize, reprove",diff:"hard"},
{w:"adorn",p:"v.",d:"to decorate",diff:"medium"},
{w:"adroit",p:"adj.",d:"skillful, dexterous",diff:"hard"},
{w:"adulation",p:"n.",d:"extreme praise",diff:"medium"},
{w:"adumbrate",p:"v.",d:"to sketch out vaguely",diff:"hard"},
{w:"adverse",p:"adj.",d:"antagonistic, unfavorable, dangerous",diff:"easy"},
{w:"advocate",p:"v.",d:"to argue for; a person who argues for",diff:"easy"},
{w:"aerial",p:"adj.",d:"related to the air",diff:"easy"},
{w:"aesthetic",p:"adj.",d:"artistic, related to beauty",diff:"easy"},
{w:"affable",p:"adj.",d:"friendly, amiable",diff:"medium"},
{w:"affinity",p:"n.",d:"a spontaneous feeling of closeness",diff:"easy"},
{w:"affluent",p:"adj.",d:"rich, wealthy",diff:"easy"},
{w:"affront",p:"n.",d:"an insult",diff:"medium"},
{w:"aggrandize",p:"v.",d:"to increase or make greater",diff:"hard"},
{w:"aggregate",p:"n.",d:"a whole or total; to gather into a mass",diff:"easy"},
{w:"aggrieved",p:"adj.",d:"distressed, wronged",diff:"medium"},
{w:"agile",p:"adj.",d:"quick, nimble",diff:"easy"},
{w:"agnostic",p:"adj.",d:"believing God's existence cannot be proven",diff:"medium"},
{w:"agriculture",p:"n.",d:"farming",diff:"easy"},
{w:"aisle",p:"n.",d:"a passageway between rows",diff:"easy"},
{w:"alacrity",p:"n.",d:"eagerness, speed",diff:"hard"},
{w:"alias",p:"n.",d:"a false name or identity",diff:"easy"},
{w:"allay",p:"v.",d:"to soothe, ease",diff:"medium"},
{w:"allege",p:"v.",d:"to assert, usually without proof",diff:"medium"},
{w:"alleviate",p:"v.",d:"to relieve, make bearable",diff:"easy"},
{w:"allocate",p:"v.",d:"to distribute, set aside",diff:"easy"},
{w:"aloof",p:"adj.",d:"reserved, distant",diff:"medium"},
{w:"altercation",p:"n.",d:"a dispute, fight",diff:"medium"},
{w:"altruistic",p:"adj.",d:"showing selfless concern for others",diff:"medium"},
{w:"amalgamate",p:"v.",d:"to bring together, unite",diff:"hard"},
{w:"ambiguous",p:"adj.",d:"uncertain, variably interpretable",diff:"easy"},
{w:"ambivalent",p:"adj.",d:"having opposing feelings",diff:"medium"},
{w:"ameliorate",p:"v.",d:"to improve",diff:"medium"},
{w:"amenable",p:"adj.",d:"willing, compliant",diff:"medium"},
{w:"amenity",p:"n.",d:"an item that increases comfort",diff:"medium"},
{w:"amiable",p:"adj.",d:"friendly",diff:"medium"},
{w:"amicable",p:"adj.",d:"friendly, often regarding agreements",diff:"medium"},
{w:"amorous",p:"adj.",d:"showing love",diff:"medium"},
{w:"amorphous",p:"adj.",d:"without definite shape or type",diff:"medium"},
{w:"anachronistic",p:"adj.",d:"out of correct chronological order",diff:"medium"},
{w:"analgesic",p:"n.",d:"something that reduces pain",diff:"medium"},
{w:"analogous",p:"adj.",d:"similar to",diff:"easy"},
{w:"anarchist",p:"n.",d:"one who wants to eliminate all government",diff:"easy"},
{w:"anathema",p:"n.",d:"a cursed, detested person",diff:"medium"},
{w:"anecdote",p:"n.",d:"a short, humorous account",diff:"easy"},
{w:"anesthesia",p:"n.",d:"loss of sensation",diff:"easy"},
{w:"anguish",p:"n.",d:"extreme sadness, torment",diff:"easy"},
{w:"animated",p:"adj.",d:"lively",diff:"easy"},
{w:"annex",p:"v.",d:"to incorporate territory",diff:"easy"},
{w:"annul",p:"v.",d:"to make void or invalid",diff:"medium"},
{w:"anomaly",p:"n.",d:"something that doesn't fit the normal order",diff:"easy"},
{w:"anonymous",p:"adj.",d:"unknown, unrecognized",diff:"easy"},
{w:"antagonism",p:"n.",d:"hostility",diff:"medium"},
{w:"antecedent",p:"n.",d:"something that came before",diff:"medium"},
{w:"antediluvian",p:"adj.",d:"ancient",diff:"hard"},
{w:"anthology",p:"n.",d:"a selected collection of writings",diff:"easy"},
{w:"antipathy",p:"n.",d:"a strong dislike, repugnance",diff:"medium"},
{w:"antiquated",p:"adj.",d:"old, out of date",diff:"medium"},
{w:"antiseptic",p:"adj.",d:"clean, sterile",diff:"medium"},
{w:"antithesis",p:"n.",d:"the absolute opposite",diff:"medium"},
{w:"anxiety",p:"n.",d:"intense uneasiness",diff:"easy"},
{w:"apathetic",p:"adj.",d:"lacking concern or emotion",diff:"medium"},
{w:"apocryphal",p:"adj.",d:"fictitious, false",diff:"medium"},
{w:"appalling",p:"adj.",d:"inspiring shock, horror, or disgust",diff:"easy"},
{w:"appease",p:"v.",d:"to calm, satisfy",diff:"easy"},
{w:"appraise",p:"v.",d:"to assess worth or value",diff:"medium"},
{w:"apprehend",p:"v.",d:"to seize or arrest; to perceive or understand",diff:"medium"},
{w:"approbation",p:"n.",d:"praise",diff:"hard"},
{w:"appropriate",p:"v.",d:"to take, make use of",diff:"easy"},
{w:"aquatic",p:"adj.",d:"relating to water",diff:"easy"},
{w:"arable",p:"adj.",d:"suitable for growing crops",diff:"medium"},
{w:"arbiter",p:"n.",d:"one who resolves a dispute",diff:"medium"},
{w:"arbitrary",p:"adj.",d:"based on random factors",diff:"easy"},
{w:"arbitration",p:"n.",d:"process of resolving a dispute",diff:"easy"},
{w:"arboreal",p:"adj.",d:"relating to trees",diff:"hard"},
{w:"arcane",p:"adj.",d:"obscure, secret, known by few",diff:"medium"},
{w:"archaic",p:"adj.",d:"outdated, from an earlier period",diff:"easy"},
{w:"archetypal",p:"adj.",d:"the most representative example",diff:"medium"},
{w:"ardor",p:"n.",d:"extreme vigor or enthusiasm",diff:"hard"},
{w:"arid",p:"adj.",d:"excessively dry",diff:"easy"},
{w:"arrogate",p:"v.",d:"to take without justification",diff:"hard"},
{w:"artifact",p:"n.",d:"a remaining piece from an extinct culture",diff:"easy"},
{w:"artisan",p:"n.",d:"a craftsman",diff:"easy"},
{w:"ascertain",p:"v.",d:"to perceive, learn",diff:"easy"},
{w:"ascetic",p:"adj.",d:"practicing restraint or self-discipline",diff:"medium"},
{w:"ascribe",p:"v.",d:"to assign, credit, attribute",diff:"medium"},
{w:"aspersion",p:"n.",d:"a curse, expression of ill-will",diff:"hard"},
{w:"aspire",p:"v.",d:"to long for, aim toward",diff:"easy"},
{w:"assail",p:"v.",d:"to attack",diff:"hard"},
{w:"assess",p:"v.",d:"to evaluate",diff:"easy"},
{w:"assiduous",p:"adj.",d:"hard-working, diligent",diff:"hard"},
{w:"assuage",p:"v.",d:"to ease, pacify",diff:"medium"},
{w:"astute",p:"adj.",d:"very clever, crafty",diff:"medium"},
{w:"asylum",p:"n.",d:"a place of refuge",diff:"easy"},
{w:"atone",p:"v.",d:"to repent, make amends",diff:"medium"},
{w:"atrophy",p:"v.",d:"to wither away, decay",diff:"medium"},
{w:"attain",p:"v.",d:"to achieve, arrive at",diff:"easy"},
{w:"attribute",p:"v.",d:"to credit or assign; a facet or trait",diff:"easy"},
{w:"atypical",p:"adj.",d:"not typical, unusual",diff:"medium"},
{w:"audacious",p:"adj.",d:"excessively bold",diff:"medium"},
{w:"audible",p:"adj.",d:"able to be heard",diff:"easy"},
{w:"augment",p:"v.",d:"to add to, expand",diff:"medium"},
{w:"auspicious",p:"adj.",d:"favorable, indicative of good things",diff:"medium"},
{w:"austere",p:"adj.",d:"very bare, bleak",diff:"medium"},
{w:"avarice",p:"n.",d:"excessive greed",diff:"medium"},
{w:"avenge",p:"v.",d:"to seek revenge",diff:"easy"},
{w:"aversion",p:"n.",d:"a particular dislike",diff:"easy"},
{w:"balk",p:"v.",d:"to stop, block abruptly",diff:"medium"},
{w:"ballad",p:"n.",d:"a love song",diff:"easy"},
{w:"banal",p:"adj.",d:"dull, commonplace",diff:"medium"},
{w:"bane",p:"n.",d:"a burden",diff:"easy"},
{w:"bard",p:"n.",d:"a poet or singer",diff:"easy"},
{w:"bashful",p:"adj.",d:"shy, excessively timid",diff:"medium"},
{w:"battery",p:"n.",d:"a power device; assault or beating",diff:"easy"},
{w:"beguile",p:"v.",d:"to trick, deceive",diff:"hard"},
{w:"behemoth",p:"n.",d:"something of tremendous power or size",diff:"medium"},
{w:"benevolent",p:"adj.",d:"marked by goodness",diff:"easy"},
{w:"benign",p:"adj.",d:"favorable, not threatening, mild",diff:"easy"},
{w:"bequeath",p:"v.",d:"to pass on, give",diff:"medium"},
{w:"berate",p:"v.",d:"to scold vehemently",diff:"medium"},
{w:"bereft",p:"adj.",d:"devoid of, without",diff:"medium"},
{w:"beseech",p:"v.",d:"to beg, plead",diff:"medium"},
{w:"bias",p:"n.",d:"a tendency, prejudice",diff:"easy"},
{w:"bilk",p:"v.",d:"to cheat, defraud",diff:"hard"},
{w:"blandish",p:"v.",d:"to coax using flattery",diff:"hard"},
{w:"blemish",p:"n.",d:"an imperfection, flaw",diff:"medium"},
{w:"blight",p:"n.",d:"a plague or disease; something destroying hope",diff:"easy"},
{w:"boisterous",p:"adj.",d:"loud, full of energy",diff:"medium"},
{w:"bombastic",p:"adj.",d:"excessively confident, pompous",diff:"medium"},
{w:"boon",p:"n.",d:"a gift or blessing",diff:"easy"},
{w:"bourgeois",p:"n.",d:"a middle-class person or capitalist",diff:"easy"},
{w:"brazen",p:"adj.",d:"excessively bold, brash",diff:"medium"},
{w:"brusque",p:"adj.",d:"short, abrupt, dismissive",diff:"hard"},
{w:"buffet",p:"v.",d:"to strike with force",diff:"easy"},
{w:"burnish",p:"v.",d:"to polish, shine",diff:"hard"},
{w:"buttress",p:"v.",d:"to support; something offering support",diff:"medium"},
{w:"cacophonous",p:"adj.",d:"having a harsh, discordant mixture of sounds",diff:"hard"},
{w:"cacophony",p:"n.",d:"tremendous noise, disharmonious sound",diff:"medium"},
{w:"cadence",p:"n.",d:"a rhythm, progression of sound",diff:"medium"},
{w:"cajole",p:"v.",d:"to urge, coax",diff:"hard"},
{w:"calamity",p:"n.",d:"an event with disastrous consequences",diff:"easy"},
{w:"calibrate",p:"v.",d:"to set, standardize",diff:"medium"},
{w:"callous",p:"adj.",d:"harsh, cold, unfeeling",diff:"medium"},
{w:"calumny",p:"n.",d:"spreading lies to spoil reputation",diff:"hard"},
{w:"camaraderie",p:"n.",d:"brotherhood, jovial unity",diff:"medium"},
{w:"candor",p:"n.",d:"honesty, frankness",diff:"medium"},
{w:"canny",p:"adj.",d:"shrewd, careful",diff:"medium"},
{w:"canvas",p:"n.",d:"cloth for painting; to cover or inspect",diff:"easy"},
{w:"capacious",p:"adj.",d:"very spacious",diff:"hard"},
{w:"capitulate",p:"v.",d:"to surrender",diff:"medium"},
{w:"capricious",p:"adj.",d:"subject to whim, fickle",diff:"medium"},
{w:"captivate",p:"v.",d:"to hold attention",diff:"medium"},
{w:"carouse",p:"v.",d:"to party, celebrate",diff:"hard"},
{w:"carp",p:"v.",d:"to annoy, pester",diff:"medium"},
{w:"catalog",p:"v.",d:"to list; a list or collection",diff:"easy"},
{w:"catalyze",p:"v.",d:"to charge, inspire",diff:"medium"},
{w:"caucus",p:"n.",d:"a meeting for a common goal",diff:"easy"},
{w:"caustic",p:"adj.",d:"bitter, biting, acidic",diff:"medium"},
{w:"cavort",p:"v.",d:"to leap about, behave boisterously",diff:"hard"},
{w:"censure",p:"n.",d:"harsh criticism; to rebuke formally",diff:"medium"},
{w:"cerebral",p:"adj.",d:"related to the intellect",diff:"easy"},
{w:"chaos",p:"n.",d:"absolute disorder",diff:"easy"},
{w:"chastise",p:"v.",d:"to criticize severely",diff:"medium"},
{w:"cherish",p:"v.",d:"to feel or show affection",diff:"easy"},
{w:"chide",p:"v.",d:"to voice disapproval",diff:"hard"},
{w:"choreography",p:"n.",d:"arrangement of dances",diff:"easy"},
{w:"chronicle",p:"n.",d:"a written history; to write history",diff:"easy"},
{w:"chronological",p:"adj.",d:"arranged in time order",diff:"easy"},
{w:"circuitous",p:"adj.",d:"roundabout",diff:"medium"},
{w:"circumlocution",p:"n.",d:"indirect, wordy language",diff:"hard"},
{w:"circumscribed",p:"adj.",d:"marked off, bounded",diff:"medium"},
{w:"circumspect",p:"adj.",d:"cautious",diff:"medium"},
{w:"circumvent",p:"v.",d:"to get around",diff:"medium"},
{w:"clairvoyant",p:"adj.",d:"able to perceive things others cannot",diff:"medium"},
{w:"clamor",p:"n.",d:"loud noise; to loudly insist",diff:"medium"},
{w:"clandestine",p:"adj.",d:"secret",diff:"easy"},
{w:"cleave",p:"v.",d:"to divide; to stick together firmly",diff:"medium"},
{w:"clemency",p:"n.",d:"mercy",diff:"medium"},
{w:"clergy",p:"n.",d:"members of holy orders",diff:"easy"},
{w:"cloying",p:"adj.",d:"sickeningly sweet",diff:"hard"},
{w:"coagulate",p:"v.",d:"to thicken, clot",diff:"hard"},
{w:"coalesce",p:"v.",d:"to fuse into a whole",diff:"medium"},
{w:"cobbler",p:"n.",d:"a shoe repairer",diff:"medium"},
{w:"coerce",p:"v.",d:"to force by threat",diff:"medium"},
{w:"cogent",p:"adj.",d:"intellectually convincing",diff:"medium"},
{w:"cognizant",p:"adj.",d:"aware, mindful",diff:"medium"},
{w:"coherent",p:"adj.",d:"logically consistent",diff:"easy"},
{w:"collateral",p:"adj.",d:"secondary; security for a debt",diff:"easy"},
{w:"colloquial",p:"adj.",d:"characteristic of informal conversation",diff:"medium"},
{w:"collusion",p:"n.",d:"secret agreement, conspiracy",diff:"easy"},
{w:"colossus",p:"n.",d:"a gigantic statue or thing",diff:"medium"},
{w:"combustion",p:"n.",d:"the act of burning",diff:"easy"},
{w:"commendation",p:"n.",d:"notice of approval",diff:"medium"},
{w:"commensurate",p:"adj.",d:"corresponding in size or amount",diff:"medium"},
{w:"commodious",p:"adj.",d:"roomy",diff:"hard"},
{w:"compelling",p:"adj.",d:"forceful, demanding attention",diff:"easy"},
{w:"compensate",p:"v.",d:"to make appropriate payment",diff:"easy"},
{w:"complacency",p:"n.",d:"self-satisfied ignorance of danger",diff:"medium"},
{w:"complement",p:"v.",d:"to complete, make perfect",diff:"easy"},
{w:"compliant",p:"adj.",d:"ready to adapt to wishes",diff:"easy"},
{w:"complicit",p:"adj.",d:"being an accomplice",diff:"medium"},
{w:"compliment",p:"n.",d:"expression of esteem",diff:"easy"},
{w:"compound",p:"v.",d:"to combine; a combination",diff:"easy"},
{w:"comprehensive",p:"adj.",d:"including everything",diff:"easy"},
{w:"compress",p:"v.",d:"to apply pressure, squeeze",diff:"medium"},
{w:"compunction",p:"n.",d:"distress from guilt",diff:"hard"},
{w:"concede",p:"v.",d:"to accept as valid",diff:"easy"},
{w:"conciliatory",p:"adj.",d:"friendly, agreeable",diff:"medium"},
{w:"concise",p:"adj.",d:"brief, direct",diff:"easy"},
{w:"concoct",p:"v.",d:"to fabricate, make up",diff:"medium"},
{w:"concomitant",p:"adj.",d:"accompanying in a subordinate fashion",diff:"medium"},
{w:"concord",p:"n.",d:"harmonious agreement",diff:"easy"},
{w:"condolence",p:"n.",d:"expression of sympathy",diff:"medium"},
{w:"condone",p:"v.",d:"to pardon, overlook",diff:"medium"},
{w:"conduit",p:"n.",d:"a pipe or channel",diff:"easy"},
{w:"confection",p:"n.",d:"a sweet, fancy food",diff:"medium"},
{w:"confidant",p:"n.",d:"a person entrusted with secrets",diff:"medium"},
{w:"conflagration",p:"n.",d:"great fire",diff:"medium"},
{w:"confluence",p:"n.",d:"a gathering together",diff:"medium"},
{w:"conformist",p:"n.",d:"one who behaves like others",diff:"medium"},
{w:"confound",p:"v.",d:"to frustrate, confuse",diff:"medium"},
{w:"congeal",p:"v.",d:"to thicken into a solid",diff:"hard"},
{w:"congenial",p:"adj.",d:"pleasantly agreeable",diff:"medium"},
{w:"congregation",p:"n.",d:"a gathering, usually religious",diff:"easy"},
{w:"congruity",p:"n.",d:"quality of being in agreement",diff:"hard"},
{w:"connive",p:"v.",d:"to plot, scheme",diff:"hard"},
{w:"consecrate",p:"v.",d:"to dedicate to a holy purpose",diff:"medium"},
{w:"consensus",p:"n.",d:"an agreement of opinion",diff:"easy"},
{w:"consign",p:"v.",d:"to give over to another's care",diff:"medium"},
{w:"consolation",p:"n.",d:"an act of comforting",diff:"easy"},
{w:"consonant",p:"adj.",d:"in harmony",diff:"medium"},
{w:"constituent",p:"n.",d:"an essential part",diff:"easy"},
{w:"constrain",p:"v.",d:"to forcibly restrict",diff:"medium"},
{w:"construe",p:"v.",d:"to interpret",diff:"hard"},
{w:"consummate",p:"v.",d:"to complete a deal or marriage",diff:"medium"},
{w:"consumption",p:"n.",d:"the act of consuming",diff:"easy"},
{w:"contemporaneous",p:"adj.",d:"existing during the same time",diff:"medium"},
{w:"contentious",p:"adj.",d:"tending to quarrel",diff:"easy"},
{w:"contravene",p:"v.",d:"to contradict, violate",diff:"hard"},
{w:"contrite",p:"adj.",d:"penitent, eager to be forgiven",diff:"medium"},
{w:"contusion",p:"n.",d:"bruise, injury",diff:"medium"},
{w:"conundrum",p:"n.",d:"puzzle, problem",diff:"medium"},
{w:"convene",p:"v.",d:"to call together",diff:"medium"},
{w:"convention",p:"n.",d:"an assembly; a rule or custom",diff:"easy"},
{w:"convivial",p:"adj.",d:"characterized by feasting or merriment",diff:"hard"},
{w:"convoluted",p:"adj.",d:"intricate, complicated",diff:"medium"},
{w:"copious",p:"adj.",d:"profuse, abundant",diff:"medium"},
{w:"cordial",p:"adj.",d:"warm, affectionate",diff:"medium"},
{w:"coronation",p:"n.",d:"the act of crowning",diff:"easy"},
{w:"corpulence",p:"n.",d:"extreme fatness",diff:"hard"},
{w:"corroborate",p:"v.",d:"to support with evidence",diff:"medium"},
{w:"corrosive",p:"adj.",d:"having tendency to erode",diff:"medium"},
{w:"cosmopolitan",p:"adj.",d:"sophisticated, worldly",diff:"easy"},
{w:"counteract",p:"v.",d:"to neutralize",diff:"medium"},
{w:"coup",p:"n.",d:"a brilliant act; overthrow of government",diff:"easy"},
{w:"covert",p:"adj.",d:"secretly engaged in",diff:"easy"},
{w:"covet",p:"v.",d:"to desire enviously",diff:"medium"},
{w:"credulity",p:"n.",d:"readiness to believe",diff:"hard"},
{w:"crescendo",p:"n.",d:"steady increase in intensity",diff:"medium"},
{w:"criteria",p:"n.",d:"standards for judgment",diff:"easy"},
{w:"culmination",p:"n.",d:"the climax",diff:"easy"},
{w:"culpable",p:"adj.",d:"deserving blame",diff:"medium"},
{w:"cultivate",p:"v.",d:"to nurture, improve",diff:"easy"},
{w:"cumulative",p:"adj.",d:"increasing, building upon itself",diff:"easy"},
{w:"cunning",p:"adj.",d:"sly, clever at deceit",diff:"easy"},
{w:"cupidity",p:"n.",d:"greed, strong desire",diff:"hard"},
{w:"cursory",p:"adj.",d:"brief, superficial",diff:"medium"},
{w:"curt",p:"adj.",d:"abruptly or rudely short",diff:"medium"},
{w:"curtail",p:"v.",d:"to lessen, reduce",diff:"medium"},
{w:"daunting",p:"adj.",d:"intimidating",diff:"easy"},
{w:"dearth",p:"n.",d:"a lack, scarcity",diff:"medium"},
{w:"debacle",p:"n.",d:"a disastrous failure",diff:"easy"},
{w:"debase",p:"v.",d:"to lower quality or esteem",diff:"hard"},
{w:"debauch",p:"v.",d:"to corrupt via sensual pleasures",diff:"hard"},
{w:"debunk",p:"v.",d:"to expose falseness",diff:"medium"},
{w:"decorous",p:"adj.",d:"socially proper",diff:"hard"},
{w:"decry",p:"v.",d:"to criticize openly",diff:"medium"},
{w:"deface",p:"v.",d:"to ruin appearance",diff:"hard"},
{w:"defamatory",p:"adj.",d:"harmful to reputation",diff:"medium"},
{w:"defer",p:"v.",d:"to postpone; to yield to wisdom",diff:"easy"},
{w:"deferential",p:"adj.",d:"showing respect for authority",diff:"hard"},
{w:"defile",p:"v.",d:"to make unclean or impure",diff:"medium"},
{w:"deft",p:"adj.",d:"skillful, capable",diff:"medium"},
{w:"defunct",p:"adj.",d:"no longer used or existing",diff:"easy"},
{w:"delegate",p:"v.",d:"to hand over responsibility",diff:"easy"},
{w:"deleterious",p:"adj.",d:"harmful",diff:"medium"},
{w:"deliberate",p:"adj.",d:"intentional, careful",diff:"easy"},
{w:"delineate",p:"v.",d:"to describe, outline",diff:"medium"},
{w:"demagogue",p:"n.",d:"leader appealing to prejudices",diff:"medium"},
{w:"demarcation",p:"n.",d:"marking of boundaries",diff:"medium"},
{w:"demean",p:"v.",d:"to lower status or stature",diff:"medium"},
{w:"demure",p:"adj.",d:"quiet, modest, reserved",diff:"medium"},
{w:"denigrate",p:"v.",d:"to belittle",diff:"medium"},
{w:"denounce",p:"v.",d:"to criticize publicly",diff:"easy"},
{w:"deplore",p:"v.",d:"to feel sorrow or disapproval",diff:"medium"},
{w:"depravity",p:"n.",d:"wickedness",diff:"medium"},
{w:"deprecate",p:"v.",d:"to belittle, depreciate",diff:"hard"},
{w:"derelict",p:"adj.",d:"abandoned, run-down",diff:"medium"},
{w:"deride",p:"v.",d:"to laugh at mockingly",diff:"medium"},
{w:"derivative",p:"adj.",d:"taken from a source, unoriginal",diff:"easy"},
{w:"desecrate",p:"v.",d:"to violate sacredness",diff:"hard"},
{w:"desiccated",p:"adj.",d:"dried up, dehydrated",diff:"hard"},
{w:"desolate",p:"adj.",d:"deserted, dreary",diff:"medium"},
{w:"despondent",p:"adj.",d:"depressed, hopeless",diff:"medium"},
{w:"despot",p:"n.",d:"one with total brutal power",diff:"medium"},
{w:"destitute",p:"adj.",d:"impoverished",diff:"medium"},
{w:"deter",p:"v.",d:"to discourage, prevent",diff:"easy"},
{w:"devious",p:"adj.",d:"not straightforward, deceitful",diff:"medium"},
{w:"dialect",p:"n.",d:"a variation of a language",diff:"easy"},
{w:"diaphanous",p:"adj.",d:"light, airy, transparent",diff:"hard"},
{w:"didactic",p:"adj.",d:"intended to instruct; overly moralistic",diff:"medium"},
{w:"didacticism",p:"n.",d:"the quality of being overly moralistic or instructional",diff:"hard"},
{w:"diffident",p:"adj.",d:"shy, quiet, modest",diff:"hard"},
{w:"diffuse",p:"v.",d:"to scatter; not concentrated",diff:"easy"},
{w:"dilatory",p:"adj.",d:"tending to delay",diff:"hard"},
{w:"diligent",p:"adj.",d:"showing care in work",diff:"easy"},
{w:"diminutive",p:"adj.",d:"small, miniature",diff:"medium"},
{w:"dirge",p:"n.",d:"a mournful song",diff:"hard"},
{w:"disaffected",p:"adj.",d:"rebellious, resentful",diff:"medium"},
{w:"disavow",p:"v.",d:"to deny knowledge or responsibility",diff:"medium"},
{w:"discern",p:"v.",d:"to perceive, detect",diff:"easy"},
{w:"disclose",p:"v.",d:"to reveal",diff:"easy"},
{w:"discomfit",p:"v.",d:"to thwart, baffle",diff:"hard"},
{w:"discordant",p:"adj.",d:"not in harmony",diff:"medium"},
{w:"discrepancy",p:"n.",d:"difference, failure to correspond",diff:"easy"},
{w:"discretion",p:"n.",d:"reserve in speech or action; good judgment",diff:"easy"},
{w:"discursive",p:"adj.",d:"rambling, lacking order",diff:"medium"},
{w:"disdain",p:"v.",d:"to scorn",diff:"easy"},
{w:"disgruntled",p:"adj.",d:"upset, not content",diff:"medium"},
{w:"disheartened",p:"adj.",d:"loss of spirit or morale",diff:"medium"},
{w:"disparage",p:"v.",d:"to criticize or speak ill of",diff:"medium"},
{w:"disparate",p:"adj.",d:"sharply differing",diff:"easy"},
{w:"dispatch",p:"v.",d:"to send off",diff:"easy"},
{w:"dispel",p:"v.",d:"to drive away, scatter",diff:"medium"},
{w:"disperse",p:"v.",d:"to scatter",diff:"easy"},
{w:"disrepute",p:"n.",d:"state of being held in low regard",diff:"medium"},
{w:"dissemble",p:"v.",d:"to conceal, fake",diff:"hard"},
{w:"disseminate",p:"v.",d:"to spread widely",diff:"medium"},
{w:"dissent",p:"v.",d:"to disagree",diff:"easy"},
{w:"dissipate",p:"v.",d:"to disappear; to waste",diff:"medium"},
{w:"dissonance",p:"n.",d:"lack of harmony or consistency",diff:"medium"},
{w:"dissuade",p:"v.",d:"to persuade someone not to do something",diff:"medium"},
{w:"distend",p:"v.",d:"to swell out",diff:"hard"},
{w:"dither",p:"v.",d:"to be indecisive",diff:"hard"},
{w:"divine",p:"adj.",d:"godly, wonderful",diff:"easy"},
{w:"divisive",p:"adj.",d:"causing dissent or discord",diff:"easy"},
{w:"divulge",p:"v.",d:"to reveal something secret",diff:"medium"},
{w:"docile",p:"adj.",d:"easily taught",diff:"medium"},
{w:"dogmatic",p:"adj.",d:"arrogantly certain about unproved principles",diff:"medium"},
{w:"dormant",p:"adj.",d:"sleeping, inactive",diff:"easy"},
{w:"dour",p:"adj.",d:"stern, joyless",diff:"medium"},
{w:"dubious",p:"adj.",d:"doubtful, uncertain quality",diff:"easy"},
{w:"duplicity",p:"n.",d:"crafty dishonesty",diff:"medium"},
{w:"duress",p:"n.",d:"hardship, threat",diff:"medium"},
{w:"dynamic",p:"adj.",d:"actively changing",diff:"easy"},
{w:"ebullient",p:"adj.",d:"extremely lively, enthusiastic",diff:"hard"},
{w:"eclectic",p:"adj.",d:"diverse variety of elements",diff:"easy"},
{w:"ecstatic",p:"adj.",d:"intensely happy",diff:"easy"},
{w:"edict",p:"n.",d:"an order, decree",diff:"medium"},
{w:"efface",p:"v.",d:"to wipe out, obliterate",diff:"hard"},
{w:"effervescent",p:"adj.",d:"bubbly, lively",diff:"medium"},
{w:"efficacious",p:"adj.",d:"effective",diff:"medium"},
{w:"effrontery",p:"n.",d:"impudence, nerve",diff:"hard"},
{w:"effulgent",p:"adj.",d:"radiant, splendorous",diff:"hard"},
{w:"egregious",p:"adj.",d:"extremely bad",diff:"medium"},
{w:"elaborate",p:"adj.",d:"complex, detailed",diff:"easy"},
{w:"elated",p:"adj.",d:"overjoyed, thrilled",diff:"medium"},
{w:"elegy",p:"n.",d:"speech honoring the dead",diff:"medium"},
{w:"elicit",p:"v.",d:"to bring forth, draw out",diff:"medium"},
{w:"eloquent",p:"adj.",d:"expressive, articulate",diff:"easy"},
{w:"elucidate",p:"v.",d:"to clarify, explain",diff:"medium"},
{w:"elude",p:"v.",d:"to evade, escape",diff:"medium"},
{w:"emaciated",p:"adj.",d:"very thin, enfeebled",diff:"medium"},
{w:"embellish",p:"v.",d:"to decorate; to add details",diff:"medium"},
{w:"embezzle",p:"v.",d:"to steal money by falsifying records",diff:"hard"},
{w:"emend",p:"v.",d:"to correct or revise text",diff:"hard"},
{w:"eminent",p:"adj.",d:"distinguished, famous; conspicuous",diff:"easy"},
{w:"emollient",p:"adj.",d:"soothing",diff:"hard"},
{w:"emote",p:"v.",d:"to express emotion",diff:"medium"},
{w:"empathy",p:"n.",d:"sensitivity to another's feelings",diff:"easy"},
{w:"empirical",p:"adj.",d:"based on observation or experience",diff:"easy"},
{w:"emulate",p:"v.",d:"to imitate",diff:"easy"},
{w:"enamor",p:"v.",d:"to fill with love or fascinate",diff:"hard"},
{w:"encore",p:"n.",d:"demand for repeat performance",diff:"easy"},
{w:"encumber",p:"v.",d:"to weigh down, burden",diff:"hard"},
{w:"enervate",p:"v.",d:"to weaken, exhaust",diff:"hard"},
{w:"enervating",p:"adj.",d:"causing one to feel drained of energy",diff:"hard"},
{w:"enfranchise",p:"v.",d:"to grant the vote",diff:"hard"},
{w:"engender",p:"v.",d:"to bring about, create",diff:"medium"},
{w:"enigmatic",p:"adj.",d:"mystifying, cryptic",diff:"medium"},
{w:"enmity",p:"n.",d:"ill will, hatred",diff:"medium"},
{w:"ennui",p:"n.",d:"boredom, weariness",diff:"medium"},
{w:"entail",p:"v.",d:"to include as a necessary step",diff:"easy"},
{w:"enthrall",p:"v.",d:"to charm, hold spellbound",diff:"hard"},
{w:"ephemera",p:"n.",d:"items of collectible memorabilia originally expected to have only short-term usefulness",diff:"medium"},
{w:"ephemeral",p:"adj.",d:"short-lived, fleeting",diff:"medium"},
{w:"epistolary",p:"adj.",d:"relating to letters",diff:"hard"},
{w:"epitome",p:"n.",d:"a perfect example",diff:"easy"},
{w:"equanimity",p:"n.",d:"composure",diff:"medium"},
{w:"equivocal",p:"adj.",d:"ambiguous, uncertain",diff:"hard"},
{w:"erudite",p:"adj.",d:"learned",diff:"medium"},
{w:"eschew",p:"v.",d:"to shun, avoid",diff:"medium"},
{w:"esoteric",p:"adj.",d:"understood by only a select few",diff:"medium"},
{w:"espouse",p:"v.",d:"to take up as a cause, support",diff:"medium"},
{w:"ethereal",p:"adj.",d:"heavenly, delicate",diff:"easy"},
{w:"etymology",p:"n.",d:"history or origin of words",diff:"medium"},
{w:"euphoric",p:"adj.",d:"elated, uplifted",diff:"medium"},
{w:"evanescent",p:"adj.",d:"fleeting, momentary",diff:"hard"},
{w:"evince",p:"v.",d:"to show, reveal",diff:"hard"},
{w:"exacerbate",p:"v.",d:"to make more violent or intense",diff:"medium"},
{w:"exalt",p:"v.",d:"to glorify, praise",diff:"medium"},
{w:"exasperate",p:"v.",d:"to irritate, irk",diff:"hard"},
{w:"excavate",p:"v.",d:"to dig out or remove",diff:"medium"},
{w:"exculpate",p:"v.",d:"to free from guilt or blame",diff:"hard"},
{w:"excursion",p:"n.",d:"a trip or outing",diff:"easy"},
{w:"execrable",p:"adj.",d:"loathsome, detestable",diff:"hard"},
{w:"exhort",p:"v.",d:"to urge, prod",diff:"hard"},
{w:"exigent",p:"adj.",d:"urgent, critical",diff:"hard"},
{w:"exonerate",p:"v.",d:"to free from guilt or blame",diff:"medium"},
{w:"exorbitant",p:"adj.",d:"excessive",diff:"medium"},
{w:"expedient",p:"adj.",d:"advisable, serving self-interest",diff:"medium"},
{w:"expiate",p:"v.",d:"to make amends, atone",diff:"hard"},
{w:"expunge",p:"v.",d:"to obliterate, eradicate",diff:"hard"},
{w:"expurgate",p:"v.",d:"to remove offensive parts",diff:"hard"},
{w:"extant",p:"adj.",d:"existing, not lost",diff:"easy"},
{w:"extol",p:"v.",d:"to praise, revere",diff:"hard"},
{w:"extraneous",p:"adj.",d:"irrelevant, extra",diff:"medium"},
{w:"extricate",p:"v.",d:"to disentangle",diff:"medium"},
{w:"exult",p:"v.",d:"to rejoice",diff:"hard"},
{w:"fabricate",p:"v.",d:"to make up, invent",diff:"medium"},
{w:"facade",p:"n.",d:"wall of a building; deceptive appearance",diff:"easy"},
{w:"facile",p:"adj.",d:"easy; superficial or insincere",diff:"medium"},
{w:"fallacious",p:"adj.",d:"incorrect, misleading",diff:"medium"},
{w:"fastidious",p:"adj.",d:"meticulous, demanding high standards",diff:"medium"},
{w:"fathom",p:"v.",d:"to understand, comprehend",diff:"easy"},
{w:"fatuous",p:"adj.",d:"silly, foolish",diff:"hard"},
{w:"fecund",p:"adj.",d:"fruitful, fertile",diff:"hard"},
{w:"felicitous",p:"adj.",d:"well suited or apt; delightful",diff:"hard"},
{w:"feral",p:"adj.",d:"wild, savage",diff:"easy"},
{w:"fervent",p:"adj.",d:"ardent, passionate",diff:"medium"},
{w:"fetid",p:"adj.",d:"having a foul odor",diff:"hard"},
{w:"fetter",p:"v.",d:"to chain, restrain",diff:"hard"},
{w:"fickle",p:"adj.",d:"shifting, inconstant",diff:"medium"},
{w:"fidelity",p:"n.",d:"loyalty, devotion",diff:"easy"},
{w:"figurative",p:"adj.",d:"symbolic",diff:"medium"},
{w:"flabbergasted",p:"adj.",d:"astounded",diff:"medium"},
{w:"flaccid",p:"adj.",d:"limp, not firm",diff:"medium"},
{w:"flagrant",p:"adj.",d:"offensive, egregious",diff:"medium"},
{w:"florid",p:"adj.",d:"flowery, ornate",diff:"hard"},
{w:"flout",p:"v.",d:"to disregard or disobey openly",diff:"hard"},
{w:"foil",p:"v.",d:"to thwart, defeat",diff:"easy"},
{w:"forage",p:"v.",d:"to graze, rummage for food",diff:"medium"},
{w:"forbearance",p:"n.",d:"patience, restraint",diff:"medium"},
{w:"forestall",p:"v.",d:"to prevent, thwart",diff:"medium"},
{w:"forlorn",p:"adj.",d:"lonely, abandoned, hopeless",diff:"medium"},
{w:"forsake",p:"v.",d:"to give up, renounce",diff:"medium"},
{w:"fortitude",p:"n.",d:"strength, guts",diff:"medium"},
{w:"fortuitous",p:"adj.",d:"happening by chance, lucky",diff:"medium"},
{w:"forum",p:"n.",d:"medium for discussion",diff:"easy"},
{w:"foster",p:"v.",d:"to stimulate, promote",diff:"easy"},
{w:"fractious",p:"adj.",d:"troublesome, irritable",diff:"hard"},
{w:"fraught",p:"adj.",d:"filled or accompanied with",diff:"medium"},
{w:"frenetic",p:"adj.",d:"frenzied, hectic",diff:"medium"},
{w:"frivolous",p:"adj.",d:"of little importance",diff:"easy"},
{w:"frugal",p:"adj.",d:"thrifty, economical",diff:"medium"},
{w:"furtive",p:"adj.",d:"secretive, sly",diff:"medium"},
{w:"garish",p:"adj.",d:"gaudy, in bad taste",diff:"medium"},
{w:"garrulous",p:"adj.",d:"talkative, wordy",diff:"hard"},
{w:"genial",p:"adj.",d:"friendly, affable",diff:"medium"},
{w:"gluttony",p:"n.",d:"overindulgence in food or drink",diff:"medium"},
{w:"goad",p:"v.",d:"to urge, spur",diff:"medium"},
{w:"gourmand",p:"n.",d:"someone fond of eating or drinking",diff:"hard"},
{w:"grandiloquence",p:"n.",d:"lofty, pompous language",diff:"hard"},
{w:"grandiose",p:"adj.",d:"magnificent or exaggerated scale",diff:"medium"},
{w:"grandiosity",p:"n.",d:"the quality of being grandiose",diff:"hard"},
{w:"gratuitous",p:"adj.",d:"uncalled for, unwarranted",diff:"medium"},
{w:"gregarious",p:"adj.",d:"sociable, drawn to company",diff:"medium"},
{w:"grievous",p:"adj.",d:"injurious, serious",diff:"medium"},
{w:"guile",p:"n.",d:"deceitful, cunning behavior",diff:"medium"},
{w:"hackneyed",p:"adj.",d:"unoriginal, trite",diff:"medium"},
{w:"hallowed",p:"adj.",d:"revered, consecrated",diff:"medium"},
{w:"hapless",p:"adj.",d:"unlucky",diff:"medium"},
{w:"harangue",p:"n.",d:"a ranting speech",diff:"hard"},
{w:"hardy",p:"adj.",d:"robust, capable of surviving adversity",diff:"easy"},
{w:"harrowing",p:"adj.",d:"greatly distressing",diff:"medium"},
{w:"haughty",p:"adj.",d:"disdainfully proud",diff:"medium"},
{w:"hedonist",p:"n.",d:"one who believes pleasure is primary",diff:"hard"},
{w:"hegemony",p:"n.",d:"domination over others",diff:"medium"},
{w:"heinous",p:"adj.",d:"shockingly wicked",diff:"easy"},
{w:"heterogeneous",p:"adj.",d:"varied, diverse",diff:"medium"},
{w:"hiatus",p:"n.",d:"a break or gap",diff:"easy"},
{w:"hierarchy",p:"n.",d:"system of ranked groups",diff:"easy"},
{w:"hypocrisy",p:"n.",d:"pretending to believe what one does not",diff:"easy"},
{w:"hypothetical",p:"adj.",d:"supposed true but unproven",diff:"easy"},
{w:"iconoclasm",p:"n.",d:"the action of attacking cherished beliefs",diff:"hard"},
{w:"iconoclast",p:"n.",d:"one who attacks common beliefs",diff:"hard"},
{w:"idiosyncratic",p:"adj.",d:"peculiar to one person",diff:"medium"},
{w:"idolatrous",p:"adj.",d:"excessively worshipping",diff:"hard"},
{w:"ignominious",p:"adj.",d:"humiliating, disgracing",diff:"hard"},
{w:"illicit",p:"adj.",d:"forbidden, not permitted",diff:"easy"},
{w:"immerse",p:"v.",d:"to absorb, deeply involve",diff:"medium"},
{w:"immutability",p:"n.",d:"the state of being unchangeable",diff:"hard"},
{w:"immutable",p:"adj.",d:"not changeable",diff:"medium"},
{w:"impassive",p:"adj.",d:"stoic, not susceptible to suffering",diff:"hard"},
{w:"impeccable",p:"adj.",d:"exemplary, flawless",diff:"easy"},
{w:"impecunious",p:"adj.",d:"poor",diff:"hard"},
{w:"imperative",p:"adj.",d:"necessary or pressing; a command",diff:"easy"},
{w:"imperious",p:"adj.",d:"commanding, domineering",diff:"medium"},
{w:"impertinent",p:"adj.",d:"rude, insolent",diff:"medium"},
{w:"impervious",p:"adj.",d:"impenetrable",diff:"medium"},
{w:"impetuous",p:"adj.",d:"rash, hastily done",diff:"medium"},
{w:"impinge",p:"v.",d:"to impact or affect; to encroach",diff:"hard"},
{w:"implacable",p:"adj.",d:"incapable of being appeased",diff:"medium"},
{w:"implement",p:"v.",d:"a tool; to put into effect",diff:"easy"},
{w:"implicate",p:"v.",d:"to involve in an incriminating way",diff:"medium"},
{w:"implicit",p:"adj.",d:"understood but not obvious",diff:"easy"},
{w:"impregnable",p:"adj.",d:"resistant to capture",diff:"medium"},
{w:"impudent",p:"adj.",d:"casually rude, insolent",diff:"medium"},
{w:"impute",p:"v.",d:"to ascribe, blame",diff:"hard"},
{w:"inane",p:"adj.",d:"silly, meaningless",diff:"medium"},
{w:"inarticulate",p:"adj.",d:"incapable of expressing clearly",diff:"hard"},
{w:"incarnate",p:"adj.",d:"embodied in flesh",diff:"medium"},
{w:"incendiary",p:"adj.",d:"inflammatory; an agitator",diff:"medium"},
{w:"incessant",p:"adj.",d:"unending",diff:"medium"},
{w:"inchoate",p:"adj.",d:"just begun and so not fully formed or developed",diff:"hard"},
{w:"incisive",p:"adj.",d:"clear, sharp, direct",diff:"medium"},
{w:"inclination",p:"n.",d:"a tendency, propensity",diff:"easy"},
{w:"incontrovertible",p:"adj.",d:"indisputable",diff:"medium"},
{w:"incorrigible",p:"adj.",d:"incapable of correction",diff:"medium"},
{w:"increment",p:"n.",d:"an enlargement or increase",diff:"medium"},
{w:"incumbent",p:"n.",d:"office holder; obligatory",diff:"easy"},
{w:"indefatigable",p:"adj.",d:"incapable of defeat or failure",diff:"medium"},
{w:"indigenous",p:"adj.",d:"originating in a region",diff:"easy"},
{w:"indigent",p:"adj.",d:"very poor, impoverished",diff:"medium"},
{w:"indignation",p:"n.",d:"anger sparked by injustice",diff:"medium"},
{w:"indolent",p:"adj.",d:"lazy",diff:"hard"},
{w:"indomitable",p:"adj.",d:"not capable of being conquered",diff:"medium"},
{w:"induce",p:"v.",d:"to bring about, stimulate",diff:"easy"},
{w:"ineffable",p:"adj.",d:"unspeakable",diff:"medium"},
{w:"inept",p:"adj.",d:"not suitable or capable",diff:"medium"},
{w:"inexorable",p:"adj.",d:"incapable of being persuaded",diff:"medium"},
{w:"inextricable",p:"adj.",d:"hopelessly tangled",diff:"hard"},
{w:"infamy",p:"n.",d:"notoriety, extreme ill repute",diff:"medium"},
{w:"infusion",p:"n.",d:"injection or permeation of one substance into another",diff:"easy"},
{w:"ingenious",p:"adj.",d:"clever, resourceful",diff:"easy"},
{w:"ingenuous",p:"adj.",d:"not devious; innocent, candid",diff:"hard"},
{w:"inhibit",p:"v.",d:"to prevent, restrain",diff:"easy"},
{w:"inimical",p:"adj.",d:"hostile, enemy-like",diff:"hard"},
{w:"iniquity",p:"n.",d:"wickedness, sin",diff:"medium"},
{w:"injunction",p:"n.",d:"an order of official warning",diff:"easy"},
{w:"innate",p:"adj.",d:"inborn, inherent",diff:"easy"},
{w:"innocuous",p:"adj.",d:"harmless, inoffensive",diff:"medium"},
{w:"innovate",p:"v.",d:"to do something unprecedented",diff:"medium"},
{w:"innuendo",p:"n.",d:"an insinuation",diff:"medium"},
{w:"inoculate",p:"v.",d:"to vaccinate",diff:"hard"},
{w:"inquisitor",p:"n.",d:"one who inquires hostilely",diff:"medium"},
{w:"insatiable",p:"adj.",d:"incapable of being satisfied",diff:"medium"},
{w:"insidious",p:"adj.",d:"appealing but imperceptibly harmful",diff:"easy"},
{w:"insinuate",p:"v.",d:"to suggest indirectly",diff:"medium"},
{w:"insipid",p:"adj.",d:"dull, boring",diff:"medium"},
{w:"insolent",p:"adj.",d:"rude, arrogant",diff:"medium"},
{w:"instigate",p:"v.",d:"to urge, goad",diff:"medium"},
{w:"insular",p:"adj.",d:"separated, narrow-minded",diff:"medium"},
{w:"insurgent",p:"n.",d:"one who rebels",diff:"easy"},
{w:"integral",p:"adj.",d:"necessary for completeness",diff:"easy"},
{w:"interject",p:"v.",d:"to insert between things",diff:"hard"},
{w:"interlocutor",p:"n.",d:"someone in a dialogue",diff:"hard"},
{w:"interminable",p:"adj.",d:"without possibility of end",diff:"medium"},
{w:"intimation",p:"n.",d:"an indirect suggestion",diff:"hard"},
{w:"intractable",p:"adj.",d:"difficult to manipulate",diff:"medium"},
{w:"intransigent",p:"adj.",d:"refusing to compromise",diff:"hard"},
{w:"intrepid",p:"adj.",d:"brave in face of danger",diff:"medium"},
{w:"inundate",p:"v.",d:"to flood with abundance",diff:"hard"},
{w:"inure",p:"v.",d:"to become accustomed to",diff:"hard"},
{w:"invective",p:"n.",d:"angry verbal attack",diff:"medium"},
{w:"inveterate",p:"adj.",d:"stubbornly established by habit",diff:"hard"},
{w:"inviolable",p:"adj.",d:"secure from assault",diff:"hard"},
{w:"irascible",p:"adj.",d:"easily angered",diff:"hard"},
{w:"iridescent",p:"adj.",d:"showing rainbow colors",diff:"medium"},
{w:"irreverence",p:"n.",d:"disrespect",diff:"hard"},
{w:"irrevocable",p:"adj.",d:"incapable of being taken back",diff:"medium"},
{w:"jubilant",p:"adj.",d:"extremely joyful",diff:"medium"},
{w:"judicious",p:"adj.",d:"having sound judgment",diff:"medium"},
{w:"juxtaposition",p:"n.",d:"placing two things next to each other",diff:"medium"},
{w:"knell",p:"n.",d:"solemn sound of a bell, usually death",diff:"medium"},
{w:"kudos",p:"n.",d:"praise for achievement",diff:"easy"},
{w:"laceration",p:"n.",d:"a cut, tear",diff:"medium"},
{w:"laconic",p:"adj.",d:"terse in speech or writing",diff:"hard"},
{w:"languid",p:"adj.",d:"sluggish from fatigue",diff:"medium"},
{w:"larceny",p:"n.",d:"theft by trickery",diff:"medium"},
{w:"largess",p:"n.",d:"generous giving of lavish gifts",diff:"hard"},
{w:"latent",p:"adj.",d:"hidden but capable of exposure",diff:"easy"},
{w:"laudatory",p:"adj.",d:"expressing admiration or praise",diff:"hard"},
{w:"lavish",p:"adj.",d:"given without limits",diff:"easy"},
{w:"legerdemain",p:"n.",d:"deception, sleight-of-hand",diff:"hard"},
{w:"lenient",p:"adj.",d:"demonstrating tolerance",diff:"medium"},
{w:"lethargic",p:"adj.",d:"sluggish, apathetic",diff:"medium"},
{w:"liability",p:"n.",d:"legal responsibility; a handicap or burden",diff:"easy"},
{w:"libertarian",p:"adj.",d:"advocating liberty or free will",diff:"easy"},
{w:"licentious",p:"adj.",d:"lacking moral or legal restraints",diff:"hard"},
{w:"limpid",p:"adj.",d:"clear, transparent",diff:"hard"},
{w:"linchpin",p:"n.",d:"something holding parts together",diff:"hard"},
{w:"lithe",p:"adj.",d:"graceful, flexible",diff:"medium"},
{w:"litigant",p:"n.",d:"someone engaged in a lawsuit",diff:"hard"},
{w:"lucid",p:"adj.",d:"clear, understandable",diff:"easy"},
{w:"lugubrious",p:"adj.",d:"looking or sounding sad and dismal",diff:"hard"},
{w:"luminous",p:"adj.",d:"brightly shining",diff:"easy"},
{w:"lurid",p:"adj.",d:"ghastly, sensational",diff:"medium"},
{w:"maelstrom",p:"n.",d:"destructive whirlpool",diff:"medium"},
{w:"magnanimity",p:"n.",d:"the quality of being magnanimous; generous nobility",diff:"hard"},
{w:"magnanimous",p:"adj.",d:"noble, generous",diff:"medium"},
{w:"malediction",p:"n.",d:"a curse",diff:"hard"},
{w:"malevolent",p:"adj.",d:"wanting harm to befall others",diff:"medium"},
{w:"malleable",p:"adj.",d:"capable of being shaped",diff:"medium"},
{w:"mandate",p:"n.",d:"authoritative command",diff:"easy"},
{w:"manifest",p:"adj.",d:"obvious; to show plainly",diff:"easy"},
{w:"manifold",p:"adj.",d:"diverse, varied",diff:"easy"},
{w:"maudlin",p:"adj.",d:"weakly sentimental",diff:"hard"},
{w:"maverick",p:"n.",d:"independent, nonconformist",diff:"easy"},
{w:"mawkish",p:"adj.",d:"sick sentimentality",diff:"hard"},
{w:"maxim",p:"n.",d:"common saying expressing a principle",diff:"easy"},
{w:"meager",p:"adj.",d:"deficient in size or quality",diff:"medium"},
{w:"medley",p:"n.",d:"mixture of differing things",diff:"easy"},
{w:"mendacious",p:"adj.",d:"lying, false",diff:"hard"},
{w:"mercurial",p:"adj.",d:"rapid change in temperament",diff:"medium"},
{w:"meritorious",p:"adj.",d:"worthy of esteem or reward",diff:"medium"},
{w:"metamorphosis",p:"n.",d:"change of form or substance",diff:"medium"},
{w:"meticulous",p:"adj.",d:"extremely careful with details",diff:"easy"},
{w:"mitigate",p:"v.",d:"to make less violent or alleviate",diff:"easy"},
{w:"moderate",p:"adj.",d:"not extreme",diff:"easy"},
{w:"modicum",p:"n.",d:"a small amount",diff:"medium"},
{w:"modulate",p:"v.",d:"to pass from one state to another",diff:"medium"},
{w:"mollify",p:"v.",d:"to soften in temper",diff:"hard"},
{w:"morass",p:"n.",d:"swamp; something trapping or confusing",diff:"hard"},
{w:"mores",p:"n.",d:"moral attitudes or customs of a group",diff:"medium"},
{w:"morose",p:"adj.",d:"gloomy, sullen",diff:"medium"},
{w:"multifarious",p:"adj.",d:"great diversity or variety",diff:"hard"},
{w:"mundane",p:"adj.",d:"commonplace, worldly",diff:"easy"},
{w:"munificence",p:"n.",d:"generosity in giving",diff:"hard"},
{w:"mutable",p:"adj.",d:"able to change",diff:"medium"},
{w:"myriad",p:"adj.",d:"consisting of a very great number",diff:"easy"},
{w:"nadir",p:"n.",d:"the lowest point",diff:"medium"},
{w:"nascent",p:"adj.",d:"coming into existence",diff:"medium"},
{w:"nebulous",p:"adj.",d:"vaguely defined, cloudy",diff:"medium"},
{w:"nefarious",p:"adj.",d:"heinously villainous",diff:"medium"},
{w:"negligent",p:"adj.",d:"habitually careless",diff:"easy"},
{w:"neophyte",p:"n.",d:"young or inexperienced person",diff:"hard"},
{w:"nocturnal",p:"adj.",d:"relating to night",diff:"easy"},
{w:"noisome",p:"adj.",d:"unpleasant smell",diff:"hard"},
{w:"nomadic",p:"adj.",d:"wandering place to place",diff:"medium"},
{w:"nominal",p:"adj.",d:"trifling, insignificant",diff:"easy"},
{w:"nonchalant",p:"adj.",d:"lacking concern, indifference",diff:"medium"},
{w:"nondescript",p:"adj.",d:"lacking distinctive character",diff:"medium"},
{w:"notorious",p:"adj.",d:"widely and unfavorably known",diff:"easy"},
{w:"novice",p:"n.",d:"beginner",diff:"easy"},
{w:"noxious",p:"adj.",d:"harmful, unwholesome",diff:"medium"},
{w:"nuance",p:"n.",d:"slight variation in meaning or tone",diff:"medium"},
{w:"nurture",p:"v.",d:"to assist development",diff:"easy"},
{w:"obdurate",p:"adj.",d:"unyielding to persuasion",diff:"hard"},
{w:"obfuscate",p:"v.",d:"to render incomprehensible",diff:"hard"},
{w:"obfuscation",p:"n.",d:"the action of making something unclear",diff:"medium"},
{w:"oblique",p:"adj.",d:"not straightforward",diff:"easy"},
{w:"oblivious",p:"adj.",d:"lacking awareness",diff:"easy"},
{w:"obscure",p:"adj.",d:"unclear, partially hidden",diff:"easy"},
{w:"obsequious",p:"adj.",d:"excessively compliant or submissive",diff:"hard"},
{w:"obsolete",p:"adj.",d:"no longer used, out of date",diff:"easy"},
{w:"obstinate",p:"adj.",d:"stubborn",diff:"medium"},
{w:"obstreperous",p:"adj.",d:"noisy, unruly",diff:"hard"},
{w:"obtuse",p:"adj.",d:"lacking quickness of intellect",diff:"medium"},
{w:"odious",p:"adj.",d:"instilling hatred or displeasure",diff:"medium"},
{w:"officious",p:"adj.",d:"offering unwanted services",diff:"hard"},
{w:"ominous",p:"adj.",d:"foreboding evil",diff:"easy"},
{w:"onerous",p:"adj.",d:"burdensome",diff:"medium"},
{w:"opulent",p:"adj.",d:"rich abundance, ostentatious",diff:"medium"},
{w:"oration",p:"n.",d:"formal speech",diff:"medium"},
{w:"ornate",p:"adj.",d:"highly elaborate, decorated",diff:"medium"},
{w:"orthodox",p:"adj.",d:"conventional",diff:"easy"},
{w:"oscillate",p:"v.",d:"to sway side to side",diff:"medium"},
{w:"ostensible",p:"adj.",d:"appearing as such, seemingly",diff:"medium"},
{w:"ostentatious",p:"adj.",d:"excessively showy",diff:"medium"},
{w:"ostracism",p:"n.",d:"exclusion from a group",diff:"hard"},
{w:"pacific",p:"adj.",d:"soothing",diff:"easy"},
{w:"palatable",p:"adj.",d:"agreeable to taste",diff:"medium"},
{w:"palette",p:"n.",d:"range of colors or qualities",diff:"easy"},
{w:"palliate",p:"v.",d:"to reduce severity",diff:"hard"},
{w:"pallid",p:"adj.",d:"lacking color",diff:"hard"},
{w:"panacea",p:"n.",d:"remedy for all ills",diff:"medium"},
{w:"paradigm",p:"n.",d:"perfect pattern or model",diff:"easy"},
{w:"paradox",p:"n.",d:"apparently contradictory statement",diff:"easy"},
{w:"paragon",p:"n.",d:"model of excellence",diff:"medium"},
{w:"paramount",p:"adj.",d:"greatest in importance",diff:"easy"},
{w:"pariah",p:"n.",d:"an outcast",diff:"medium"},
{w:"parody",p:"n.",d:"satirical imitation",diff:"easy"},
{w:"parsimony",p:"n.",d:"frugality, stinginess",diff:"hard"},
{w:"partisan",p:"n.",d:"follower, adherent",diff:"easy"},
{w:"patent",p:"adj.",d:"readily seen, clear",diff:"easy"},
{w:"pathology",p:"n.",d:"deviation from normal",diff:"easy"},
{w:"pathos",p:"n.",d:"emotion of sympathy",diff:"medium"},
{w:"paucity",p:"n.",d:"small quantity",diff:"medium"},
{w:"pejorative",p:"adj.",d:"derogatory",diff:"medium"},
{w:"pellucid",p:"adj.",d:"easily intelligible, clear",diff:"hard"},
{w:"penchant",p:"n.",d:"tendency, preference",diff:"medium"},
{w:"penitent",p:"adj.",d:"remorseful",diff:"medium"},
{w:"penultimate",p:"adj.",d:"next to last",diff:"medium"},
{w:"penurious",p:"adj.",d:"miserly, stingy",diff:"hard"},
{w:"perfidious",p:"adj.",d:"disloyal, unfaithful",diff:"hard"},
{w:"perfunctory",p:"adj.",d:"showing little interest",diff:"medium"},
{w:"permeate",p:"v.",d:"to spread throughout",diff:"medium"},
{w:"pernicious",p:"adj.",d:"extremely destructive or harmful",diff:"medium"},
{w:"perniciousness",p:"n.",d:"the quality of having a harmful effect",diff:"hard"},
{w:"perplex",p:"v.",d:"to confuse",diff:"hard"},
{w:"perspicacity",p:"n.",d:"shrewdness, perceptiveness",diff:"hard"},
{w:"pert",p:"adj.",d:"flippant, bold",diff:"medium"},
{w:"pertinacious",p:"adj.",d:"stubbornly persistent",diff:"hard"},
{w:"perusal",p:"n.",d:"careful examination",diff:"hard"},
{w:"pervasive",p:"adj.",d:"tending to spread throughout",diff:"easy"},
{w:"petulance",p:"n.",d:"rudeness, irritability",diff:"hard"},
{w:"philanthropic",p:"adj.",d:"charitable",diff:"easy"},
{w:"phlegmatic",p:"adj.",d:"uninterested, unresponsive",diff:"hard"},
{w:"pillage",p:"v.",d:"to seize or plunder",diff:"medium"},
{w:"pinnacle",p:"n.",d:"highest point",diff:"easy"},
{w:"pithy",p:"adj.",d:"concisely meaningful",diff:"medium"},
{w:"pittance",p:"n.",d:"very small amount of money",diff:"medium"},
{w:"placate",p:"v.",d:"to ease anger, soothe",diff:"medium"},
{w:"placid",p:"adj.",d:"calm, peaceful",diff:"medium"},
{w:"platitude",p:"n.",d:"uninspired remark, cliche",diff:"hard"},
{w:"plaudits",p:"n.",d:"enthusiastic approval",diff:"hard"},
{w:"plausible",p:"adj.",d:"believable, reasonable",diff:"easy"},
{w:"plenitude",p:"n.",d:"an abundance",diff:"hard"},
{w:"plethora",p:"n.",d:"an abundance, excess",diff:"easy"},
{w:"pliable",p:"adj.",d:"flexible",diff:"medium"},
{w:"poignant",p:"adj.",d:"deeply affecting, moving",diff:"easy"},
{w:"polemic",p:"n.",d:"aggressive argument against an opinion",diff:"medium"},
{w:"portent",p:"n.",d:"an omen",diff:"hard"},
{w:"potable",p:"adj.",d:"suitable for drinking",diff:"medium"},
{w:"potentate",p:"n.",d:"one with great power or ruler",diff:"hard"},
{w:"pragmatic",p:"adj.",d:"practical",diff:"easy"},
{w:"precipice",p:"n.",d:"face of a cliff",diff:"medium"},
{w:"preclude",p:"v.",d:"to prevent",diff:"medium"},
{w:"precocious",p:"adj.",d:"advanced, developing early",diff:"medium"},
{w:"predilection",p:"n.",d:"preference or inclination",diff:"medium"},
{w:"preponderance",p:"n.",d:"superiority in importance or quantity",diff:"medium"},
{w:"prepossessing",p:"adj.",d:"occupying the mind exclusively",diff:"hard"},
{w:"presage",p:"n.",d:"an omen",diff:"hard"},
{w:"prescient",p:"adj.",d:"having foreknowledge",diff:"medium"},
{w:"prescribe",p:"v.",d:"to lay down a rule",diff:"easy"},
{w:"presumptuous",p:"adj.",d:"disrespectfully bold",diff:"medium"},
{w:"pretense",p:"n.",d:"appearance intended to deceive",diff:"medium"},
{w:"primeval",p:"adj.",d:"original, ancient",diff:"medium"},
{w:"privation",p:"n.",d:"lacking basic necessities",diff:"hard"},
{w:"probity",p:"n.",d:"virtue, integrity",diff:"hard"},
{w:"proclivity",p:"n.",d:"strong inclination",diff:"hard"},
{w:"procure",p:"v.",d:"to obtain, acquire",diff:"medium"},
{w:"profane",p:"adj.",d:"lewd, indecent",diff:"medium"},
{w:"profligate",p:"adj.",d:"dissolute, extravagant",diff:"hard"},
{w:"profuse",p:"adj.",d:"plentiful, abundant",diff:"hard"},
{w:"promulgate",p:"v.",d:"to proclaim, make known",diff:"hard"},
{w:"propagate",p:"v.",d:"to multiply, spread",diff:"medium"},
{w:"propensity",p:"n.",d:"inclination, preference",diff:"medium"},
{w:"propitious",p:"adj.",d:"favorable",diff:"hard"},
{w:"propriety",p:"n.",d:"quality of being proper or decent",diff:"medium"},
{w:"prosaic",p:"adj.",d:"plain, lacking liveliness",diff:"medium"},
{w:"proscribe",p:"v.",d:"to condemn, outlaw",diff:"hard"},
{w:"protean",p:"adj.",d:"able to change shape, varied",diff:"hard"},
{w:"prowess",p:"n.",d:"extraordinary ability",diff:"easy"},
{w:"prudence",p:"n.",d:"cautious, circumspect",diff:"medium"},
{w:"prurient",p:"adj.",d:"extraordinary interest in sex",diff:"hard"},
{w:"puerile",p:"adj.",d:"juvenile, immature",diff:"hard"},
{w:"pugnacious",p:"adj.",d:"quarrelsome, combative",diff:"hard"},
{w:"pulchritude",p:"n.",d:"physical beauty",diff:"hard"},
{w:"punctilious",p:"adj.",d:"eager to follow rules",diff:"hard"},
{w:"pungent",p:"adj.",d:"pointed, sharp smell",diff:"medium"},
{w:"punitive",p:"adj.",d:"involving punishment",diff:"easy"},
{w:"putrid",p:"adj.",d:"rotten, foul",diff:"medium"},
{w:"quagmire",p:"n.",d:"a difficult situation",diff:"medium"},
{w:"quaint",p:"adj.",d:"charmingly old-fashioned",diff:"easy"},
{w:"quandary",p:"n.",d:"perplexed, unresolvable state",diff:"medium"},
{w:"quell",p:"v.",d:"to control or diffuse",diff:"medium"},
{w:"querulous",p:"adj.",d:"whiny, complaining",diff:"hard"},
{w:"quixotic",p:"adj.",d:"idealistic, impractical",diff:"hard"},
{w:"quotidian",p:"adj.",d:"daily",diff:"hard"},
{w:"rail",p:"v.",d:"to scold, protest",diff:"easy"},
{w:"rancid",p:"adj.",d:"terrible taste or smell",diff:"medium"},
{w:"rancor",p:"n.",d:"deep, bitter resentment",diff:"medium"},
{w:"rapport",p:"n.",d:"mutual understanding or harmony",diff:"medium"},
{w:"rash",p:"adj.",d:"hasty, incautious",diff:"easy"},
{w:"raucous",p:"adj.",d:"loud, boisterous",diff:"medium"},
{w:"raze",p:"v.",d:"to demolish, level",diff:"medium"},
{w:"rebuke",p:"v.",d:"to scold, criticize",diff:"medium"},
{w:"recalcitrant",p:"adj.",d:"defiant, unapologetic",diff:"medium"},
{w:"recapitulate",p:"v.",d:"to sum up, repeat",diff:"hard"},
{w:"reciprocate",p:"v.",d:"to give in return",diff:"medium"},
{w:"reclusive",p:"adj.",d:"solitary, shunning society",diff:"medium"},
{w:"reconcile",p:"v.",d:"to return to harmony; to make consistent",diff:"easy"},
{w:"rectitude",p:"n.",d:"uprightness, morality",diff:"hard"},
{w:"redoubtable",p:"adj.",d:"formidable; commanding respect",diff:"hard"},
{w:"refract",p:"v.",d:"to distort, change",diff:"hard"},
{w:"refurbish",p:"v.",d:"to restore, clean up",diff:"medium"},
{w:"refute",p:"v.",d:"to prove wrong",diff:"medium"},
{w:"regurgitate",p:"v.",d:"to vomit; to throw back exactly",diff:"hard"},
{w:"relegate",p:"v.",d:"to assign to proper or inferior place",diff:"medium"},
{w:"relish",p:"v.",d:"to enjoy",diff:"easy"},
{w:"remedial",p:"adj.",d:"intended to repair gaps",diff:"medium"},
{w:"remiss",p:"adj.",d:"negligent",diff:"medium"},
{w:"renovate",p:"v.",d:"to restore; enlarge or prettify",diff:"medium"},
{w:"renown",p:"n.",d:"honor, acclaim",diff:"medium"},
{w:"renunciation",p:"n.",d:"rejection",diff:"medium"},
{w:"repentant",p:"adj.",d:"penitent, sorry",diff:"medium"},
{w:"replete",p:"adj.",d:"full, abundant",diff:"medium"},
{w:"repose",p:"v.",d:"to rest, lie down",diff:"medium"},
{w:"reprehensible",p:"adj.",d:"deserving rebuke",diff:"medium"},
{w:"reprieve",p:"n.",d:"temporary delay of punishment",diff:"medium"},
{w:"reproach",p:"v.",d:"to scold, disapprove",diff:"medium"},
{w:"reprobate",p:"adj.",d:"evil, unprincipled",diff:"hard"},
{w:"reprove",p:"v.",d:"to scold, rebuke",diff:"hard"},
{w:"repudiate",p:"v.",d:"to reject, refuse",diff:"medium"},
{w:"repulse",p:"v.",d:"to disgust; to push back",diff:"medium"},
{w:"reputable",p:"adj.",d:"of good reputation",diff:"easy"},
{w:"requisition",p:"n.",d:"demand for goods",diff:"medium"},
{w:"rescind",p:"v.",d:"to take back, repeal",diff:"medium"},
{w:"reservoir",p:"n.",d:"reserves; body of water",diff:"easy"},
{w:"resilient",p:"adj.",d:"able to recover",diff:"easy"},
{w:"resolute",p:"adj.",d:"firm, determined",diff:"medium"},
{w:"resolve",p:"v.",d:"to find solution; to firmly decide",diff:"easy"},
{w:"respite",p:"n.",d:"a break, rest",diff:"medium"},
{w:"resplendent",p:"adj.",d:"shiny, glowing",diff:"medium"},
{w:"restitution",p:"n.",d:"restoration to rightful owner",diff:"medium"},
{w:"restive",p:"adj.",d:"resistant, stubborn, impatient",diff:"hard"},
{w:"retract",p:"v.",d:"to withdraw",diff:"medium"},
{w:"revel",p:"v.",d:"to enjoy intensely",diff:"medium"},
{w:"revere",p:"v.",d:"to esteem, venerate",diff:"medium"},
{w:"revoke",p:"v.",d:"to take back",diff:"easy"},
{w:"rhapsodize",p:"v.",d:"to engage in excessive enthusiasm",diff:"hard"},
{w:"ribald",p:"adj.",d:"coarsely, crudely humorous",diff:"hard"},
{w:"rife",p:"adj.",d:"abundant",diff:"medium"},
{w:"ruminate",p:"v.",d:"to contemplate, reflect",diff:"hard"},
{w:"ruse",p:"n.",d:"a trick",diff:"medium"},
{w:"saccharine",p:"adj.",d:"sickeningly sweet",diff:"medium"},
{w:"sacrosanct",p:"adj.",d:"holy, should not be criticized",diff:"medium"},
{w:"sagacity",p:"n.",d:"shrewdness, sound perspective",diff:"hard"},
{w:"salient",p:"adj.",d:"significant, conspicuous",diff:"medium"},
{w:"salutation",p:"n.",d:"a greeting",diff:"medium"},
{w:"salve",p:"n.",d:"a soothing balm",diff:"medium"},
{w:"sanctimonious",p:"adj.",d:"hypocritical appearance of piety",diff:"medium"},
{w:"sanguine",p:"adj.",d:"optimistic, cheery",diff:"medium"},
{w:"satiate",p:"v.",d:"to satisfy excessively",diff:"hard"},
{w:"scathing",p:"adj.",d:"sharp, critical, hurtful",diff:"medium"},
{w:"scintillating",p:"adj.",d:"sparkling",diff:"medium"},
{w:"scrupulous",p:"adj.",d:"painstaking, careful",diff:"medium"},
{w:"scurrilous",p:"adj.",d:"vulgar, coarse",diff:"hard"},
{w:"sedentary",p:"adj.",d:"sitting, settled",diff:"medium"},
{w:"semaphore",p:"n.",d:"a visual signal",diff:"medium"},
{w:"seminal",p:"adj.",d:"original, important, creating a field",diff:"easy"},
{w:"sensual",p:"adj.",d:"sensory gratification, often sexual",diff:"easy"},
{w:"sensuous",p:"adj.",d:"sensory gratification",diff:"medium"},
{w:"serendipity",p:"n.",d:"luck, finding good things without looking",diff:"medium"},
{w:"serene",p:"adj.",d:"calm, untroubled",diff:"easy"},
{w:"servile",p:"adj.",d:"subservient",diff:"medium"},
{w:"sinuous",p:"adj.",d:"lithe, serpentine",diff:"medium"},
{w:"sobriety",p:"n.",d:"sedate, calm",diff:"medium"},
{w:"solicitous",p:"adj.",d:"concerned, attentive",diff:"hard"},
{w:"solipsistic",p:"adj.",d:"believing only oneself exists",diff:"hard"},
{w:"soluble",p:"adj.",d:"able to dissolve",diff:"easy"},
{w:"solvent",p:"adj.",d:"substance that dissolves; able to pay debts",diff:"easy"},
{w:"somnolent",p:"adj.",d:"sleepy, drowsy",diff:"hard"},
{w:"sophomoric",p:"adj.",d:"immature, uninformed",diff:"hard"},
{w:"sovereign",p:"adj.",d:"having absolute authority",diff:"easy"},
{w:"speculative",p:"adj.",d:"not based in fact",diff:"easy"},
{w:"spurious",p:"adj.",d:"false but designed to seem plausible",diff:"medium"},
{w:"stagnate",p:"v.",d:"to become inactive",diff:"medium"},
{w:"staid",p:"adj.",d:"sedate, serious",diff:"medium"},
{w:"stingy",p:"adj.",d:"not generous",diff:"medium"},
{w:"stoic",p:"adj.",d:"unaffected by passion or feeling",diff:"medium"},
{w:"stolid",p:"adj.",d:"expressing little sensibility",diff:"hard"},
{w:"strenuous",p:"adj.",d:"requiring tremendous energy",diff:"medium"},
{w:"strident",p:"adj.",d:"harsh, loud",diff:"medium"},
{w:"stupefy",p:"v.",d:"to astonish, make insensible",diff:"hard"},
{w:"subjugate",p:"v.",d:"to bring under control",diff:"medium"},
{w:"sublime",p:"adj.",d:"lofty, grand",diff:"easy"},
{w:"submissive",p:"adj.",d:"easily yielding",diff:"easy"},
{w:"succinct",p:"adj.",d:"compact precision",diff:"medium"},
{w:"superfluous",p:"adj.",d:"exceeding what is necessary",diff:"medium"},
{w:"surfeit",p:"n.",d:"overabundant supply",diff:"hard"},
{w:"surmise",p:"v.",d:"to infer with little evidence",diff:"medium"},
{w:"surreptitious",p:"adj.",d:"stealthy",diff:"hard"},
{w:"surrogate",p:"n.",d:"one acting in place of another",diff:"easy"},
{w:"swarthy",p:"adj.",d:"dark complexion",diff:"hard"},
{w:"sycophancy",p:"n.",d:"obsequious behavior; excessive flattery for self-gain",diff:"hard"},
{w:"sycophant",p:"n.",d:"one who flatters for self-gain",diff:"hard"},
{w:"tacit",p:"adj.",d:"expressed without words",diff:"medium"},
{w:"taciturn",p:"adj.",d:"not inclined to talk",diff:"hard"},
{w:"tangential",p:"adj.",d:"incidental, peripheral",diff:"medium"},
{w:"tantamount",p:"adj.",d:"equivalent in value or significance",diff:"medium"},
{w:"tedious",p:"adj.",d:"dull, boring",diff:"easy"},
{w:"temerity",p:"n.",d:"audacity, recklessness",diff:"medium"},
{w:"temperance",p:"n.",d:"moderation",diff:"medium"},
{w:"tenable",p:"adj.",d:"able to be defended",diff:"medium"},
{w:"tenuous",p:"adj.",d:"having little substance or strength",diff:"medium"},
{w:"terrestrial",p:"adj.",d:"relating to land",diff:"easy"},
{w:"timorous",p:"adj.",d:"timid, fearful",diff:"hard"},
{w:"tirade",p:"n.",d:"long speech with harsh language",diff:"medium"},
{w:"toady",p:"n.",d:"one who flatters for favors",diff:"hard"},
{w:"tome",p:"n.",d:"a large book",diff:"easy"},
{w:"torpid",p:"adj.",d:"lethargic, dormant",diff:"hard"},
{w:"torrid",p:"adj.",d:"intense heat, passionate",diff:"medium"},
{w:"tortuous",p:"adj.",d:"winding",diff:"medium"},
{w:"tractable",p:"adj.",d:"easily controlled",diff:"hard"},
{w:"tranquil",p:"adj.",d:"calm",diff:"medium"},
{w:"transgress",p:"v.",d:"to violate, go over limit",diff:"hard"},
{w:"transient",p:"adj.",d:"passing through briefly",diff:"easy"},
{w:"transmute",p:"v.",d:"to change or alter form",diff:"hard"},
{w:"travesty",p:"n.",d:"grossly inferior imitation",diff:"medium"},
{w:"tremulous",p:"adj.",d:"fearful",diff:"hard"},
{w:"trenchant",p:"adj.",d:"effective, articulate, clear-cut",diff:"hard"},
{w:"trepidation",p:"n.",d:"fear, apprehension",diff:"medium"},
{w:"trite",p:"adj.",d:"not original, overused",diff:"medium"},
{w:"truculent",p:"adj.",d:"ready to fight, cruel",diff:"hard"},
{w:"truncate",p:"v.",d:"to shorten by cutting off",diff:"hard"},
{w:"turgid",p:"adj.",d:"swollen, excessively embellished",diff:"hard"},
{w:"turpitude",p:"n.",d:"depravity, moral corruption",diff:"hard"},
{w:"ubiquitous",p:"adj.",d:"existing everywhere",diff:"easy"},
{w:"umbrage",p:"n.",d:"resentment, offense",diff:"hard"},
{w:"uncanny",p:"adj.",d:"supernatural character",diff:"easy"},
{w:"unctuous",p:"adj.",d:"smooth or greasy in manner",diff:"hard"},
{w:"undulate",p:"v.",d:"to move in waves",diff:"hard"},
{w:"upbraid",p:"v.",d:"to criticize or scold severely",diff:"hard"},
{w:"usurp",p:"v.",d:"to seize by force",diff:"medium"},
{w:"utilitarian",p:"adj.",d:"relating to usefulness",diff:"medium"},
{w:"utopia",p:"n.",d:"imaginary place of perfection",diff:"easy"},
{w:"vacillate",p:"v.",d:"to fluctuate, hesitate",diff:"hard"},
{w:"vacuous",p:"adj.",d:"lack of content or ideas, stupid",diff:"medium"},
{w:"validate",p:"v.",d:"to confirm, support",diff:"easy"},
{w:"vapid",p:"adj.",d:"lacking liveliness, dull",diff:"medium"},
{w:"variegated",p:"adj.",d:"diversified, distinctly marked",diff:"medium"},
{w:"vehemently",p:"adv.",d:"marked by intense force or emotion",diff:"medium"},
{w:"veneer",p:"n.",d:"superficial or deceptive appearance",diff:"medium"},
{w:"venerable",p:"adj.",d:"deserving respect due to age or achievement",diff:"easy"},
{w:"venerate",p:"v.",d:"to regard with respect",diff:"hard"},
{w:"veracity",p:"n.",d:"conformity to facts; accuracy",diff:"medium"},
{w:"verbose",p:"adj.",d:"wordy",diff:"medium"},
{w:"verdant",p:"adj.",d:"green",diff:"medium"},
{w:"vestige",p:"n.",d:"mark or trace of something lost",diff:"medium"},
{w:"vex",p:"v.",d:"to confuse or annoy",diff:"medium"},
{w:"vicarious",p:"adj.",d:"experiencing through another",diff:"medium"},
{w:"vicissitude",p:"n.",d:"event occurring by chance",diff:"hard"},
{w:"vigilant",p:"adj.",d:"watchful, alert",diff:"easy"},
{w:"vilify",p:"v.",d:"to lower importance, defame",diff:"medium"},
{w:"vindicate",p:"v.",d:"to avenge; free from allegation",diff:"medium"},
{w:"vindictive",p:"adj.",d:"vengeful",diff:"medium"},
{w:"virtuoso",p:"n.",d:"one who excels in an art",diff:"medium"},
{w:"viscous",p:"adj.",d:"not free flowing, syrupy",diff:"medium"},
{w:"vitriolic",p:"adj.",d:"having caustic quality",diff:"medium"},
{w:"vituperate",p:"v.",d:"to berate",diff:"hard"},
{w:"vivacious",p:"adj.",d:"lively, sprightly",diff:"medium"},
{w:"vocation",p:"n.",d:"profession",diff:"easy"},
{w:"vociferous",p:"adj.",d:"loud, boisterous",diff:"medium"},
{w:"wallow",p:"v.",d:"to roll indolently; remain helpless",diff:"medium"},
{w:"wane",p:"v.",d:"to decrease, dwindle",diff:"medium"},
{w:"wanton",p:"adj.",d:"undisciplined, lewd",diff:"medium"},
{w:"whimsical",p:"adj.",d:"fanciful, full of whims",diff:"medium"},
{w:"wily",p:"adj.",d:"crafty, sly",diff:"medium"},
{w:"winsome",p:"adj.",d:"charming, pleasing",diff:"hard"},
{w:"wistful",p:"adj.",d:"full of yearning; musingly sad",diff:"medium"},
{w:"wizened",p:"adj.",d:"dry, shrunken, wrinkled",diff:"hard"},
{w:"wrath",p:"n.",d:"vengeful anger",diff:"easy"},
{w:"yoke",p:"v.",d:"to join, link",diff:"medium"},
{w:"zealous",p:"adj.",d:"fervent, filled with eagerness",diff:"medium"},
{w:"zenith",p:"n.",d:"highest point",diff:"medium"},
{w:"zephyr",p:"n.",d:"a gentle breeze",diff:"medium"}
];
